### ISSUE TITLE
in Mailing list - List information  Unable to change list owner address   

### ISSUE THREAD

**Issue by dickmo** [justingit/dada-mail#1016]
Unable to change list owner email address   screen does nothing  Version 11.13.0  or 11.13.1

**Comment by justingit** [comment]
Are there any javascript errors being reported in the console?

**Comment by dickmo** [comment]
Today it is working.  Version 11.13.1

  After clicking the save button  takes about 3 seconds then the screen 
shows the changes





Richard Mourino

------ Original Message ------
From: "Justin J" ***@***.***>
To: "justingit/dada-mail" ***@***.***>
Cc: "dickmo" ***@***.***>; "Author" 
***@***.***>
Sent: 5/17/2021 8:35:09 PM
Subject: Re: [justingit/dada-mail] in Mailing list - List information 
Unable to change list owner address (#1016)

**Comment by dickmo** [comment]
Issue came back.

It let me change it twice then It would not let me do it again.

I changed value in List owner email ( mailing list  list info screen)  
to a new value.  Then tried to change it back then no response.
I will wait an hour and try again.







Richard Mourino

------ Original Message ------
From: "Justin J" ***@***.***>
To: "justingit/dada-mail" ***@***.***>
Cc: "dickmo" ***@***.***>; "Author" 
***@***.***>
Sent: 5/18/2021 1:06:02 PM
Subject: Re: [justingit/dada-mail] in Mailing list - List information 
Unable to change list owner address (#1016)

**Comment by dickmo** [comment]
Now it will not allow me to change anything on the mailing list.   Tried added a new list that all works  but trying
to modify any old list does not work.

**Comment by justingit** [comment]
I mean the browser's javascript console: 

https://support.cytobank.org/hc/en-us/articles/206273618-How-to-open-and-use-your-browser-s-JavaScript-console

Yes - there is an option to clone a list when you create a new list.

**Comment by dickmo** [comment]
Is this what you are looking for?

Tried to clone an old list same result no response

Layout was forced before the page was fully loaded. If stylesheets are 
not yet loaded this may cause a flash of unstyled 
content.modernizr.js:8:4005 
<https://testemails.sbccsail.org/dada_mail_support_files/static/javascripts/vendor/modernizr.js?v=11.13.1%2005%2F15%2F21>
Layout was forced before the page was fully loaded. If stylesheets are 
not yet loaded this may cause a flash of unstyled 
content.modernizr.js:8:4005 
<https://testemails.sbccsail.org/dada_mail_support_files/static/javascripts/vendor/modernizr.js?v=11.13.1%2005%2F15%2F21>
GEThttps://testemails.sbccsail.org/favicon.ico[HTTP/1.1 404 Not Found 
0ms]
Source map error: Error: request failed with status 404 Resource URL: 
https://testemails.sbccsail.org/dada_mail_support_files/static/css/vendor/foundation/app.css?v=11.13.1%2005%2F15%2F21 
Source Map URL: app.css.map

​




Richard Mourino

------ Original Message ------
From: "Justin J" ***@***.***>
To: "justingit/dada-mail" ***@***.***>
Cc: "dickmo" ***@***.***>; "Author" 
***@***.***>
Sent: 5/19/2021 11:47:45 AM
Subject: Re: [justingit/dada-mail] in Mailing list - List information 
Unable to change list owner address (#1016)

**Comment by dickmo** [comment]
Added in dadamailxxl module into cpanel  now its working

Maybe the old one got damaged.

Tried to re install dadamail budle and it failed but the dadamailxxl 
went in clean
and now the screen is working.





Richard Mourino

------ Original Message ------
From: "Richard" ***@***.***>
To: "justingit/dada-mail" 
***@***.***>
Sent: 5/19/2021 1:01:40 PM
Subject: Re[2]: [justingit/dada-mail] in Mailing list - List information 
Unable to change list owner address (#1016)

>Is this what you are looking for?
>
>Tried to clone an old list same result no response
>
>Layout was forced before the page was fully loaded. If stylesheets are 
>not yet loaded this may cause a flash of unstyled 
>content.modernizr.js:8:4005 
><https://testemails.sbccsail.org/dada_mail_support_files/static/javascripts/vendor/modernizr.js?v=11.13.1%2005%2F15%2F21>
>Layout was forced before the page was fully loaded. If stylesheets are 
>not yet loaded this may cause a flash of unstyled 
>content.modernizr.js:8:4005 
><https://testemails.sbccsail.org/dada_mail_support_files/static/javascripts/vendor/modernizr.js?v=11.13.1%2005%2F15%2F21>
>GEThttps://testemails.sbccsail.org/favicon.ico[HTTP/1.1 404 Not Found 
>0ms]
>Source map error: Error: request failed with status 404 Resource URL: 
>https://testemails.sbccsail.org/dada_mail_support_files/static/css/vendor/foundation/app.css?v=11.13.1%2005%2F15%2F21 
>Source Map URL: app.css.map
>
>​
>
>
>
>
>Richard Mourino
>
>------ Original Message ------
>From: "Justin J" ***@***.***>
>To: "justingit/dada-mail" ***@***.***>
>Cc: "dickmo" ***@***.***>; "Author" 
***@***.***>

**Comment by dickmo** [comment]
Getting the bundle back into my server may be done.  The normal cpanel 
install keeps failing.
My server vendor was able to get the modules back into my perl library 
but still having
Problems in modifying that particular screen. (Mailing List List 
Information)

Here is the strange thing.
Creating a new list works  can modify it with no problem.
Trying to modify an existing one fails
Cloning an existing one also fails (in modifying data.

ONLY trying to modify the Mailing List   List Information on older list 
fails.
Can you think of any data field long ago that may be causing this.

I am going to try and find what data field is doing this by re creating 
a manual created new list using
the info from an old list and see if that resolves this.








Richard Mourino

------ Original Message ------
From: "Justin J" ***@***.***>
To: "justingit/dada-mail" ***@***.***>
Cc: "dickmo" ***@***.***>; "Author" 
***@***.***>
Sent: 5/19/2021 11:47:45 AM
Subject: Re: [justingit/dada-mail] in Mailing list - List information 
Unable to change list owner address (#1016)

**Comment by dickmo** [comment]
Located the problem.

In the mailing List     List Information
I had a lot of URL's  and maybe it either did not like one of them or 
the format and got stuck

I removed the URLS  (all) except the website url and it now works .

I just hard coded the urls into the custom mass mailing layout

It did not like by Facebook link or the twitter one which I was using 
for some other web address.

The screen seems to ignore the action of unchecking    (Validate URL 
below)

With these changes it is totally working


Richard Mourino

**Comment by justingit** [comment]
If there's a specific value that you're filling out, or if there's an error in the JavaScript console you can share that's related to this problem, those things can help with reporting this as an issue. Without those, I have nothing to work with when trying to solve the underlying problem.

**Comment by dickmo** [comment]
Did not see any error in console  (if i did it correct)

But here was the url that I had used in the facebook slot

https://facebook.com/groups/southbaycruisingclub/?ref=bookmarks

In the twitter slot

https://www.sbccracing.org

Just tested it again  It is the twitter entry that held it up.




Richard Mourino

------ Original Message ------
From: "Justin J" ***@***.***>
To: "justingit/dada-mail" ***@***.***>
Cc: "dickmo" ***@***.***>; "Author" 
***@***.***>
Sent: 5/20/2021 1:29:51 PM
Subject: Re: [justingit/dada-mail] in Mailing list - List information 
Unable to change list owner address (#1016)
