### ISSUE TITLE
Lose all css when under https://

### ISSUE THREAD

**Issue by Henleygraphics** [justingit/dada-mail#1040]
<img width="1252" alt="Screen Shot 2021-07-23 at 11 34 50 AM" src="https://user-images.githubusercontent.com/49725705/126807173-78f46a81-a79c-4718-96e7-5122453b92ad.png">

**Comment by justingit** [comment]
You'll have to do a re-configuration of the app, as outlined here: 

https://blog.dadamailproject.com/2017/06/23/configuring-your-dada-mail-install-to-work-over-https/

Cheers,

**Comment by Henleygraphics** [comment]
ThanksRaphael WightmanWeb DesignerHenley Graphics 567-238-4561 - Direct Line800-772-5488 - Toll Free419-994-3396 - Faxwww.Henley-Graphics.com 


-------- Original Message --------
Subject: Re: [justingit/dada-mail] Lose all css when under https://
(#1040)
From: Justin J ***@***.***>
Date: Fri, July 23, 2021 10:54 am
To: justingit/dada-mail ***@***.***>
Cc: Henleygraphics ***@***.***>,  Author
***@***.***>

 You'll have to do a re-configuration of the app, as outlined here: https://blog.dadamailproject.com/2017/06/23/configuring-your-dada-mail-install-to-work-over-https/ Cheers, —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
