### ISSUE TITLE
Duplicate entry error on clickthrough

### ISSUE THREAD

**Issue by dickmo** [justingit/dada-mail#1050]
Seems to get this most but not all of the time when there is a clickthrough  .  It also (sometimes)  erases the added fields in the profile_fields for that user when the error happens.   I have seen this from many different past versions so it does not seem to be related to any new release.  

DBD::mysql::st execute failed: Duplicate entry 'jwerkjr@gmail.com' for key 'email' at DADA/Profile/Fields/baseSQL.pm line 126.
DBD::mysql::st execute failed: Duplicate entry 'jwerkjr@gmail.com' for key 'email' at DADA/Profile/Fields/baseSQL.pm line 126.
DBD::mysql::st execute failed: Duplicate entry 'jwerkjr@gmail.com' for key 'email' at DADA/Profile/Fields/baseSQL.pm line 126.
DBD::mysql::st execute failed: Duplicate entry 'jwerkjr@gmail.com' for key 'email' at DADA/Profile/Fields/baseSQL.pm line 126.
DBD::mysql::st execute failed: Duplicate entry 'jwerkjr@gmail.com' for key 'email' at DADA/Profile/Fields/baseSQL.pm line 126.
problems updating fields with geo ip data: cannot do statement (at insert)! Duplicate entry 'jwerkjr@gmail.com' for key 'email'
 at DADA/Logging/Clickthrough/baseSQL.pm line 517.
 at DADA/Logging/Clickthrough/baseSQL.pm line 802.
problems updating fields with geo ip data: cannot do statement (at insert)! Duplicate entry 'jwerkjr@gmail.com' for key 'email'
 at DADA/Logging/Clickthrough/baseSQL.pm line 517.
 at DADA/Logging/Clickthrough/baseSQL.pm line 802.
problems updating fields with geo ip data: cannot do statement (at insert)! Duplicate entry 'jwerkjr@gmail.com' for key 'email'
 at DADA/Logging/Clickthrough/baseSQL.pm line 517.
 at DADA/Logging/Clickthrough/baseSQL.pm line 802.
problems updating fields with geo ip data: cannot do statement (at insert)! Duplicate entry 'jwerkjr@gmail.com' for key 'email'
 at DADA/Logging/Clickthrough/baseSQL.pm line 517.
 at DADA/Logging/Clickthrough/baseSQL.pm line 802.
problems updating fields with geo ip data: cannot do statement (at insert)! Duplicate entry 'jwerkjr@gmail.com' for key 'email'
 at DADA/Logging/Clickthrough/baseSQL.pm line 517.
 at DADA/Logging/Clickthrough/baseSQL.pm line 802.
DBD::mysql::st execute failed: Duplicate entry 'hmirchel@optonline.net' for key 'email' at DADA/Profile/Fields/baseSQL.pm line 126.
problems updating fields with geo ip data: cannot do statement (at insert)! Duplicate entry 'hmirchel@optonline.net' for key 'email'
 at DADA/Logging/Clickthrough/baseSQL.pm line 517.
 at DADA/Logging/Clickthrough/baseSQL.pm line 802.

**Comment by justingit** [comment]
What are the exact steps needed to recreate this issue?

**Comment by dickmo** [comment]
Using a very standard mass mailing list (announce_only) with an 
attachment (sometimes)  to our members (244 in total.)
Or it could contain a link to a web site photo page.

  The profile_field has 5 fields
  Last_name
  First_name
  Membership_type
  Date
  ip_number

  Members start opening the newsletter and some click the attachments if 
it is there.
  In the log some get this error  and their profile fields are then null 
.
  But it does not happen to all members.

  I am guessing that you delete the profile and then insert it back in 
when they open the newsletter.
  When they then click on the attachment maybe the code is trying to 
insert it again  as it is already there.
  I dont know the flow so I am just guessing.

  In Tracker
  Track message clickthroughs
   automatic
         auto track mailto links
   Track messages
    using embedded image



Richard Mourino

------ Original Message ------
From: "Justin J" ***@***.***>
To: "justingit/dada-mail" ***@***.***>
Cc: "dickmo" ***@***.***>; "Author" 
***@***.***>
Sent: 8/31/2021 12:45:13 PM
Subject: Re: [justingit/dada-mail] Duplicate entry error on clickthrough 
(#1050)

**Comment by dickmo** [comment]
For the last 2 hours trying to reproduce the error   was not able.
Maybe the new release might fix this random situation.







Richard Mourino

------ Original Message ------
From: "Justin J" ***@***.***>
To: "justingit/dada-mail" ***@***.***>
Cc: "dickmo" ***@***.***>; "Author" 
***@***.***>
Sent: 8/31/2021 12:45:13 PM
Subject: Re: [justingit/dada-mail] Duplicate entry error on clickthrough 
(#1050)
