### ISSUE TITLE
Dada mail support files that are backed up  after an update 

### ISSUE THREAD

**Issue by dickmo** [justingit/dada-mail#1051]
After one updates the software the update process creates backup file that are in the dada_mail_support directory.
However they are not readable and can cause errors if one is using a tar compress to backup the full dada-mail folder.  I just delete them .  Is this the way it should work ?

view of folder after update 
![image](https://user-images.githubusercontent.com/51383521/131696226-8cf807a7-334a-4898-85e1-0238a94a6618.png)

![image](https://user-images.githubusercontent.com/51383521/131696442-03cb6016-b9db-4916-8cdc-2fe5a80e3833.png)

**Comment by justingit** [comment]
Yes. The permissions of the directories are changed from 755 to 644 during backup.
