### ISSUE TITLE
When changing root password, I lose Control Panel menu and root privilege

### ISSUE THREAD

**Issue by cantoute** [justingit/dada-mail#1083]
So I had to change root password, I first tried using the plugin that is now marked depreciated, to I tried manually with same result.

changing those vars in `.dada_files/.configs/.dada_config`
```
$ROOT_PASS_IS_ENCRYPTED = 1; 

$PROGRAM_ROOT_PASSWORD  = 'zdrhlGbW9EY'; 
```

I can then login with the new password, but root features are disabled and the "Control Panel Settings" menu is gone.

I've retried using encrypted password or not... same thing.

**Comment by justingit** [comment]
Is your List Password, and Root Password the same?

**Comment by cantoute** [comment]
> Is your List Password, and Root Password the same?

No they are distinct.
It appears that something compares to the very first password used at setup to leverage root privileges.

**Comment by justingit** [comment]
>No they are distinct.

Are the first 8 characters the same? 

> It appears that something compares to the very first password used at setup to leverage root privileges.

No, nothing like that actually happens. 

Can you post a screenshot of what the list control panel looks like, when you're logged in using the root password?

**Comment by cantoute** [comment]
> > No they are distinct.
> 
> Are the first 8 characters the same?

This is the thing... both passwords had same prefix.
I used a new password with different first characters and it now works fine.

How come 8 first chars can be compared on an encrypted password?

Anyhow, you pointed out the reason.

Thanks very much.

**Comment by justingit** [comment]
I believe only the first 8 characters are used in the password - a limitation of crypt(): 

https://ftp.gnu.org/old-gnu/Manuals/glibc-2.2.3/html_node/libc_650.html
