### ISSUE TITLE
Can't upload files in 11.17.1 using core5_filemanager

### ISSUE THREAD

**Issue by philmck** [justingit/dada-mail#1085]
I'm getting a new error in Dada version 11.17.1  - I can't upload files and attach them.

This is a set of symptoms I haven't seen before - I can create a draft message, click the "Attachments" tab then "Select a file" and I see the list of files in core5_filemanager OK. When I try to upload a new file a popup says "New file(s) added successfully". But then that message is replaced with a popup "Error saving draft: Internal Error,  has your session expired?" and the file hasn't actually been uploaded. I can attach files that are already in the filemanager successfully.

I see the following error in the Apache error logs:

malformed header from script 'filemanager.pl': Bad header: Couldn't carry on at file, referer: https://www.skeptic.org.uk/dada_mail_support_files/core5_filemanager/index.html?custom_function=SetAttachmentUrl

**Comment by philmck** [comment]
Rolling back to a previous version of core5_filemanager hasn't helped.

**Comment by philmck** [comment]
The Dada error log shows several errors:

[Sun Jan  2 14:51:42 2022] filemanager.pl: Couldn't carry on at filemanager.pl line 372.
	(in cleanup) Can't access 'DESTROY' field in object of class Google::reCAPTCHA::v3 at /home/skeptic/cgi-bin/paranormal/DADA/App/Guts.pm line 3349.
[Sun Jan  2 14:52:03 2022] filemanager.pl: sysread() is deprecated on :utf8 handles. This will be a fatal error in Perl 5.30 at /home/skeptic/cgi-bin/paranormal/DADA/perllib/File/Slurp.pm line 225.
[Sun Jan  2 14:52:03 2022] filemanager.pl: CGI::param called in list context from filemanager.pl line 156, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /home/skeptic/cgi-bin/paranormal/DADA/perllib/CGI.pm line 414.
[Sun Jan  2 14:52:03 2022] filemanager.pl: sysread() is deprecated on :utf8 handles. This will be a fatal error in Perl 5.30 at /home/skeptic/cgi-bin/paranormal/DADA/perllib/File/Slurp.pm line 225.
[Sun Jan  2 14:52:03 2022] filemanager.pl: CGI::param called in list context from filemanager.pl line 156, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /home/skeptic/cgi-bin/paranormal/DADA/perllib/CGI.pm line 414.
[Sun Jan  2 14:52:15 2022] filemanager.pl: sysread() is deprecated on :utf8 handles. This will be a fatal error in Perl 5.30 at /home/skeptic/cgi-bin/paranormal/DADA/perllib/File/Slurp.pm line 225.
[Sun Jan  2 14:52:15 2022] filemanager.pl: CGI::param called in list context from filemanager.pl line 106, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /home/skeptic/cgi-bin/paranormal/DADA/perllib/CGI.pm line 414.

**Comment by justingit** [comment]
When this happens, are you then logged out of the Dada Mail list control panel?

**Comment by philmck** [comment]
My reply doesn't seem to have registered. Nothing happens immediately (just a spinning progress indicator) but I do have to re-login to the Dada Mail control panel to do anything so I think the answer is yes.

**Comment by philmck** [comment]
Rolling back to a previous version of Dada hasn't helped.

**Comment by justingit** [comment]
> Rolling back to a previous version of Dada hasn't helped.

I wouldn't think it would given, https://github.com/justingit/dada-mail/issues/1080

> but I do have to re-login to the Dada Mail control panel to do anything so I think the answer is yes.

Can you make sure that the check_security function in core5_filemanager-for-dada-mail/core5_filemanager/connectors/pl/filemanager.pl , of Core5FileManager looks like this: 

`sub check_security { 
	
	$q = CGI->new;
	# I bet this now has to be a json, something or other...
	require DADA::App::Guts; 


	$q->param('_csrf_token', $q->cookie('_csrf_token'));
	
    my ( $admin_list, $root_login, $checksout, $error_msg ) = DADA::App::Guts::check_list_security(
        -cgi_obj         => $q,
        -Function        => 'send_email send_url_email',
    );
	
    if ($checksout) {
		#... 
	}	
	else { 
		error("Sessioning Failed. Log in!"); 	
		exit();
	}
}`

**Comment by philmck** [comment]
Another error:
[Fri Jan 07 23:32:11.084495 2022] [cgid:error] [pid 27576:tid 140233943025408] [client 2a00:23c4:808b:b700:6c6f:1c9:f659:526:49349] malformed header from script 'filemanager.pl': Bad header: <pre>Couldn't carry on at file, referer: https://www.skeptic.org.uk/dada_mail_support_files/core5_filemanager/index.html?custom_function=SetAttachmentUrl

**Comment by philmck** [comment]
No, it was missing this line:

$q->param('_csrf_token', $q->cookie('_csrf_token'));

Adding it seems to fix the problem, thanks.

**Comment by justingit** [comment]
Hmm OK - I checked the actual distro for what I ship as Dada Mail, and the correct Core5Filemanager is there, with that bug in https://github.com/justingit/dada-mail/issues/1080 fixed. Is there a different way you're packaging up Dada Mail? You said you were using v11.7.1, but... not the 11.17.1 distro I release?

**Comment by justingit** [comment]
I'm closing this bug, but the problem was found in this issue, #1108, which will be used now to track this... issue.
