### ISSUE TITLE
DADA messages sent with any type of formatting are bouncing from gmail addresses with "message has lines too long for transport"

### ISSUE THREAD

**Issue by RayGX** [justingit/dada-mail#1101]
DADA messages sent with any type of formatting are bouncing from gmail addresses with:

2022-06-20 10:50:23 1o3KbX-003jsq-D2 ** myemail@gmail.com  (dada@mydomain.org ) <dada@mydomain.org> F=<bounces@mydomain.org> R=deliver_through_cm_smtp T=remote_smtp: message has lines too long for transport

2022-06-20 10:50:23 cwd=/var/spool/exim 7 args: /usr/sbin/exim -t -oem -oi -f <> -E1o3KbX-003jsq-D2

2022-06-20 10:50:23 1o3KbX-003jtF-Oc <= <> R=1o3KbX-003jsq-D2 U=mailnull P=local S=2892 T="Mail delivery failed: returning message to sender" from <> for bounces@mydomain.org

Issue occurs if Full Layout or Minimal Layout are selected when message is created (message formatting doesn't change once a draft is created using a specific format...a new message must be created to change the format).  I didn't try any others besides the "Don't use a Layout" setting which is the only one which I was able to send/forward to gmail without a "message has lines too long for transport" bounce.

The "too long" message occurred even with a short 3-word test message such as "test1ng for delivery".

See attachment for source code of short test message which still results in "too long..." bounces.
[DADA_source_too_long_bounce.txt](https://github.com/justingit/dada-mail/files/8943706/DADA_source_too_long_bounce.txt)

**Comment by RayGX** [comment]
Forgot to include that the installation of DADA is 11.4.2

**Comment by justingit** [comment]
Change the Content Transfer Encoding to, quoted-printable.

**Comment by RayGX** [comment]
OK...couldn't find this setting in either the Config.pm or .dada_config files so attempted to add it as a new variable in the .dada_config.

Tried both:
@CONTENT_TRANSFER_ENCODINGS = 'quoted-printable'; (as shown in the manual)
   and
$CONTENT_TRANSFER_ENCODINGS = 'quoted-printable'; (as all other variables in .dada_config seemed to be notated this way)
and the issue persists with either setting.  DADA was closed out and restarted for each attempt.
Any additional guidance would be appreciated.

**Comment by justingit** [comment]
Try saving the settings again - those global config vars you change only set up the defaults, not what's saved per-list.
