### ISSUE TITLE
Core 5 File Manager Perl connector/upload script fails to work correctly if you set additional Perl libaries

### ISSUE THREAD

**Issue by philmck** [justingit/dada-mail#1108]
I'm getting errors (again) when trying to upload an attachment. I'm currently running Dada Pro version 11.18.0 2022-03-03 on Ubuntu 18.04, PHP 7.4-fpm, perl v5.26.1

What I'm doing:

- Create a new draft in Mass Mailing > New Draft Message
- Attempt to add an attachment (250k Word doc) in Attachments > Select a File > Upload

What I see:

- A spinning cursor, followed by a popup saying "Error Saving draft:  Internal Error, has your session expired?"

I've tried all the usual things to resolve session problems, including logging out and in again, clearing browser cache, using an "incognito" window, using a different computer. None of these make any difference.

I see these errors in the Error Log:

[Fri Jul  8 17:17:47 2022] filemanager.pl: sysread() is deprecated on :utf8 handles. This will be a fatal error in Perl 5.30 at /home/skeptic/cgi-bin/paranormal/DADA/perllib/File/Slurp.pm line 225.
[Fri Jul  8 17:17:47 2022] filemanager.pl: CGI::param called in list context from filemanager.pl line 285, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /home/skeptic/cgi-bin/paranormal/DADA/perllib/CGI.pm line 414.
[Fri Jul  8 17:18:22 2022] filemanager.pl: invalid csrf for flavor,  at /home/skeptic/cgi-bin/paranormal/DADA/App/Session.pm line 807.
[Fri Jul  8 17:18:22 2022] filemanager.pl: Couldn't carry on at filemanager.pl line 372.
[Fri Jul  8 17:18:22 2022] filemanager.pl: Couldn't carry on at filemanager.pl line 372.
[Fri Jul  8 17:18:23 2022] filemanager.pl: Couldn't carry on at filemanager.pl line 372.
[Fri Jul  8 17:18:55 2022] filemanager.pl: Couldn't carry on at filemanager.pl line 372.
    (in cleanup) Can't access 'DESTROY' field in object of class Google::reCAPTCHA::v3 at /home/skeptic/cgi-bin/paranormal/DADA/App/Guts.pm line 3443.

Could you help me track this down and resolve it, please?

**Comment by justingit** [comment]
Can you make sure your copy of core5_filemanager/connectors/pl/filemanager.pl looks like what I've attached? 

[filemanager.pl.txt](https://github.com/justingit/dada-mail/files/9073803/filemanager.pl.txt)

**Comment by philmck** [comment]
No, there are quite a few differences.

Mine is attached.

Why are they different?
[filemanager.pl (2).txt](https://github.com/justingit/dada-mail/files/9074062/filemanager.pl.2.txt)

**Comment by justingit** [comment]
I'm not sure why they are different. What I attached is what Dada Mail is shipped with.

**Comment by philmck** [comment]
Simply replacing the file hasn't helped. I guess I need a clean install. Can I do that without losing all settings and history?

**Comment by justingit** [comment]
yeah, that's how the app is designed. Just follow the upgrade instructions, 

https://dadamailproject.com/d/upgrade_dada_mail.pod.html

**Comment by philmck** [comment]
I ran the upgrade again and the problem is still there.

The filemanager.pl installed looks like the one I had originally, not the one you attached above. In particular, it lacks the "Additional Perl libraries" and line 44 from yours:
$q->param('_csrf_token', $q->cookie('_csrf_token'));

**Comment by philmck** [comment]
Just to be clear about what I did - I downloaded pro_dada-11_18_0.tar.gz from https://dadamailproject.com/pro_dada/index.cgi?rm=download&CGISESSID=af3bb9a9aec4e1bf5c298d3a47c031c1, untarred/gzipped it, renamed installer-disabled and ran the installer selecting "upgrade" mode.

**Comment by justingit** [comment]
I just did this as well, and the correct copy of filemanager.pl is in the distro - identical to the file I previously posted. 

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/39739/178051370-044fe27c-63c4-4144-9c6b-908a151697f8.png">

**Comment by philmck** [comment]
I confirm that the file in that location (on my machine it's /home/skeptic/cgi-bin/paranormal/extras/packages/core5_filemanager/connectors/pl/filemanager.pl) looks the same as yours. But the file that is copied to the location where I think it's actually executed (in my case /home/skeptic/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/filemanager.pl) is different. Where's that coming from?

**Comment by justingit** [comment]
From location #1. I'm geussing that during an install/upgrade, the copy of the core5_filemanager directory isn't backed up/moved, and a new copy is put in its place? (File created/modified dates could be a clue). Either that or some other file system/permissions issue is going on. But I think the correct core5_filemanager distro is indeed packaged with Dada Mail.

**Comment by philmck** [comment]
The backup is created with the old filestamps and a new folder is created with new timestamps. File permissions look correct. But the contents of the new files are the same as the old files.

How best to work around this? Manually copying the new filemanager.pl didn't seem to help.

**Comment by justingit** [comment]
Not knowing where the source of the file that IS getting copied seems like the crux of everything. Obviously, I can't tell whatever exactly is going on, but this may be a unique issue on this one account, and not an issue with the app - would you agree?

**Comment by philmck** [comment]
I agree this problem has been seen before. I think it's an issue with the installer. 

I tried renaming the old "public_html/dada_mail_support_files" folder in case the file was somehow copied from there, but it hasn't helped.

The installer must be modifying the file I think, because the "Additional Perl Libraries" are added, which is correct behaviour (I think). 

I searched for other "rogue" copies of filemanager.pl but didn't find any:
![filemanager files](https://user-images.githubusercontent.com/293914/178060782-ce21057d-0f35-4351-8a11-1cb8f362c39d.jpg)

**Comment by philmck** [comment]
Manually adding that one line has worked. But replacing the whole file doesn't.

**Comment by justingit** [comment]
Awww, crud, you figured it out - egg on my face. 

So here's what's happening: to DO that custom perl library paths, Dada Mail DOES have an additional copy of that file, here: 

https://github.com/justingit/dada-mail/blob/master/dada/installer-disabled/templates/core5_filemanager-filemanager_pl.tmpl

Which will NOT work with the current version of Dada Mail. This is ONLY used if you have those additional Perl libraries set, which is why you're seeing this problem (and going crazy) and I don't (also going crazy, but def. not as much). 

BUG: recreated. 

My apologies on this one - it wasn't solved correctly back in January.
