### ISSUE TITLE
Perl CPAN Module DateTime.pm unable to located in schedule report

### ISSUE THREAD

**Issue by dickmo** [justingit/dada-mail#1136]
I ran the schedule manually and found this error warning within the display, Using 11.20.0
https://domain-name.org/dada/mail.cgi/_schedules/_all/_all/

Removing old archive messages:
------------------------------------------------------------------------
* Error: Can't locate DateTime.pm in @INC (@INC contains: ../../. ../../DADA/perllib ../../../ ../../../DADA/...

Removing old tracker data:
------------------------------------------------------------------------
* Error: Can't locate DateTime.pm in @INC (@INC contains: ../../ ../../perllib ./ ./DADA/perllib ../../. ../....

**Comment by dickmo** [comment]
can it be added into your dada library

**Comment by justingit** [comment]
No, I will not be adding it to the included perl library that's distributed with Dada Mail (too many prereqs)
