### ISSUE TITLE
v11.20.0 stable 2022-10-03 gets Internal Error

### ISSUE THREAD

**Issue by jzeevi** [justingit/dada-mail#1142]
I just recently upgraded to 11.20.0 stable. I ocassionally been seeing the following:

Internal Problem
The attached message was sent to your mailing list to be sent out to as a mass mailing. but an internal error in the app itself stopped the message from being sent out. Additional tries will not be attempted. 
At your discretion, you may look over the message, and manually send out the contents through the list control panel. 
Errors are below:
parse_data: unable to open in-memory file handle at /home/breakawaypark/public_html/40XSMail/dada/plugins/bridge line 2552. 

Help? Is there something I need to do on my end?

**Comment by justingit** [comment]
It's this issue: 

https://github.com/justingit/dada-mail/issues/1135

I'll close this as a dupe. Fix is being worked on at, 

https://github.com/justingit/dada-mail/tree/bugfixes-11_20_1

You could try just copying over bridge from this branch, 

https://github.com/justingit/dada-mail/blob/bugfixes-11_20_1/app/dada/plugins/bridge

But I would wait for the official stable release in < week. 

Appreciate the report.
