### ISSUE TITLE
Mailing List mail.cgi not displaying format properly in Chrome

### ISSUE THREAD

**Issue by edcoates** [justingit/dada-mail#1160]
I'm currently running version v11.20.1 stable 2023-01-18 of dada-mail.  I run a mailing list for a Boy Scout Troop and I'm havine an issue with the way that mail.cgi is displaying from their website.  The main pages is split into TOP and BOTTOM frames and the BOTTOM frame is split into LEFT and RIGHT frames.  There's a Mailing List link in the LEFT frame that's referenced with with an HREF link.

`<TD><A TARGET="RIGHT" HREF="[/dada/mail.cgi](https://troop363.net/dada/mail.cgi)">Mailing List</A></TD>`

and it used to display properly formatted in the RIGHT frame, but now, there's no formatting.  Also, if I click on the Administration link at the bottoem of the RIGHT frame, it doesn't do anything where it used to display the Administration login page in the RIGHT frame.  If I right-click on the Administration link and display it in another tab, the Administation login page displays just fine.  If I point the browser directly at http://www.troop363.net/dada/mail.cgi, it displays just fine.  It seems to only have issues in Chrome when using the frames.  It also displays just fine when using Firefox.

Thanks for looking,

Ed Coates

**Comment by justingit** [comment]
It may be just how you're visiting the page. For example, if you go to the https url of your site, 

https://troop363.net/dada/mail.cgi

Then go to, "Mailing List", the formatting for Dada Mail is broken. 

But if you start with the http url of your site, 

http://troop363.net/dada/mail.cgi

Then go to, "Mailing List"

It'll work fine. 

So, you want to figure out which one to use: http or https for serving your website and for links in the pages of the website itself. I would suggest https myself, but you would have to reconfigure Dada Mail to work under https. This will help you with that: 

https://blog.dadamailproject.com/2017/06/23/configuring-your-dada-mail-install-to-work-over-https/
