### ISSUE TITLE
Message line length exceeded for Grab content from a URL

### ISSUE THREAD

**Issue by rabell** [justingit/dada-mail#1169]
I am using v11.21.0
When I send a mailing using Grab content from a URL, I get a lot of rejects:
    550 Maximum message linelength exceeded 28942/8000
The problem is caused by HTMLminifier.pm removing newlines in minify.

RFS 5322 says:
2.1.1.  Line Length Limits

   There are two limits that this specification places on the number of
   characters in a line.  Each line of characters MUST be no more than
   998 characters, and SHOULD be no more than 78 characters, excluding
   the CRLF.

I easily fixed the problem by setting:
    remove_newlines => 0,

**Comment by justingit** [comment]
In Sending -> Advanced Options

Is the Default PlainTexst Message Encoding  and Default HTML Message Encoding set to, "quoted-printable"?

**Comment by rabell** [comment]
YesRegards,RobertOn 25 Aug 2023, at 16:37, Justin J ***@***.***> wrote:﻿
In Sending -> Advanced Options
Is the Default PlainTexst Message Encoding  and Default HTML Message Encoding set to, "quoted-printable"?

**Comment by justingit** [comment]
Quoted-Printable would have the max lines for an email message set to 75, and this would not be a problem.

**Comment by rabell** [comment]
I used the URL https://www.polepositiontravel.com/newsletter/148 and the email sent is as attached.

You will see that HTML content at line 120 is a single line.

[Indonesian MotoGP & fly-away events - Unique Offer to our Australasian customers -- Special newsletter form Pole Position Travel - 'Pole Position Travel Australasia' (aus@polepositiontravel.com) - 2023-08-09 1031.zip](https://github.com/justingit/dada-mail/files/12441806/Indonesian.MotoGP.fly-away.events.-.Unique.Offer.to.our.Australasian.customers.--.Special.newsletter.form.Pole.Position.Travel.-.Pole.Position.Travel.Australasia.aus%40polepositiontravel.com.-.2023-08-09.1031.zip)

**Comment by justingit** [comment]
Hmm, testing this myself - it seems to work perfectly - do make sure the settings are the defaults as shown: 

<img width="974" alt="image" src="https://github.com/justingit/dada-mail/assets/39739/631ffef1-c04c-4fa9-9851-ecf8227706ef">

[Indonesian MotoGP & fly-away events - Unique Offer to our Australasian customers -- Special newsletter form Pole Position Travel - 'Pole Position Travel Australasia' (aus@polepositiontravel.com) - 2023-08-09 1031 copy.txt](https://github.com/justingit/dada-mail/files/12444318/Indonesian.MotoGP.fly-away.events.-.Unique.Offer.to.our.Australasian.customers.--.Special.newsletter.form.Pole.Position.Travel.-.Pole.Position.Travel.Australasia.aus%40polepositiontravel.com.-.2023-08-09.1031.copy.txt)

**Comment by rabell** [comment]
I retested myself, and can confirm there is no problem.Apologies - I looked at settings in wrong mailing list.The settings were wrong in the mailing list used. I have corrected and advised the individual concerned.Regards,RobertOn 26 Aug 2023, at 02:16, Justin J ***@***.***> wrote:﻿
Hmm, testing this myself - it seems to work perfectly - do make sure the settings are the defaults as shown:

Indonesian MotoGP & fly-away events - Unique Offer to our Australasian customers -- Special newsletter form Pole Position Travel - 'Pole Position Travel Australasia' ***@***.***) - 2023-08-09 1031 copy.txt

**Comment by justingit** [comment]
Good to hear. I appreciate you filling out an issue regardless, cheers. Closing,
