### ISSUE TITLE
Japanese characters in message title

### ISSUE THREAD

**Issue by babalou** [justingit/dada-mail#470]
Hello Justin,

My company uses DM to send newsletters in Japanese. So, messages titles contains Japanese characters (both in normal and wide size).
-> When I send (to me) a test message, the title (in Japanese) displays correctly.
-> When I send the message with mass mailing option, the title (in Japanese) is broken. The memberships receive an email with wrong characters in the title.

If I look the error logs, I found the following lines :
mail.cgi: Problems: with: (アンスティチュ・フランセ関西 ニュースレター): Cannot decode string with wide characters at /usr/lib64/perl5/Encode.pm line 174.
mail.cgi: Problems: with: (フランス留学大学応募申請説明会（12月12・13日）): Cannot decode string with wide characters at /usr/lib64/perl5/Encode.pm line 174.

Best.

**Comment by justingit** [comment]
What version of Dada Mail are you running?

**Comment by babalou** [comment]
I'm using the version 7.3.1 Pro.

**Comment by justingit** [comment]
The latest is v7.4.0 - if you could double-check that you're not still having problems with the newest version, I'd appreciate it. If you are, I'll be happy to check this out. 

In,  Mail Sending » Advanced Options, what have you set the Message Encoding settings to? I would suggest UTF-8 for both Plaintext, and HTML. Is, " Encode Message Headers " also checked?

**Comment by babalou** [comment]
Thanks !
I think I will update to 7.4.0 in a few days and inform you I still have this problem.
By the way, in Mail Sending » Advanced Options, the options are :
- Default Character Set : UTF8 UTF8
- Default Plain Text Message Encoding : quoted-printable
- Default HTML Message Encoding : quoted-printable
- Encode Message Headers is checked
Are this option correct ?

**Comment by justingit** [comment]
> By the way, in Mail Sending » Advanced Options, the options are :

Yes, everything looks good. Sometimes, people set the encoding to a Japanese-specific encoding, and run into problems. Since the message is reencoded into UTF-8 internally, encoding it back into a Japanese-encoded format sometimes causes problems.
