### ISSUE TITLE
Too many files in /.dada_files/.tmp

### ISSUE THREAD

**Issue by babalou** [justingit/dada-mail#471]
Hi Justin,

I recently noticed the /.dada_files/.tmp directory is containing about 10.000 files. The names of those files begins with "msg-" (ex.: "msg-10476-1.txt", "msg-10476-10.html", etc.). By the way, the html files have a size of 0.

Can I delete those files ?

Best.

**Comment by justingit** [comment]
Yes.

**Comment by babalou** [comment]
Thanks Justin.

I deleted all the files msg-*, but new files msg-* appear a few hours after. 

I'm using DM 7.3.1 PRO and I didn't noticed thos files with previous version. Is ther someting wrong with my DM settings ?

**Comment by justingit** [comment]
Here's where to receive general support (rather than post about a bug) 

http://dadamailproject.com/support/boards/

I can't tell what your settings are, or if there's any errors - you'll have to report those on the boards
