### ISSUE TITLE
New Draft from Stationary

### ISSUE THREAD

**Issue by garethstorer** [justingit/dada-mail#473]
Hi

Every time I try to create a new draft from stationary it does not bring up the template I have selected but rather the last Stationary template created.
I did a test and this does not happen if a stationary item has been modified. it seems to look at crreation date of the stationary item.

Also related to this but not a big issue, but in the interest if ensuring everything is correct I thought I'd the spelling... stationary vs stationery. If your intention was that the reusable "tamplate" is stationary in that it does not move, then stationary is correct. If your intention is that it is related to writing tools then stationery is the correct spelling.

Not sure which is intended from your side. :-)
thanks

**Comment by garethstorer** [comment]
I'm running Dada Pro 7.4.0 Stable

**Comment by justingit** [comment]
I'll check out the problem. 

> If your intention is that it is related to writing tools then stationery is the correct spelling.

Wow, you're totally correct on that! ;)
