### ISSUE TITLE
Sending an invitation in version 7.4.1

### ISSUE THREAD

**Issue by foxation** [justingit/dada-mail#474]
I had been using Dada Mail 7.3.x and tried, for the first time, to send an invitation.

My testing didn't work the way it should so I went to your web site and saw that version 7.4.1 had some bug fixes.

After installing version 7.4.1 I did a test that resulted in two similar emails being received.  They were identical except for the links.  Now I will admit that the email address I was using for testing had previously been subscribed and deleted so that may have some bearing on this, but that could happen in real life, too.  In any event, here are the links from the two latest such emails:
- If you'd like to subscribe, just click the link below: 
  http://www.example.com/cgi-bin/dada/mail.cgi/t/RxO8UAA65vhGi6MScwNy8WAoPDupeEpPuR37HDCf/ 
- If you'd like to subscribe, just click the link below: 
  http://www.example.com/cgi-bin/dada/mail.cgi/t/bMYoKBAS9hVv9rnv3wT7pe5Mzqi9YagUaDjMuggD/ 

One link (I forget which) takes the new subscriber to a page confirming the subscription and the other takes the new subscriber to a page saying there has been a problem of some sort (sorry about the vagueness) and provides a link to the new subscriber's profile.  If you can replicate this you'll see what I mean.

I hope this helps.

Gerald Fox

**Comment by justingit** [comment]
My guess is that you received a copy of the list invitation to the list owner, as they receive copies of all the mass mailings going out. The link that didn't work is being delivered to the list owner. Yeah?
