### ISSUE TITLE
No welcome message

### ISSUE THREAD

**Issue by garethstorer** [justingit/dada-mail#475]
It appears that no welcome message is sent to someone added from the control panel even though that option is selected in the list options.

Was logged with root credentials
Running version 7.4.1

**Comment by justingit** [comment]
By default, no welcome message is sent. First, have you enabled that feature and if so are there any errors in the error log that correspond to this problem?

**Comment by garethstorer** [comment]
The feature is enabled.

Here is an image of the message that comes up after you click "verify addresses" showing that it should work:

![screen shot 2015-03-05 at 10 38 46 am](https://cloud.githubusercontent.com/assets/11058157/6501659/f7b05576-c323-11e4-98e2-415c78cbfc8c.png)

Log entries for a test I did now:

[Thu Mar  5 10:38:59 2015] mail.cgi: You MUST pass a list in the, '-list' parameter! at /DADA/App/MassSend.pm line 1979
[Thu Mar  5 10:38:59 2015] mail.cgi:     DADA::App::MassSend::just_subscribed_mass_mailing('HASH(0x9d68c3c)') called at /home/cfanotyl/public_html/cgi-bin/dada/DADA/MailingList/Subscribers.pm line 221
[Thu Mar  5 10:38:59 2015] mail.cgi:     eval {...} called at /home/cfanotyl/public_html/cgi-bin/dada/DADA/MailingList/Subscribers.pm line 215
[Thu Mar  5 10:38:59 2015] mail.cgi:     DADA::MailingList::Subscribers::add_subscribers('DADA::MailingList::Subscribers=HASH(0x9c5b268)', 'HASH(0x9d53f70)') called at mail.cgi line 5901
[Thu Mar  5 10:38:59 2015] mail.cgi:     mail::add_email() called at mail.cgi line 724
[Thu Mar  5 10:38:59 2015] mail.cgi:     mail::run('mail') called at mail.cgi line 567
[Thu Mar  5 10:38:59 2015] mail.cgi:  at /home/cfanotyl/public_html/cgi-bin/dada/DADA/MailingList/Subscribers.pm line 229
[Thu Mar  5 10:38:59 2015] mail.cgi:     DADA::MailingList::Subscribers::add_subscribers('DADA::MailingList::Subscribers=HASH(0x9c5b268)', 'HASH(0x9d53f70)') called at mail.cgi line 5901
[Thu Mar  5 10:38:59 2015] mail.cgi:     mail::add_email() called at mail.cgi line 724
[Thu Mar  5 10:38:59 2015] mail.cgi:     mail::run('mail') called at mail.cgi line 567
[Thu Mar  5 10:38:59 2015] mail.cgi: You MUST pass a list in the, '-list' parameter! at /DADA/App/MassSend.pm line 2096
[Thu Mar  5 10:38:59 2015] mail.cgi:     DADA::App::MassSend::send_last_archived_msg_mass_mailing('HASH(0xa19c1c0)') called at /home/cfanotyl/public_html/cgi-bin/dada/DADA/MailingList/Subscribers.pm line 235
[Thu Mar  5 10:38:59 2015] mail.cgi:     eval {...} called at /home/cfanotyl/public_html/cgi-bin/dada/DADA/MailingList/Subscribers.pm line 233
[Thu Mar  5 10:38:59 2015] mail.cgi:     DADA::MailingList::Subscribers::add_subscribers('DADA::MailingList::Subscribers=HASH(0x9c5b268)', 'HASH(0x9d53f70)') called at mail.cgi line 5901
[Thu Mar  5 10:38:59 2015] mail.cgi:     mail::add_email() called at mail.cgi line 724
[Thu Mar  5 10:38:59 2015] mail.cgi:     mail::run('mail') called at mail.cgi line 567
[Thu Mar  5 10:38:59 2015] mail.cgi:  at /home/cfanotyl/public_html/cgi-bin/dada/DADA/MailingList/Subscribers.pm line 243
[Thu Mar  5 10:38:59 2015] mail.cgi:     DADA::MailingList::Subscribers::add_subscribers('DADA::MailingList::Subscribers=HASH(0x9c5b268)', 'HASH(0x9d53f70)') called at mail.cgi line 5901
[Thu Mar  5 10:38:59 2015] mail.cgi:     mail::add_email() called at mail.cgi line 724
[Thu Mar  5 10:38:59 2015] mail.cgi:     mail::run('mail') called at mail.cgi line 567

**Comment by justingit** [comment]
OK, 

Thank you very much. There ARE some pretty major issues with this feature. I appreciate you taking the time to report this.

**Comment by justingit** [comment]
The option to send the last archived message out to people subscribed via the control panel also doesn't seem to be working. I'm tacking that issue along with this issue, as the problems seems to be pretty similar.
