### ISSUE TITLE
option to not archive message ignored

### ISSUE THREAD

**Issue by garethstorer** [justingit/dada-mail#476]
When creating a new message, when I unselect the option to archive the message on sending the message still gets archived.

![screen shot 2015-03-05 at 10 43 26 am](https://cloud.githubusercontent.com/assets/11058157/6501736/bfad7d42-c324-11e4-95de-1a0f7c29669d.png)

Only error log entry after sending:

[Thu Mar  5 10:44:02 2015] mail.cgi: $self->{md_obj}->enabled  1 at /DADA/App/MassSend.pm line 348.

**Comment by justingit** [comment]
What version of Dada Mail is this?

**Comment by garethstorer** [comment]
Sorry for the delay in answering. Github notification email seems to be going to SPAM. Sorting that out on my side.
I am using 7.4.1 Pro

**Comment by justingit** [comment]
Thanks, I'll look into it for you,

**Comment by justingit** [comment]
OK, confirmed. (sigh)
