### ISSUE TITLE
Return address of mailings changed with version 7.4.1

### ISSUE THREAD

**Issue by dajonline** [justingit/dada-mail#477]
I just updated to Dada Mail Pro version 7.4.1. 
In the past the return address to mailings was always, mailing list name, then email address:

CSAMA Newsletter no-reply@csamanewsletter.org

Upon updating to Dada Mail Pro version 7.4.1. the return address changed:
Example:

bouncehandler-no+2Dreply=csamanewsletter.org@csamanewsletter.org; on behalf of; CSAMA Newsletter no-reply@csamanewsletter.org

To my knowledge I did not do anything different when I installed this version than I have in the past. I always do a fresh install.

The above example was doing a test email.  In the example above the recipient email was no-reply@csamanewsletter.org.  With other precipitants the recipient's email is inserted in the reply address. 

How do I get the return address to go back to just :CSAMA Newsletter no-reply@csamanewsletter.org.

Thanks,
Daniel Jacobson

**Comment by justingit** [comment]
Which header are you looking at?  Can you post the source of a message you're seeing this issue?

**Comment by justingit** [comment]
And what did you upgrade from?

**Comment by dajonline** [comment]
I upgraded from Version ver 7.4.0
I am looking at the header that comes in on my Outlook email. I am not looking at the expanded header. I will try to post them here:

I don't think I can copy and paste what I see there as a picture but here is the full headers. 

The examples are the test emails so you would see the same to address (which in this case was no-reply@csamanewsletter.org.) But the same thing happens regardless of who it is addressed to. Their address is inserted into the from address. 

Old header:
---
Received: from WINHEXBEUS7.winus.mail (10.71.41.34) by WINHEXBEUS7.winus.mail
 (10.71.41.34) with Microsoft SMTP Server (TLS) id 15.0.995.29 via Mailbox
 Transport; Sat, 14 Feb 2015 17:57:56 -0500
Received: from WINHEXFEUS3.winus.mail (10.72.31.12) by winhexbeus7.winus.mail
 (10.71.41.34) with Microsoft SMTP Server (TLS) id 15.0.995.29; Sat, 14 Feb
 2015 17:57:53 -0500
Received: from mout.perfora.net (74.208.4.196) by WINHEXFEUS3.winus.mail
 (74.208.196.66) with Microsoft SMTP Server (TLS) id 15.0.995.29 via Frontend
 Transport; Sat, 14 Feb 2015 17:57:53 -0500
Received: from winxedgeus02.exchange.xchg (winxedgeus02.lxa.perfora.net [172.23.130.34])
	by mrelay.perfora.net (node=mreueus001) with ESMTP (Nemesis)
	id 0LnAfj-1XfSDk39dV-00hKFz; Sat, 14 Feb 2015 23:57:53 +0100
Received: from winxhubus04.exchange.xchg (172.23.130.36) by
 winxedgeus02.exchange.xchg (172.23.130.34) with Microsoft SMTP Server (TLS)
 id 8.3.279.5; Sat, 14 Feb 2015 17:45:09 -0500
Received: from winxedgeus02.exchange.xchg (172.23.130.34) by
 winxhubus04.exchange.xchg (172.23.130.36) with Microsoft SMTP Server id
 8.3.279.5; Sat, 14 Feb 2015 17:45:02 -0500
Received: from moeueus001.server.lan (172.19.150.50) by
 winxedgeus02.exchange.xchg (172.23.130.34) with Microsoft SMTP Server id
 8.3.279.5; Sat, 14 Feb 2015 17:45:07 -0500
Received: from [74.208.5.21] ([74.208.5.21]) by mx.perfora.net (mxeueus002)
 with ESMTPS (Nemesis) id 0Md5VM-1Y4Xoi0ldK-00IE8p for
 <e124374133@exchange.1and1.com>; Sat, 14 Feb 2015 23:45:02 +0100
Received: from [74.208.5.21] ([74.208.5.21]) by mx.perfora.net (mxeueus002)
 with ESMTPS (Nemesis) id 0LyTIW-1XYYVk0lc6-015uud for
 <daj.exchange@dajonline.com>; Sat, 14 Feb 2015 23:45:02 +0100
Received: from mout.perfora.net ([74.208.4.197]) by mx.perfora.net
 (mxeueus002) with ESMTPS (Nemesis) id 0Let0z-1XnjsX0jCZ-00qiLG for
 <zzzzzzzcontrol@csamanewsletter.org>; Sat, 14 Feb 2015 23:45:02 +0100
Received: from csamanewsletter.org (infong1333.lxa.perfora.net
 [74.208.241.186])	by mrelay.perfora.net (node=mreueus002) with ESMTP
 (Nemesis)	id 0MBToO-1YTwS22rl0-00AUoU; Sat, 14 Feb 2015 23:45:01 +0100
Date: Sat, 14 Feb 2015 17:45:00 -0500
From: CSAMA Newsletter <no-reply@csamanewsletter.org>
To: CSAMA Newsletter Subscriber <zzzzzzzcontrol@csamanewsletter.org>
X-Priority: 3
Precedence: list
List: csamanewsletter
List-ID: <csamanewsletter.icpu3231.schlund.de>
List-Owner: <no-reply@csamanewsletter.org>
List-Post: NO
List-Subscribe: <http://nl.csamanewsletter.org/cgi-bin/dada/mail.cgi/s/csamanewsletter/zzzzzzzcontrol/csamanewsletter.org/>
List-Unsubscribe: <mailto:no-reply@csamanewsletter.org?Subject=Unsubscribe%20from%20CSAMA%20Newsletter>,
 <http://nl.csamanewsletter.org/cgi-bin/dada/mail.cgi/t/Vbm7oTsoe3ezeKtu75EICfAMq4Bpen9DXiFpejXI/>
List-URL: <http://nl.csamanewsletter.org/cgi-bin/dada/mail.cgi/list/csamanewsletter/>
Message-ID: <20150214173928.95228460@csamanewsletter.org>
X-Mailer: CSAMA Mailing List 7.4.0 Stable 12/16/14 
Content-Type: multipart/alternative;
	boundary="----------=_1423953568-25673-0"; charset="UTF-8"
MIME-Version: 1.0
Subject: CSAMA Newsletter Volume 32 (2) February 2015
X-Provags-ID: V02:K0:y/cY85NGsXlQ9rl1VsnbHjBhTIghzPCH8C2DEP2rarW
 SZb15FwRq04f6ILbVX1qJ6mKQ65dBn6W+Jjo0vnuX7zJcqR7yY
 H4pfdgle25DvHW/96TapuW8BR4AyMO6OXL2slyj8aONB3MQEpl
 4/mUE+dtlRz/8Ta5++0191htlvkLRhyMgzjDZ3obngqKptAYRH
 PgHUt2gtmb/f5n9p3CKi9nNkYCoFYRsVjWTWmsva0SdPoVkFes
 vnCA6R8Qra/8V6SUC3yNLK2vLaCOm5mHBI27x0BH4Kx/2PYAFk
 DbFPi/ZbFPyFBjhIXcZ+lu6jIF1nmfbXgwpbpZnum0mBkbjGXh
 +/OmPbPLf77H6I4XXGTznWWh4tUzp/mWj5VATs78qSQWlQ2GIU
 CJ710/VG9Ogm7HxrYWKKsPLIa91+SsGw7g=
Return-Path: bouncehandler-zzzzzzzcontrol=csamanewsletter.org@csamanewsletter.org
X-1and1-Spam-Score: 0/5
X-1and1-Spam-Level: None
X-UI-Out-Filterresults: notjunk:1;
X-MS-Exchange-Organization-Network-Message-Id: b2734fd6-73c8-4559-37d5-08d216c0cce3
X-1and1-Spam-Score: 0/5
X-1and1-Spam-Level: None
X-MS-Exchange-Organization-AVStamp-Mailbox: SYMANTEC;1;0;info
X-MS-Exchange-Organization-AuthSource: WINHEXFEUS3.winus.mail
X-MS-Exchange-Organization-AuthAs: Anonymous

---

New header:

---
Received: from WINHEXBEUS16.winus.mail (10.71.41.148) by
 WINHEXBEUS7.winus.mail (10.71.41.34) with Microsoft SMTP Server (TLS) id
 15.0.995.29 via Mailbox Transport; Sat, 14 Mar 2015 11:44:47 -0400
Received: from WINHEXFEUS4.winus.mail (10.72.31.132) by
 winhexbeus16.winus.mail (10.71.41.148) with Microsoft SMTP Server (TLS) id
 15.0.995.29; Sat, 14 Mar 2015 16:44:45 +0100
Received: from mout.perfora.net (74.208.4.194) by WINHEXFEUS4.winus.mail
 (74.208.196.98) with Microsoft SMTP Server (TLS) id 15.0.995.29 via Frontend
 Transport; Sat, 14 Mar 2015 11:44:45 -0400
Received: from winxedgeus01.exchange.xchg ([172.23.130.53]) by
 mrieueus.server.lan (mrieueus002) with ESMTP (Nemesis) id
 0MCgOy-1YgBtX1bIw-009Q1c for <e124374133@1.exchange.1and1.us>; Sat, 14 Mar
 2015 16:44:45 +0100
Received: from winxhubus03.exchange.xchg (172.23.130.33) by
 winxedgeus01.exchange.xchg (172.23.130.53) with Microsoft SMTP Server (TLS)
 id 8.3.279.5; Sat, 14 Mar 2015 11:44:51 -0400
Received: from winxedgeus01.exchange.xchg (172.23.130.53) by
 winxhubus03.exchange.xchg (172.23.130.33) with Microsoft SMTP Server id
 8.3.279.5; Sat, 14 Mar 2015 11:44:42 -0400
Received: from moeueus002.server.lan (172.19.150.51) by
 winxedgeus01.exchange.xchg (172.23.130.53) with Microsoft SMTP Server id
 8.3.279.5; Sat, 14 Mar 2015 11:44:47 -0400
Received: from [74.208.5.21] ([74.208.5.21]) by mx.perfora.net (mxeueus003)
 with ESMTPS (Nemesis) id 0LZfp4-1ZG5Cv2aPU-00lR3E for
 <e124374133@exchange.1and1.com>; Sat, 14 Mar 2015 16:44:41 +0100
Received: from mout.perfora.net ([74.208.4.197]) by mx.perfora.net
 (mxeueus003) with ESMTPS (Nemesis) id 0MdMkn-1YpA2U2aNn-00IXch for
 <daj.exchange@dajonline.com>; Sat, 14 Mar 2015 16:44:41 +0100
Received: from mout.perfora.net ([74.208.4.196]) by mx.perfora.net
 (mxeueus003) with ESMTPS (Nemesis) id 0LtY9a-1ZVP8W2dUK-010uer for
 <no-reply@csamanewsletter.org>; Sat, 14 Mar 2015 16:44:40 +0100
Received: from csamanewsletter.org ([74.208.241.186]) by mrelay.perfora.net
 (mreueus002) with ESMTPA (Nemesis) id 0MHqf5-1YYBgY3DOX-003cEK for
 <no-reply@csamanewsletter.org>; Sat, 14 Mar 2015 16:44:39 +0100
Date: Sat, 14 Mar 2015 11:44:39 -0400
From: CSAMA Newsletter <no-reply@csamanewsletter.org>
To: CSAMA Newsletter Subscriber <no-reply@csamanewsletter.org>
X-Priority: 3
Precedence: list
List: csamanewsletter
List-ID: <csamanewsletter.icpu3231.schlund.de>
List-Owner: <no-reply@csamanewsletter.org>
List-Post: NO
List-Subscribe: <http://nl.csamanewsletter.org/cgi-bin/dada/mail.cgi/s/csamanewsletter/no-reply/csamanewsletter.org/>
List-Unsubscribe: <mailto:no-reply@csamanewsletter.org?Subject=Unsubscribe%20from%20CSAMA%20Newsletter>,
 <http://nl.csamanewsletter.org/cgi-bin/dada/mail.cgi/t/f2UuPEpN74o2sUUCCcrMSueyvZWyG5wyM6VuujtK/>
List-URL: <http://nl.csamanewsletter.org/cgi-bin/dada/mail.cgi/list/csamanewsletter/>
Message-ID: <20150314114439.74737733@csamanewsletter.org>
X-Mailer: CSAMA Mailing List 7.4.1 Stable 02/20/14 
Content-Type: multipart/alternative;
	boundary="----------=_1426347878-13830-0"; charset="UTF-8"
MIME-Version: 1.0
Subject: CSAMA Newsletter
Sender: <bouncehandler-no+2Dreply=csamanewsletter.org@csamanewsletter.org>
X-Provags-ID: V03:K0:chMNk/U2ENPLRUHI5ubZThOwsjJRVXh3gkKNbdKk2AABhdN0amx
 oZq9Ttl3fepAicBd2sPMESKBNnYZNwIMGGt49ZaGB/jw/hhSI8Jm6J8B9vRSbvOKWiMFXgZ
 7TNDDDE06jfyLlyQXhNy2xjIIVJz3mgu76s5oMwl8SOMS9FR9qF8fDELWAD6Uh7TQCFL3et
 T0AF5g47nMTMtxML3KQ3A==
X-UI-Loop: V01:4T6YIrKZ7vQ=:wVV63KEwh6d5xWg4DxZ+IvoxAGoZAfmXrWv7/NW0aeA=
Return-Path: no-reply@csamanewsletter.org
X-1and1-Spam-Score: 2.4/5
X-1and1-Spam-Level: Medium
X-UI-Out-Filterresults: notjunk:1;
X-MS-Exchange-Organization-Network-Message-Id: 4e2031ee-668c-4e93-097f-08d22c84ee2f
X-1and1-Spam-Score: 0/5
X-1and1-Spam-Level: None
X-MS-Exchange-Organization-AVStamp-Mailbox: SYMANTEC;1;0;info
X-MS-Exchange-Organization-SCL: 6
X-MS-Exchange-Organization-AuthSource: winhexfeus4.winus.mail
X-MS-Exchange-Organization-AuthAs: Anonymous
---
Daniel

**Comment by dajonline** [comment]
I will try here to insert the picture of the header I see:

How it used to show:

![old](https://cloud.githubusercontent.com/assets/3821024/6652551/a295d6aa-ca40-11e4-9b65-87bb0de7e263.JPG)

How it shows now.

![new](https://cloud.githubusercontent.com/assets/3821024/6652552/a816060e-ca40-11e4-900f-21d3208f7b6f.JPG)

I can't see if it shows correct until I post it.

**Comment by dajonline** [comment]
Those where with two different recipients. Here it is with the same recipients.
![old](https://cloud.githubusercontent.com/assets/3821024/6652565/0c66b3e2-ca41-11e4-9ad4-f51ba34a68ec.JPG)

![new2](https://cloud.githubusercontent.com/assets/3821024/6652566/12e69fb6-ca41-11e4-84f3-0bbe0d05ab10.JPG)

**Comment by justingit** [comment]
Looks like you have VERP enabled - and then, did you also install the bounce handler? VERP can be disabled in Mail Sending >> Advanced Options (uncheck:  Use VERP )

**Comment by dajonline** [comment]
Verb is on but it was on before. I have been using Dada Mail for over 2 years and have updated every time a stable update comes out. I also have been using Bounce handler ever since too. If I turn off VERP will that stop Bounce Handler from working?

**Comment by dajonline** [comment]
I just read your link to http://cr.yp.to/proto/verp.txt.  The weird thing is I didn't change any settings (knowingly at least) when I updated.  I am just afraid that people's spam filters, white lists and such will get confused when the address changes like that. I also have never had any bounces that I am aware of yet. So I don't even know if the bounce thing works. Well when I first set up the list one address I 'invited' did not go through because it was invalid, but I don't know if that was a function of the Bounce Handler or something else.

**Comment by dajonline** [comment]
OK. I just turned VERB off and sent myself a test message and the header didn't change.

**Comment by dajonline** [comment]
Hmmm... The account I used for one of the accounts was unsubscribed and a request but in to reusbscribe. 
zzzzzzzcontrol@csamanewsletter.org
I created that account so I would know that the mailing list had finished. It is an alias to my personal account. That way I would know that all the emails had sent. 
It is just curious because I didn't unsubscribe and resubscribe it myself. Did you? I don't mind if you did to test something but it would be nice to know if it was you.

**Comment by justingit** [comment]
I wouldn't have changed anything on your Dada Mail myself. 

I don't think the changes between v7.4 and v7.4.1 would account for the changes you're seeing. 

Is it instead something that changed in Outlook? What you're seeing looks to be what I'd expect from Outlook. 

VERP will only help the Bounce Handler, if you're MTA is Qmail, it seems. If it's not, then it may actually be a detriment.

**Comment by dajonline** [comment]
If something changed with my Outlook why would only the new emails show the different header and not all of the emails (from the newsletter) have that different header?

As far as I know the only thing I did was to upgrade from Ver 7.4.0 to 7.4.1. I have not changed anything with Outlook.

**Comment by dajonline** [comment]
OK. While I was trying to figure out another issue, I reinstalled ver 7.4.0 and have the same problem as described in this correspondence. So I am thinking that perhaps an update to Outlook happened at the same time.  What ever, it wasn't, I would think, caused by the upgrade. Just thought you would want to know.

**Comment by dajonline** [comment]
I have more than one email account. Only the email that goes through my 1&1 mail server does this happen, so I have put in a trouble ticket with 1&1.

**Comment by dajonline** [comment]
One last comment.  I am getting the problem with other mailing lists I am on, not just ones I send. Of course they might be u sing Dada Mail, but I doubt it.

Here is an example:

![another example](https://cloud.githubusercontent.com/assets/3821024/7139608/cea4a53c-e28c-11e4-8124-4dbd224a436f.JPG)

So I think it was a coincidence that it happened at the same time I upgraded. I think it is my email provider that changed something.
