### ISSUE TITLE
Profile issues with dada 8.0.0

### ISSUE THREAD

**Issue by DavidGwydion** [justingit/dada-mail#479]
Finally bought the perpetual license. Nice program.

The latest release has a few issues that are concerning me. First, I can still register a new profile for an address that already has a profile. That means someone who knows an address that isregistered can change that address's password.

The second is that the reset password works fine, up until the point I submit the new password. Instead of logging me in, it displays the generic server error message. It does change the password and acknowledge the authentication.

Thanks, and let me know if you need any more information.

I would have posted this on the forums, but they don't seem that up to date.

David Gosselin

**Comment by justingit** [comment]
> First, I can still register a new profile for an address that already has a profile.  

Wow, that is kind of strange, I can recreate that quite easily. 

> The second is that the reset password works fine, up until the point I submit the new password. Instead > of logging me in, it displays the generic server error message. It does change the password and 
> acknowledge the authentication.

Again, easy to recreate - I'll look into both these issues. 

> I would have posted this on the forums, but they don't seem that up to date.

This is a fine place to post these problems, but what do you mean that they don't seem that up to date?

**Comment by DavidGwydion** [comment]
Please ignore the comment about the forums. Most of the messages I was looking at were about older versions.
