### ISSUE TITLE
Problems setting .dada_files location in Installer

### ISSUE THREAD

**Issue by dajonline** [justingit/dada-mail#480]
When I tried to install Version 8 to my server. I got an error:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

----

I have had no problem in the past installing earlier versions. I do have the correct perl version, I checked that first before I started.

I also noticed that it did not create the .data_files folder or the data_mail_support_files folders.

For now I will just step pack to the previous version. Any suggestions?

Thanks,

Daniel Jacobson

**Comment by dajonline** [comment]
Now I just get the error:

Can not create, /kunden/homepages/16/d487428368/htdocs/Web_Sites/CSAMA_NEWSLETTER/nl_csamanewsletter_org/.dada_files

But it did create: /kunden/homepages/16/d487428368/htdocs/Web_Sites/CSAMA_NEWSLETTER/nl_csamanewsletter_org/cgi-bin/dada

I am confused.

Daniel

**Comment by dajonline** [comment]
Sorry for the multiple entries.

I can, using Filezilla manually create a directory, where Dada says it can't.

I have a mailing to get out so I will just rename the older version and make it active again.

I am using 1and1 for my web service.

Daniel

**Comment by justingit** [comment]
This does sound less like a bug and more like a permissions problem on your account. 

The directory structure for this host is strange, but I'd check to make sure the "nl_csamanewsletter_org" doesn't have some sort of permissions to disallow new directories to be written to it, by Dada Mail. This probably just means it needs permissions of, "755", but if that doesn't work, change them to "777" for the installation, and then back to the original permissions when you're done.

**Comment by dajonline** [comment]
I set up the directory structure. I didn't know there was suppose to be something special so I did what looked good to me. To late to (easily) change it now. I have multiple web sites on that host. 

I changed the .httaccess files to not restrict anything. But the weird thing is I did not have any problems installing eariler versions of DADA. 

I will try what you suggest then let you know.  It won't be until latter today or tomorrow. I went back to my saved version and sent out my mailing.

Daniel

**Comment by dajonline** [comment]
I changed the container folder to 777. Still got the same error message. As I said, the Dada file installed into the cgi-bin folder, which is a sub folder that the folder that the dada folder is installed in, and the dada file was created just fine.

![capture](https://cloud.githubusercontent.com/assets/3821024/7107933/9bea80d2-e13b-11e4-9d95-69beab770d59.JPG)

Daniel

**Comment by dajonline** [comment]
I am going to do an install of an older version. I set the folders back to what the where 705. I will do that an my next message I will give you the results.

Daniel

**Comment by dajonline** [comment]
I just installed ProDada 7.4.1. Everything installed just fine and it works.  So it isn't a permissions problem with my provider.  My provider is 1&1.

Daniel

**Comment by DavidGwydion** [comment]
I had the same problem installing v8. What I ended up doing was manually creating the .dada_files directory and its subdirectories, adding a .configs/.dada_config and then doing an upgrade instead of an install. I had chmod'd the entire directory path to 777 at some point, chown'd the dirs to www-data:www-data and the install still didn't work.

I had other issues with the update, but I'll start a new thread on that.

**Comment by dajonline** [comment]
Thank you David Gwydion.  It is nice to know it wasn't me.  I will just wait for the next version. Hopefully that bug will be fixed by then.

**Comment by justingit** [comment]
David, who was your host?

**Comment by justingit** [comment]
You can give the multiple_subscribe.cgi script on my own install a shot, 

http://dadamailproject.com/cgi-bin/dada/extensions/multiple_subscribe.cgi

It does seem to work, correctly.

**Comment by DavidGwydion** [comment]
serveraxis.com

**Comment by dajonline** [comment]
Justin,

I notice you took the post off that I am refering to below, but I still had it in my email inbox...

Were you saying to use http://dadamailproject.com/cgi-bin/dada/extensions/multiple_subscribe.cgi
instead of uncompress_dada.cgi?  

I still think I am going to wait for you to fix the problem in your next upgrade.

Daniel

**Comment by justingit** [comment]
> I notice you took the post off that I am refering to below, but I still had it in my email inbox...

Sorry I misposted in the wrong issue, I meant to post in this one #481 - that's all that was.

**Comment by justingit** [comment]
I've happened upon this problem in v8, when setting a custom place for the .dada_files - I may have a fix by tomorrow,

**Comment by justingit** [comment]
Should now be fixed in v8.0.1

**Comment by dajonline** [comment]
Ver 8.0.1 installed just fine. However when I tried to use the fast CGI the program would not work.  So I reinstalled it using GCI and it works.  The install program said that fast GCI would be supported, but I am not going to worry about that. It works now.
