### ISSUE TITLE
Multiple Subscribe extension script: no support for validating profile fields

### ISSUE THREAD

**Issue by DavidGwydion** [justingit/dada-mail#481]
When I use multiple subscribe for a new subscription, I get this:
Subscription Results:
Test1 Mailing List
Looks like there were problems:
Test2 Mailing List
Looks like there were problems:

Mail.cgi works fine.

**Comment by justingit** [comment]
Are any of the settings for these lists different than the default? For example, is the list closed, or private, or something like that?

**Comment by DavidGwydion** [comment]
The both use the Bridge plugin. That is the only difference I can think of.

**Comment by justingit** [comment]
in that extension script, there is a variable called, "$Debug" and it's set to, 0 by default. If you set it to, 1, and try running the script again, does it report anything new that sheds light to the problem?

**Comment by DavidGwydion** [comment]
No additional information was displayed. And the error messages were correct as the requestor was not subscribed.

**Comment by justingit** [comment]
Error messages? What did it say, exactly? Can you provide a screenshot or URL to the script?

**Comment by DavidGwydion** [comment]
Here is the screenshot. It was nothing more than what I originally reported.

![screen shot 2015-04-13 at 17 08 21](https://cloud.githubusercontent.com/assets/11878615/7125557/f94d033e-e1ff-11e4-8fea-77b602de8902.png)

**Comment by justingit** [comment]
David, is there a reason you closed this issue?

**Comment by justingit** [comment]
You can give the multiple_subscribe.cgi script on my own install a shot,

http://dadamailproject.com/cgi-bin/dada/extensions/multiple_subscribe.cgi

It does seem to work, correctly.

**Comment by DavidGwydion** [comment]
I didn't mean to close this. Sorry.

**Comment by DavidGwydion** [comment]
I see that yours works as expected. I'll check my permissions.

**Comment by DavidGwydion** [comment]
Permissions seem fine. Not sure what to do at this point.

**Comment by justingit** [comment]
My only guess is that there is a problem with subscribing, but it isn't something the multiple_subscribe.cgi script is aware of, so it's return the issue an error, without an explanation. That's why I've asked if any of the defaults for the list settings have changed. Perhaps it doesn't know about private/closed lists, or something like that. 

Any errors in the actual error log reported, when running this script?

**Comment by DavidGwydion** [comment]
I found the issue. I have two profile fields and I made them required. This seems to cause multiple_subscribe.cgi to fail. When they are not required, it works. I want them to be required.

**Comment by DavidGwydion** [comment]
Funny thing is that it still seems to pass the values of those variables when I fill them in and it is not required.

**Comment by justingit** [comment]
OK, so that's the issue: the email validation stuff lacks support for profile field validations as well. 

I'm going to change the title of this bug, just to make things clear. Thanks for the report and patience in helping me understand it.

**Comment by justingit** [comment]
Should now be fixed in v8.0.1
