### ISSUE TITLE
Digests messages show List Email, instead of Subscriber Email

### ISSUE THREAD

**Issue by DavidGwydion** [justingit/dada-mail#484]
The digests I receive have the list address as the individual sender's addresses. There appears to be no way for someone to know who sent the message if they want to reply to them directly.

**Comment by justingit** [comment]
> The digests I receive have the list address as the individual sender's addresses. 

So, do you mean in each message within the digest, the first part where it lists: 

Date: 
From: 
Subject: 

"From:" just lists the List Email, rather than then Subscriber's email?

**Comment by DavidGwydion** [comment]
Exactly. It also does it at the top where it lists the messages. I can live with that.
