### ISSUE TITLE
List Invitation not disabled with correct option in Mail Sending >> Mass Mailing Options

### ISSUE THREAD

**Issue by sandy-j** [justingit/dada-mail#486]
Hi Justin,
I've just upgraded to 7.4.1, and now I'm finding that when I try to invite an address. I get to the verify>>send invitation screen OK but then when I click on Send invitation… I get a page with:

This screen has been disabled, when Signing in with the List Password.

To access this screen, log in using the, Pro Dada Root Password

OK so I can work around this by using the root password, but I don't want to give that out to everyone. I've tried all the available options but I can't seem to get past this. Is there some option I've overlooked?
TIA
Sandy_J

**Comment by justingit** [comment]
Try, 

Your List Control Panel >> Customize Feature Set

and check: Mail Sending >> Mass Mailing Options

Which makes NO sense, and is in fact: a bug. When fixed, you would make sure, 

Membership  >> Invite/Subscribe/Add

is checked.
