### ISSUE TITLE
Profile password reset not working

### ISSUE THREAD

**Issue by cheveuxrouges69** [justingit/dada-mail#493]
Dada 8.0.1 
Following the link in emails to "Manage Your Subscription"
https://www.example.org/cgi-bin/dada/mail.cgi/profile_login/email/domain/
Click "Reset Password" tab
Enter email address of subscription
Click "reset your Profile Password"
Next screen
"Profile Reset Password Confirm
Profile Reset Confirmation Email Sent!
Please check your email inbox for, name@domain for the profile password confirmation message.
Follow the authorization link in the message, to reset your profile password!"
No email is received. Error log message is:

CAPTCHA Not working correctly?: Can't locate GD.pm in @INC (@INC contains: <long list of paths>) at /DADA/Security/AuthenCAPTCHA/Default.pm line 7.
BEGIN failed--compilation aborted at /DADA/Security/AuthenCAPTCHA/Default.pm line 7.
Compilation failed in require at (eval 43) line 3.
	...propagated at /usr/share/perl5/base.pm line 94.
BEGIN failed--compilation aborted at /DADA/Security/AuthenCAPTCHA.pm line 13.
Compilation failed in require at /home/xxxxxxx/public_html/cgi-bin/dada//DADA/App/Guts.pm line 3059.
 at /home/xxxxxxx/public_html/cgi-bin/dada//DADA/App/Guts.pm line 3065

Then later:

exim abandoned: unknown, malformed, or incomplete option -f
Dada Mail 8.0.1 Stable 04/20/15 Warning: 
                         didn't close pipe to '|/usr/sbin/sendmail -t -f' while 
                         attempting to send a message to: 'user@domain because:'  at /DADA/Mail/Send.pm line 801.

config.pm:
$PROFILE_OPTIONS //= {

    enabled                         => 1,
    profile_email                   => '',
    enable_captcha                  => 1,

\# Set to Either, "Default" or, "reCAPTCHA";
$CAPTCHA_TYPE //= 'Default';
$GD_SECURITYIMAGE_PARAMS //= {
    'rand_string_from' => 'ABCDEFGHIJKLMNOPQRSTUVWXYZaeiouy',

    limit_sub_confirm             => 1,
    limit_sub_confirm_use_captcha => 1,

Plugins:
 Tracker
 Bridge
 Change the Program Root Password
 Change Your List Short Name
 View Logs
 Screen Cache

Can't find anywhere in GUI to disable captcha and try without it set, apart from editing config.pm 
-> edited config.pm to set 
$PROFILE_OPTIONS //= {
    enabled                         => 1,
    profile_email                   => '',
    enable_captcha                  => 0,

now no email received but also no error message

**Comment by justingit** [comment]
Def. doesn't seem like CAPTCHA is working for you, so that's the fist thing I'd change, but not in the dada/DADA/Config.pm file, but rather in your .dada_config file either directly, or by using the included installer: 

http://dadamailproject.com/d/install_dada_mail.pod.html#Making-Additional-Global-Configuration-Changes-using-the-Dada-Mail-Installer

http://dadamailproject.com/d/install_dada_mail-advanced_configuration.pod.html

You would want to see if that variable, is present and change that one line: 


to disable CAPTCHA for now.
