### ISSUE TITLE
Subscribe/Invite/Update seems to think that there is profile info already saved when there isn't

### ISSUE THREAD

**Issue by cheveuxrouges69** [justingit/dada-mail#494]
Dadamail 8.0.1
Trying to add a new subscriber
"Invite Just One Address:"
Enter completely random info (making sure it looks like a valid email address)
Click "Verify"
Get "Some of the Verified Addresses below may already have profile information saved"

**Comment by justingit** [comment]
This will be shown, no matter what address or addresses you put in - that's true. That's why I use the word, *may* in that dialog.

**Comment by cheveuxrouges69** [comment]
Ah I thought that you actually checked - my bad
