### ISSUE TITLE
Rejected Emails not being attached

### ISSUE THREAD

**Issue by cheveuxrouges69** [justingit/dada-mail#496]
When a non-subscriber or non-approved sender sends an email to the list via bridge, the list admin receives an email along these lines:
[officers]  Error - spam@spammer.com Not Allowed to Post On ThisListName (original message attached)
With the text: 
The attached message was not sent to your Mailing List, 
  ThisListName 
but was not sent from an address that has permission to do so. 
There are two issues:
1) There is nothing attached to the email!
2) (minor) The text of the email is meaningless, perhaps "because it was not sent"...  would be better, rather than "but was not sent..."

**Comment by justingit** [comment]
The original message won't be attached anymore, as it seems to be a source of backscatter spam. The email template should be updated as of v8.0.2

>  2) (minor) The text of the email is meaningless, perhaps "because it was not sent"... would be better, 
> rather than "but was not sent..."

Far enough, I can make that change,

**Comment by cheveuxrouges69** [comment]
If you're not going to include the message (perhaps an option? I /would/ like to see what it is) then:
- Email subject needs changing too  - remove "Original Message Attached"
- Email text also change "The attached message was not sent" to "A message was not sent"
