### ISSUE TITLE
Mass Mailing stops and doesn't restart v8.0.2

### ISSUE THREAD

**Issue by DavidGwydion** [justingit/dada-mail#501]
I am running two small lists and at least twice a week the mass mailing stops with items in the queue. The one that is blocking says 100% complete, but it never removes it from the queue and none of the messages after that are sent.

**Comment by justingit** [comment]
Any error logs associated with the problem?

**Comment by DavidGwydion** [comment]
No. The log mostly has:
Fri May  1 11:45:02 2015] mail.cgi: defined(@array) is deprecated at plugins/bridge line 1322, <CONFIG> line 1.
[Fri May  1 11:45:02 2015] mail.cgi:     (Maybe you should just omit the defined()?)

Then it logged when I forced the queue to restart by deleting the completed head element:
[Sun May  3 23:26:29 2015] mail.cgi: restart_with set to: 20150502210004.20206759_at_sacredstatus.net at DADA/Mail/Send.pm line 1069.
[Sun May  3 23:26:29 2015] mail.cgi: Reloading message... (4784) at DADA/Mail/MailOut.pm line 1928.
[Sun May  3 23:26:30 2015] mail.cgi: returning message id<20150502210004.20206759@sacredstatus.net> at DADA/Mail/MailOut.pm line 2751.

The only other log entry I see is [Sat May  2 12:55:05 2015] mail.cgi: Given an invalid email to create a redirect from, '#digest_20150501224508' - skipping! at DADA/Mail/Send.pm line 2340.

**Comment by DavidGwydion** [comment]
It seems to stop after a digest is sent out.
