### ISSUE TITLE
Images don't show in archive view in Chrome

### ISSUE THREAD

**Issue by philmck** [justingit/dada-mail#502]
When I view archived messages containing images (e.g. http://www.bromleysymphony.org/mail/mail.cgi?flavor=archive&list=news&id=20140504170301) using Chrome, the images briefly flicker then turn to "broken link" images. The messages look OK in IE. I've tried turning off popup blockers etc.

If I right-click a broken image in Chrome and try to inspect the element I get errors and warnings like these:

Uncaught TypeError: Cannot read property 'insertBefore' of undefined
http://www.bromleysymphony.org/mail/mail.cgi?flavor=show_img&list=news&id=2…661756c742f66696c65732f62726f63687572655f323031342e6a7067brochure_2014.jpg Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://www.bromleysymphony.org/mail/mail.cgi?flavor=show_img&list=news&id=20140504170301&cid=6f72672f696d616765732f617564696f2e676966audio.gif Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://www.bromleysymphony.org/mail/mail.cgi?flavor=show_img&list=news&id=2…42f66696c65732f696d616765732f6265726c696f7a323031332e6a7067berlioz2013.jpg Failed to load resource: the server responded with a status of 500 (Internal Server Error)
VM1945:62 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
Failed to load resourcerapport_nikko_send_focus_event @ VM1945:63
Failed to load resource

My Apache error log shows lots of messages like these
[Mon May 04 18:36:17.503796 2015] [cgi:error] [pid 6768] [client 86.185.140.140:53816] Invalid status line from script 'mail.cgi': image/jpg, referer: http://www.bromleysymphony.org/mail/mail.cgi?flavor=archive&list=news&id=20140504170301

The Dada error log doesn't seem to show anything relevant (but maybe that's because it's swamped by data bridge errors, which is a different issue).

**Comment by philmck** [comment]
I checked and the problem happens even with all caching and templating disabled. It's standard LAMP hosting running on Ubuntu 14.04 LTS managed by Virtualmin.

I have noticed the problem happens only with embedded images, not linked images so for now my workaround is to avoid embedding (fairly pointless anyway these days).

The error log messages from Dada bridge are already logged in issue #458.

**Comment by justingit** [comment]
OK, thanks for the report. I bet it has something to do with corruption of the image. I usually run Firefox, and things seem to work there. I'll see if there's something interesting about Chrome that's causing this problem.
