### ISSUE TITLE
CC addresses not removed from bridge email when using SES 

### ISSUE THREAD

**Issue by kscherer** [justingit/dada-mail#507]
I recently switched from the hosting provider sendmail to use Amazon SES and one of the subscribers sent an email to the mailing list with a some additional CC addresses. This worked fine before, but after the switch to SES, this results in the addresses on the CC getting another copy of the email sent to _every_ subscriber. I was on the CC because of recent mailing list problems and I received over 100 emails because that is how many subscribers we have. Of course using SES, this means I have to pay for each additional CC address. I think any CC addresses should be removed from the email before it is sent to SES.

Using Dadmail Pro 8.0.2

**Comment by justingit** [comment]
Yikes! No good. Looking at the code, it does already take the Cc: tag out. I wonder if in the original headers, the case of the header was different: CC: rather than Cc:

**Comment by justingit** [comment]
Actually - nope, that'll still product the bug you're seeing. In dada/DADA/App/FormatMessages.pm you can find this line: 

    if (   $self->mass_mailing == 1
        && $self->{ls}->param('group_list') != 1
        && defined( $self->{ls}->param('discussion_pop_email') ) )
    {

And change it to, 

    if (   $self->mass_mailing == 1
        && defined( $self->{ls}->param('discussion_pop_email') ) )
    {

And the problem you're experiencing should be stopped.

**Comment by kscherer** [comment]
Yes when I look at the email source it is CC:

**Comment by fdinkler** [comment]
I see dadamailproject.com as expired?...

**Comment by justingit** [comment]
Lemme know if the site is coming up for you currently, or not, 

Cheers, 

-- 

Justin J: Lead Dadaist. 
url:         http://dadamailproject.com
email:    justin@dadamailproject.com
twitter:  @dadamail
skype:   leaddadaist

Dada Mail Announcements: 
http://dadamailproject.com/cgi-bin/dada/mail.cgi/list/dada_announce/

**Comment by fdinkler** [comment]
Yep,  it’s rendering now…

**Comment by bretmaverick999** [comment]
I believe the fix above worked around the root issue and didn't actually address the root issue that I've documented in https://github.com/justingit/dada-mail/issues/698. Hence if feature request https://github.com/justingit/dada-mail/issues/801 is implemented (by backing out the fix above) the root issue could reappear...
