### ISSUE TITLE
No profile access for users

### ISSUE THREAD

**Issue by dajonline** [justingit/dada-mail#514]
I wrote to you about this  before but in an email.  

I have not upgraded and installed version 8.4.0.  I am haveing the same issue as I did with version 8.3.0.  When I go to: http://nl.csamanewsletter.org/cgi-bin/dada/mail.cgi/profile_login/ there is no place to get into profiles and change one's subscription.  There is also, as you noted before, no administrator link.  Now, except for the SQL data I totally deleted the old (well I renamed the three folders to .old) and I know I checked to activate profiles with all the options, except the   Profile Host List: (I can't find any documentation on it.).  I also know I did NOT check: Hide Administration Link of  Disable Outside Logins.  

I don't know if it makes any difference but I have no fields in the profiles except the email address.  ( I do that for security, I don't need to know anyone's personal information, all I need is their email address.)  Do I need to put in a field to activate the profile feature?

Thanks for your help.

Daniel Jacobson

**Comment by dajonline** [comment]
OK I added a field and there still is no way to access profiles at http://nl.csamanewsletter.org/cgi-bin/dada/mail.cgi/profile_login/ and no administrator link.

**Comment by dajonline** [comment]
I don't need an administrator link since I go straight to the control panel via http://nl.csamanewsletter.org/cgi-bin/dada/mail.cgi/sign_in/csamanewsletter/.  However you mentioned it in your email to me when I asked about this problem initially so I include it here.

**Comment by justingit** [comment]
It's pretty hard to debug a problem without any data to look over - you're just telling me what you think you did, which is unclear to me, since you're only sharing part of the picture. 

In general, looks like profiles are working, as you can see them here:

http://dadamailproject.com/cgi-bin/dada/mail.cgi/profile_login/

There's no $PROFILE_OPTIONS variable in my .dada_config file, as I have not configured them in the installer. 

So, I'm not sure why you're seeing something totally different. My guess is that you have that variable saved in your .dada_config file. 

What's it look like?

Same with the hidden admin link - do you have the $SHOW_ADMIN_LINK variable set in your .dada_config file?

**Comment by dajonline** [comment]
I don't think you are understanding.

I did a fresh install.  I changed the names of the 8.3.0  folders to .dada_files.OLD, dada_mail_support_files.OLD, and dada.OLD.  So they where effectively uninstalled.

Then I did a fresh install of 8.4.0.

When using the dada install software, I left unchecked the 'Hide Administration Link'.  Just now I looked and in the dada_config file I found the following:

$SHOW_ADMIN_LINK        = 0;

When I changed it to:

$SHOW_ADMIN_LINK        = 1;

the administrator link shows.  Perhaps your install code did the opposite of what the description stated.  I am fairly sure I read it correctly, as I was being very aware of that issue this time around.

However I really don't want the Administrator link to show but only include it in this discussion because you brought it up.  However, the profiles still don't show up.  I want the Profiles to show.

I am writing more but I am sending this now so it won't get deleted. I already had that problem already when I accidentally closed the web page when I got distracted.

**Comment by dajonline** [comment]
you stated in your previous message:

"There's no $PROFILE_OPTIONS variable in my .dada_config file, as I have not configured them in the installer."

However I did a search on the data_config file for: '$PROFILE_OPTIONS' and found it:  It was set to:

$PROFILE_OPTIONS = { 
		
	enabled                         => 0, 
	profile_email                   => '', 
	profile_host_list               => '', 
	enable_captcha                  => 0, 
	enable_magic_subscription_forms => 0, 
	
	update_email_options            => 
	{ 
		send_notification_to_profile_email => 0, 
		subscription_check_skip            => 'auto', 
		
	},
		
	gravatar_options => 
	{
		enable_gravators     => 1, 
		default_gravatar_url => undef,
	},
	
	features => 
	{ 
		help                        => 0, 
		login                       => 0, 
		register                    => 0, 
		password_reset              => 0, 
		profile_fields              => 0, 
		mailing_list_subscriptions  => 0, 
		protected_directories       => 0, 
		update_email_address        => 0, 
		change_password             => 0, 
		delete_profile              => 0, 
	},
	cookie_params =>
	{ 
		-name    => 'dada_profile',  
	    -path    => '/',
	    -expires => '+1y',		
	},

};

I changed that to:

$PROFILE_OPTIONS = { 
		
	enabled                         => 1, 
	profile_email                   => '', 
	profile_host_list               => '', 
	enable_captcha                  => 1, 
	enable_magic_subscription_forms => 1, 
	
	update_email_options            => 
	{ 
		send_notification_to_profile_email => 1, 
		subscription_check_skip            => 'auto', 
		
	},
		
	gravatar_options => 
	{
		enable_gravators     => 1, 
		default_gravatar_url => undef,
	},
	
	features => 
	{ 
		help                        => 1, 
		login                       => 1, 
		register                    => 1, 
		password_reset              => 1, 
		profile_fields              => 1, 
		mailing_list_subscriptions  => 1, 
		protected_directories       => 1, 
		update_email_address        => 1, 
		change_password             => 1, 
		delete_profile              => 1, 
	},
	cookie_params =>
	{ 
		-name    => 'dada_profile',  
	    -path    => '/',
	    -expires => '+1y',		
	},

};

and now the profiles link shows up and everything shows up as it should.

Now I know how to fix it but something is wrong with your install software.

**Comment by justingit** [comment]
I honestly can't tell what's going on, as I'm not seeing the same behavior with the installer. My guess is that you're getting confused with perhaps multiple .dada_files locations?

**Comment by dajonline** [comment]
Hey, I did a clean install, no confusion, there is something wrong with your installer.  Did you install it fresh to see or are you just doing updates?

**Comment by justingit** [comment]
Pretty much everyday, in different environments which I do not control, as I offer installation services and I do not ever come across the problems you are seeing. That's why I'm going to call this, "unresolved" - I believe there's more to the problem that you or I know. I don't know what that is - I can only guess.

**Comment by dajonline** [comment]
Everyday, yes. But have you done what I have done.  I don't use the default install location.  I use one I choose.  (the reason being is 1. I didn't know there was a special place when I installed and 2. I have multiple sites on my server space and I keep them separate.)  Perhaps something in the the install program isn't pointing to the correct place when making the  changes to the configuration file.  Just a thought.

**Comment by dajonline** [comment]
You know computers and programming, the program does exactly what you tell it to, not necessarily what you want it to.

**Comment by justingit** [comment]
What I'll need is the problem simplified down, so that I myself can recreate it. If you're telling me your environment is non-standard and more complicated, that's too many leads for me to try to follow. If you can do that, please start another issue, and I"ll be happy to look into it,

**Comment by dajonline** [comment]
OK.
