### ISSUE TITLE
Dada Mail Not Sending

### ISSUE THREAD

**Issue by HortonsBooks** [justingit/dada-mail#515]
For the past two weeks, we have been having difficulty getting our Dada Mail mass mailer to send. Whether we are sending a webpage or an html message, the Dada Mail mailer will report the test message and/or the mailer as having been sent, but it will not send. We have tried sending the test mailers to 3 different email addresses with no luck.

Any advice?

**Comment by justingit** [comment]
I'm closing this, as this isn't a bug per say, it's a problem with your environment. If you could, post to the boards, with as much relevant information as you can: 

http://dadamailproject.com/support/boards/

**Comment by HortonsBooks** [comment]
Dear Justin,
	We were advised by Dada Mail last Monday that someone had tried to hack the our e-mail and that we should change our password.  We did as instructed, and the mail has not been sending since that time.  We would appreciate your checking into this.
	Thanks you.
	D Pittman
<a href="http://www.hortonsbooks.com/">
Horton's <br>
Books & Gifts</a>
410 Adamson SQ
Carrollton GA 30117
770-832-8021

**Comment by justingit** [comment]
Dale, email me personally, and I'll help you from there, (http://dadamailproject.com/contact/)
