### ISSUE TITLE
Error installing 8.4

### ISSUE THREAD

**Issue by fdinkler** [justingit/dada-mail#520]
Running 8.2 Pro from non-standard location (/mlm not /cgi-bin) - Bluehost account, perl and php versions OK.
Attempted to upgrade to 8.4 using install.cgi.  All install attempts appeared to complete correctly.  However, first attempt had disabled menu items that had been selected.  Reinstalled using install.cgi, no menu items across top of member page, and no graphics in bounce or membership.  Rolled back to 8.2

Below is extract from errors.txt in .logs folder.

`[Sat Sep 12 07:25:20 2015] install.cgi: Error executing run mode 'screen': HTML::Template->new() : Cannot open included file /static/css/jquery-ui-1.9.1.custom.min.css : file not found. at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/HTML/Template.pm line 1813
[Sat Sep 12 07:25:20 2015] install.cgi: 	HTML::Template::_init_template('HTML::Template=HASH(0x2a88c10)') called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/HTML/Template.pm line 1401
[Sat Sep 12 07:25:20 2015] install.cgi: 	HTML::Template::_init('HTML::Template=HASH(0x2a88c10)') called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/HTML/Template.pm line 1286
[Sat Sep 12 07:25:20 2015] install.cgi: 	HTML::Template::new('HTML::Template', 'loop_context_vars', 1, 'path', 'ARRAY(0x2815aa8)', 'die_on_bad_params', 0, 'filename', '/static/css/jquery-ui-1.9.1.custom.min.css', ...) called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/..//DADA/Template/Widgets.pm line 1899
[Sat Sep 12 07:25:20 2015] install.cgi: 	DADA::Template::Widgets::screen('HASH(0x2176f18)') called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 4420
[Sat Sep 12 07:25:20 2015] install.cgi: 	DadaMailInstaller::screen('DadaMailInstaller=HASH(0x1f2db98)') called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/CGI/Application.pm line 143
[Sat Sep 12 07:25:20 2015] install.cgi: 	eval {...} called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/CGI/Application.pm line 142
[Sat Sep 12 07:25:20 2015] install.cgi: 	CGI::Application::__get_body('DadaMailInstaller=HASH(0x1f2db98)', 'screen') called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/CGI/Application.pm line 191
[Sat Sep 12 07:25:20 2015] install.cgi: 	CGI::Application::run('DadaMailInstaller=HASH(0x1f2db98)') called at install.cgi line 25
[Sat Sep 12 07:25:20 2015] install.cgi:  at install.cgi line 25
[Sat Sep 12 07:25:21 2015] install.cgi: Wide character in print at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/CGI/Application.pm line 210, <CONFIG> line 1.
[Sat Sep 12 07:25:21 2015] install.cgi: Error executing run mode 'screen': HTML::Template->new() : Cannot open included file /static/css/jquery-ui-1.9.1.custom.min.css : file not found. at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/HTML/Template.pm line 1813
[Sat Sep 12 07:25:21 2015] install.cgi: 	HTML::Template::_init_template('HTML::Template=HASH(0x1f4ec10)') called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/HTML/Template.pm line 1401
[Sat Sep 12 07:25:21 2015] install.cgi: 	HTML::Template::_init('HTML::Template=HASH(0x1f4ec10)') called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/HTML/Template.pm line 1286
[Sat Sep 12 07:25:21 2015] install.cgi: 	HTML::Template::new('HTML::Template', 'loop_context_vars', 1, 'path', 'ARRAY(0x1cdbaa8)', 'die_on_bad_params', 0, 'filename', '/static/css/jquery-ui-1.9.1.custom.min.css', ...) called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/..//DADA/Template/Widgets.pm line 1899
[Sat Sep 12 07:25:21 2015] install.cgi: 	DADA::Template::Widgets::screen('HASH(0x163cf18)') called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 4420
[Sat Sep 12 07:25:21 2015] install.cgi: 	DadaMailInstaller::screen('DadaMailInstaller=HASH(0x13f3b98)') called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/CGI/Application.pm line 143
[Sat Sep 12 07:25:21 2015] install.cgi: 	eval {...} called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/CGI/Application.pm line 142
[Sat Sep 12 07:25:21 2015] install.cgi: 	CGI::Application::__get_body('DadaMailInstaller=HASH(0x13f3b98)', 'screen') called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/CGI/Application.pm line 191
[Sat Sep 12 07:25:21 2015] install.cgi: 	CGI::Application::run('DadaMailInstaller=HASH(0x13f3b98)') called at install.cgi line 25
[Sat Sep 12 07:25:21 2015] install.cgi:  at install.cgi line 25
[Sat Sep 12 07:27:07 2015] install.cgi: working on: change_root_password at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: HASH(0x2b3cd00) at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: tracker at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: HASH(0x2b3ce20) at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: blog_index at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: HASH(0x2b3d0c0) at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: password_protect_directories at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: HASH(0x2b3cf40) at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: log_viewer at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: HASH(0x2b3cdc0) at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: bridge at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: HASH(0x2b3ce80) at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: multiple_subscribe at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: HASH(0x2b3d060) at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: bounce_handler at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: HASH(0x2b3cee0) at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: change_list_shortname at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: HASH(0x2b3cfa0) at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: screen_cache at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: HASH(0x2b3cd60) at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: global_config at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:07 2015] install.cgi: working on: HASH(0x2b3d000) at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 2744.
[Sat Sep 12 07:27:09 2015] install.cgi: DBI connect('dbname=;host=localhost;port=3306','',...) failed: Access denied for user 'root'@'localhost' (using password: NO) at ..//DADA/App/DBIHandle.pm line 159
[Sat Sep 12 07:27:09 2015] install.cgi: CAUGHT Error with Sessioning: can't connect to db:  at ..//DADA/Profile/Session.pm line 37
[Sat Sep 12 07:27:09 2015] install.cgi:  at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/..//DADA/Template/HTML.pm line 794
[Sat Sep 12 07:27:12 2015] install.cgi: Wide character in print at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/CGI/Application.pm line 210, <CONFIG> line 1.
[Sat Sep 12 07:27:12 2015] install.cgi: Error executing run mode 'screen': HTML::Template->new() : Cannot open included file /static/css/jquery-ui-1.9.1.custom.min.css : file not found. at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/HTML/Template.pm line 1813
[Sat Sep 12 07:27:12 2015] install.cgi: 	HTML::Template::_init_template('HTML::Template=HASH(0x20b5dd8)') called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/HTML/Template.pm line 1401
[Sat Sep 12 07:27:12 2015] install.cgi: 	HTML::Template::_init('HTML::Template=HASH(0x20b5dd8)') called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/HTML/Template.pm line 1286
[Sat Sep 12 07:27:12 2015] install.cgi: 	HTML::Template::new('HTML::Template', 'loop_context_vars', 1, 'path', 'ARRAY(0x1e4aa88)', 'die_on_bad_params', 0, 'filename', '/static/css/jquery-ui-1.9.1.custom.min.css', ...) called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/..//DADA/Template/Widgets.pm line 1899
[Sat Sep 12 07:27:12 2015] install.cgi: 	DADA::Template::Widgets::screen('HASH(0x17abe18)') called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/lib/DadaMailInstaller.pm line 4420
[Sat Sep 12 07:27:12 2015] install.cgi: 	DadaMailInstaller::screen('DadaMailInstaller=HASH(0x1562b98)') called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/CGI/Application.pm line 143
[Sat Sep 12 07:27:12 2015] install.cgi: 	eval {...} called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/CGI/Application.pm line 142
[Sat Sep 12 07:27:12 2015] install.cgi: 	CGI::Application::__get_body('DadaMailInstaller=HASH(0x1562b98)', 'screen') called at /home1/hostname/public_html/wrpoa/cgi-bin/dada/installer/../DADA/perllib/CGI/Application.pm line 191
[Sat Sep 12 07:27:12 2015] install.cgi: 	CGI::Application::run('DadaMailInstaller=HASH(0x1562b98)') called at install.cgi line 25
[Sat Sep 12 07:27:12 2015] install.cgi:  at install.cgi line 25`

**Comment by justingit** [comment]
I can help you on the boards, but this is obv. just a problem/confusion with configuring your Dada Mail. 

http://dadamailproject.com/support/boards/

**Comment by fdinkler** [comment]
Hey Justin – 

 

Officially, characters to the left of the ‘@’ are case sensitive.  Most email hosts are set-up as case insensitive.

 

I encountered a situation where the subscribed email was “EmailAddr@host.com <mailto:EmailAddr@host.com> ” and the unsubscribed email was emailaddr@host.com <mailto:emailaddr@host.com>  and the Blacklist filter didn’t pick it up.

 

Enhancement? 

How does Dada handle email case internally?

Thanks,           Fred
(fdinkler)

**Comment by justingit** [comment]
Email case is configurable: 

http://dadamailproject.com/d/global_variables.pod.html#EMAIL_CASE

By default it's set to, "lc_all", sounds like it would make sense for you to set it to, "lc_domain"
