### ISSUE TITLE
RSS Archive & "Only Allow Subscribers to View Archived Messages "

### ISSUE THREAD

**Issue by kingofthering** [justingit/dada-mail#521]
Hi Justin,
RSS Feeds will not work anymore if you enable "Only Allow Subscribers to View Archived Messages" in the settings. At least Outlook 2010 and latest Firefox do not recognize to use authentication.

Best,
Axel

**Comment by justingit** [comment]
That's by design. Makes sense: the RSS feeds are public - if you've disabled archives to be publicly viewed: bye bye RSS feed.

**Comment by kingofthering** [comment]
Hi Justin,
this post is already 10 years old but it lists several feeds that do support authentication. Adding username and pwd to the url could be a pretty easy way - no?

http://labs.silverorange.com/archive/2003/july/privaterss

Thx,
Axel

**Comment by justingit** [comment]
So is this a bug report or a feature request ;) 

I  don't think I like the idea of using just HTTP Authentication for RSS feeds, or requiring that SSL be available. One other suggestion would be to have a specific token to place in the RSS URL for each subscriber, but it's the same problem as HTTP Authentication over a non-SSL connection - the token is in plain text and can be used by anyone.
