### ISSUE TITLE
Logrotation

### ISSUE THREAD

**Issue by kingofthering** [justingit/dada-mail#524]
Hi Justin,
my cron job stopped working out of a sudden. Opening the link reported "internal Server Error"
I realized that the eror.txt file was 65536Kb and when I deleted it the cron job started again.

Obviously the server has a problem handling files with the used perllib.

Would it be possible to add logrotation?

Thx,
Axel

**Comment by justingit** [comment]
I think log rotation would be a good wishlist item. Right now, you could probably just set up another cronjob to do the log rotation job for you, (via mv)

65 megs is not a whole heck of a large error log, though and Dada Mail would only be opening it to write to, not read and certainly not to read all at once, so I don't suspect the size of the file will matter. But rather, I wonder if the permission to the file were changed? Even if the permissions to the error log file are changed, Dada Mail should still run, just not be able to write into the error log. 

What version of Dada Mail are you using?

**Comment by kingofthering** [comment]
Hi Justin,
Ansolutely with u, 65megs is nothing, but it could grow infinetely...
I run 8.4

I need to change my web hoster, the server sucks everywhere ... Even if its the biggest german one ...
Thx,
Axel

**Comment by justingit** [comment]
Most any cPanel host will work well - this is a partner referal link for Bluehost: 

http://www.bluehost.com/track/dadamail/
