### ISSUE TITLE
Unsubscribe from form not working

### ISSUE THREAD

**Issue by philmck** [justingit/dada-mail#525]
Unsubscriptions from a web form don't seem to be working any more in Dada 8.4.0 Pro. I get a 500 server error whenever I try. (Subscriptions from the form still seem to work, as do unsubscriptions from a link in a mail message.)

My web server (running Ubuntu 14.04, in fastCGI mode, managed by webmin) reports in the error log:
End of script output before headers: mail.cgi, referer: [my Dada URL]

The Dada error log shows:
Invalid header value contains a newline not followed by whitespace: location="Status: 302 Found
Location: http://www.skeptic.org.uk/cgi-bin... at (eval 27) line 34, <CONFIG> line 1

Unfortunately the ellipsis in that last error log line hides the location of the problem so I'm not sure how to debug this further.

I get the same symptoms when trying in the Modal and Full subscription form preview in the admin interface as well as the "live" form.

**Comment by justingit** [comment]
There hasn't been a form where you can unsubscribe from a mailing list in Dada Mail for a few versions, now. There was some overlap where the feature was removed officially, but it still worked. I bet that was taken out in v8. 

The two ways someone can unsubscribe is either from the unsubscribe link in an email, or through their profile.

**Comment by philmck** [comment]
Ah, it seems someone has overridden the subscription_form_widget.tmpl file on the installation in question, which means it still shows the unsubscribe option even though it has been removed from the core files. 

Could we make this into a documentation request instead of a bug report, in that case?

**Comment by justingit** [comment]
Well, there's this, 

http://dadamailproject.com/d/features-unsubscription_system.pod.html#The-Unsubscription-Link

Looks like the unsusbcribe option in the subscription form was removed in v6.4.0
