### ISSUE TITLE
cgi-bin not accessible for installation process

### ISSUE THREAD

**Issue by edwarddesc** [justingit/dada-mail#527]
Hi,
I tried to install Dada Mail for testing and hopefully adopt for our mailing needs.
Our hosting server does not allow us to execute the "uncompress_dada.cgi", it says "Forbidden, You don't have permission to access /cgi-bin/ on this server." (I did put the authorisation to 755 both on the folder and on the file)...
Alternative solutions ?
Thank you, Edward

**Comment by justingit** [comment]
Hi Edward, 

This is the issues tracker, not the forum for general help. You would want to post this in, 

http://dadamailproject.com/support/boards/
