### ISSUE TITLE
Version Check in 9.0.1

### ISSUE THREAD

**Issue by Hawkwala** [justingit/dada-mail#528]
I just installed Stabe version 9.0.1 and when I do "Version Check" I get the following message:

Version Checker

The most recent version is 8.4.0 Stable .

You're currently running, 9.0.1 Stable 12/09/15

Download the latest Version of Dada Mail

View the Most Current Documentation

**Comment by justingit** [comment]
Thanks for the report - that should be fixed now, 

Cheers,
