### ISSUE TITLE
Attachments now failing on 9.0.1 stable with core5 filemanager

### ISSUE THREAD

**Issue by philmck** [justingit/dada-mail#531]
Messages are coming through with nothing attached, even though everything looks OK in the admin screen. 

My error log shows
[Sun Dec 27 16:17:59 2015] mail.cgi: id, '320' doesn't exist! at DADA/App/MassSend.pm line 1660.
I can't find attachment file: /home/skeptic/public_html/dada_mail_support_files/file_uploads//dada_mail_support_files/file_uploads/Intelligencer 2015 4.doc at DADA/App/MassSend.pm line 1768.

That path is clearly incorrect - it looks like the "uploads_directory" and "url_path" configurations in filemanager_config.pl are being concatenated. Something about the meaning of these paths has changed and broken compatibility. I've tried fiddling with them and I can make the error message go away but the attachment still doesn't arrive.

**Comment by philmck** [comment]
I've just seen that 9.0.2 is available and includes a fix for file attachments, I'll try it out.

**Comment by philmck** [comment]
Good news, it works. You can close this bug.

All I want for Christmas is a regression test suite so problems like this get caught before they affect end users!

**Comment by justingit** [comment]
Re: test suite - there is one, but coverage isn't 100%. - that's what all the files in dada/t are. 

This is an interesting problem as it deals with a form value set programmatically by  javascript that's then passed to the Perl part of Dada Mail to attempt to make sense of. To set up a test for this, we'd have to perhaps set up an environment similar to an actual installation and run a headless webserver that still understands javascript. 

Not impossible, but not something I can whip up in a few minutes. ;) I think this problem originates in upgrades either the rich text editor of file browser - it just gives back a slightly different value, which trips up Dada Mail. 

I feel you when it comes to these sorts of bugs, though. I attempt to vet them out as best I can, but I also have to anticipate them coming to the surface and dealing with them efficiently. Just the nature of the beast,

**Comment by philmck** [comment]
I didn’t realise it was so complicated – I agree a headless webserver might be the solution. 

 

It was certainly dealt with efficiently, in that the fix was available before I even reported the problem. In a way the root cause was that I wasn’t aware of the bugfix release. I’m subscribed to Dada announcements but the last message was for Dada 9.0.0 on 8th December. Also I didn’t see it when searching Github.

 

At least you’re supporting the product well and I like the new Foundation back end. Thanks and have a great 2016.

 

-- 
Phil McKerracher
+44 7565 803841
www.mckerracher.net

**Comment by justingit** [comment]
The main announcment list is just use for major announcements, bugfix releases could be daily, so I try not to annoy my subscribers. 

Places to get alerted when a new upgrade is available: 
Dev list: 
http://dadamailproject.com/cgi-bin/dada/mail.cgi/list/dadadev/

Blog: 
http://blog.dadamailproject.com/

Sourceforge: (look for, "KEEP ME UPDATED") 
https://sourceforge.net/projects/dadamail/

**Comment by philmck** [comment]
Great, thanks – you have a new blog subscriber.

 

-- 
Phil McKerracher
+44 7565 803841
www.mckerracher.net
