### ISSUE TITLE
Core5 Filemanager returns URL, relative to site root, which is broken when email w/image is sent

### ISSUE THREAD

**Issue by justingit** [justingit/dada-mail#533]
Not sure why, but Filemanager does not return the full URL of the image you select (KCFinder does). 

When sending out images, any images places using Core5 Filemanager will be broken, as the URL for the image is not turned into an absolute URL.

**Comment by philmck** [comment]
Still seems to be broken in 9.0.3 if option "Embed Images in Message" is selected.
