### ISSUE TITLE
TinyMCE insert link dialogue broken, Dada Pro 9.0.2 stable

### ISSUE THREAD

**Issue by philmck** [justingit/dada-mail#535]
If I try to edit or create a hyperlink in WYSIWYG mode using TinyMCE, the dialogue that pops up is too narrow so it's impossible to edit the URL. This used to be OK in previous versions. Viewed using Chrome browser latest version.

The problem can be worked around by using the "Source" view to directly edit the HTML.

**Comment by justingit** [comment]
Very strange! I'll have to dig a little and see why this may be happening. All the other modal windows that pop up seem to at least be usable.

**Comment by justingit** [comment]
Just for kicks, I upgraded my Tiny MCE to see if it's a fix we can get "for free", by changing the following in my admin_template.tmpl from, 

		<script src="/tinymce.min.js?v=" type="text/javascript"></script>



to, 


			<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>


but the problem persists.
