### ISSUE TITLE
Assigned Password to List - Can No Longer Switch between lists v9.0.2 and v9.0.3

### ISSUE THREAD

**Issue by Mark1953** [justingit/dada-mail#540]
Silly me, thought I would add a password to three of the lists so I could share the access with another user, without revealing the root password.
Well first noticed that I couldn't switch between lists, and other user bailed.   So I tried resetting the list to the root password, no joy, then tried changing to no password, then tried changing in sql table...
All no joy.  Any suggestions on how to return the three lists to the group and enable switching between them again?

**Comment by justingit** [comment]
The Pro Dada Root Pass should be set in the .dada_config file. You *can* change it, 

http://dadamailproject.com/d/FAQ-general.pod.html#How-do-I-fetch-reset-the-Dada-Mail-Root-Password

but it may not be needed in this case. You just need to change the List Passwords. Log into each list with what you think is the Dada Mail Root Pass, then go change the list password, to something that's not the Dada Mail Root Password. Repeat for each of your mailig lists. That's it!

**Comment by Mark1953** [comment]
Justin,

I tried working through the List’s change password option after using the root pass to log in.  When I click Change Password, it throws a Yikes server error.

Here is the log entry: “DBD::mysql::st execute failed: Column count doesn't match value count at row 1 at /DADA/MailingList/Settings/baseSQL.pm line 112.

cannot do statement Column count doesn't match value count at row 1“

 

As it looks to be a SQL table issue, not sure this issue would go away by switching to the not-recommended unencrypted password option.

 

So, should I just cut my loss and create three replacement lists?

 

Thanks,

Mark

**Comment by justingit** [comment]
I'm guessing this happened because of whatever changes you may to the MySQL database directly. Changing the Pro Dada Root Password wouldn't fix this. 

It's up to you - I don't know how to fix the issue you're seeing now.

**Comment by Mark1953** [comment]
Copy that.

**Comment by Mark1953** [comment]
Okay, so I removed the autoincrement record Id field I added from the settings table, and the password reset worked.   I then logged into the list but the option to switch to another list from the list does not appear.
If I log into one of the other lists that I always used the root password to access, the switch from the list option is available.
Is there a setting that controls the switch list option?

**Comment by justingit** [comment]
> I then logged into the list but the option to switch to another list from the list does not appear.

That's probably because your list password is the same as the Dada Root Password. Change the list password to something other than the value of the Dada Root Pass.

**Comment by Mark1953** [comment]
Well that fixed it. So it looks like the addition of a auto-increment field to the settings table ( a kludge to solve a different issue some months ago) caused all these issues. 

Thanks for your help.

**Comment by justingit** [comment]
Mark, for  customer support for the app, rather than filing issue reports, please use the Zendesk next time - just open a ticket by emailing, 

support@dadamail.zendesk.com

Cheers,

**Comment by Mark1953** [comment]
Copy That
