### ISSUE TITLE
Dada's cron job creates a security exception

### ISSUE THREAD

**Issue by goobertron** [justingit/dada-mail#541]
*(NB: I can't see anything on your site relating to reporting security exceptions, and as this relates to a security exception thrown up on my server rather than one in the software itself, I hope it's safe to report it here. Apologies if not.)*

Hi there,

I recently got the scheduling set up properly. However, the cron job was throwing up an 403 error. My host's support team looked into it and worked out that it was the semi-colon in the user-agent which caused the error. Removing this semi-colon solved it and the scheduling now works perfectly.

On http://dadamailproject.com/support/documentation-9_0_3/features-scheduled_cronjobs.pod.html the cron job is given as

`*/5 * * * * /usr/bin/curl --user-agent "Mozilla/5.0 (compatible;)" --silent --get --url http://example.com/cgi-bin/dada/mail.cgi/_sched513A3F128C5C41EC/_all/_all/_silent/`

and this semi-colon also appears in the 'flavoured' cron job given me in the control panel of my install. Simply removing the semi-colon does the trick.

The error thrown up, for my host's servers at least, is:

`[Thu Jan 28 16:34:42 2016] [error] [client 80.82.116.123] ModSecurity: [file "/etc/httpd/modsecurity.d/20_asl_useragents.conf"] [line "361"] [id "309925"] [rev "7"] [msg "Atomicorp.com WAF Rules: Suspicious User-Agent, parenthesis closed with a semicolon Mozilla/5.0 (compatible;)"] [severity "CRITICAL"] Access denied with code 403 (phase 2). Match of "rx (Qualidator\\\\.com|ExaleadCloudView|^Mozilla/4\\\\.0 \\\\(compatible;\\\\)$|UTVDriveBot|Add Catalog|^Appcelerator|GoHome Spider)" against "REQUEST_HEADERS:User-Agent" required. [hostname "mail.example.com"] [uri "/mail.cgi/_sched{my_schedule_flavour}/_all/_all/_silent/"] [unique_id "{unique_job_id}"]`

I don't know whether this is the same for all servers. If not, I don't know how to find out which servers it causes a problem for, but I can ask my hosts if they can provide any further information if you need it. I do know that my site is hosted on a server running a pared-down version of CentOS. If some servers require the semi-colon, perhaps a note could be added to the documentation and the Scheduled Jobs page of the control panel that if this throws up a 403 error, try removing the semi-colon.

-------------

One small related matter: for many months I couldn't get scheduling working using 7.4.0. I thought there must be a flaw in my install, so I upgraded to 9.0.3 to try to fix this. It didn't, but reviewing how I upgraded to try to find something I did wrong, I stumbled across your upgrade video tutorial, and watched it. This explained that the cron job was the means by which all scheduled tasks in Dada were performed. From reading the documentation, I had thought that the cron job was an alternative way of scheduling tasks for people who preferred command-line admin.

Changing a sentence on the http://dadamailproject.com/support/documentation-9_0_3/features-scheduled_cronjobs.pod.html page would clarify it, I think:

> Some of Dada Mail's more powerful features depend on a cronjob to be run on a periodic schedule.
> 
> Only one cronjob is required for all scheduled tasks in Dada Mail. It is composed of a URL that will need to be accessed.

I suggest changing the second paragraph to:

> In order for scheduled tasks to work in Dada Mail, you first have to set one cronjob. This cronjob periodically accesses a URL that prompts scheduled tasks to be run.

Maybe the last part of that second sentence isn't quite accurately worded and needs to be tweaked, but I think it will be clearer to say it this way. (This change would have to be made in the documentation for each version, of course.)

Thanks again for the fantastic software.
goob

**Comment by justingit** [comment]
mod_security does in fact get in the way of many things in Dada Mail. Obviously, the semicolon in the user agent string is a false positive, so I would say it's on your host to resolve that. If they don't want to, fine - that is why I do give alternative directions on setting up the cronjob, 

http://dadamailproject.com/d/features-scheduled_cronjobs.pod.html#Running-the-scheduled-jobs-via-the-command-line

v7 would have had a different way to set up the Beatitude plugin's cronjob (scheduled mailings), which was changed in v8.
