### ISSUE TITLE
Sending / Options - "Save For Selected Mailing Lists" button is editable not clickable

### ISSUE THREAD

**Issue by frederickjh** [justingit/dada-mail#547]
Hi!
I just upgraded to 9.1.1 and was configuring smtp  for the lists. I got it working and then clicked on the **Save for Multiple Lists ...** button. The modal window pops up. I then tried to click on the **Save For Selected Mailing Lists** button but it would not click. Instead a cursor appear like I could edit the text on the button .  . .

![screenshot from 2016-02-25 23 05 46](https://cloud.githubusercontent.com/assets/864159/13336619/40188150-dc17-11e5-9d91-68c024757436.png)

and I did!
![screenshot from 2016-02-25 23 07 09](https://cloud.githubusercontent.com/assets/864159/13336440/37a9a734-dc16-11e5-9dd0-685cc5d8bbd1.png)

I am using Google Chrome on Linux.
![screenshot from 2016-02-25 23 15 21](https://cloud.githubusercontent.com/assets/864159/13336455/488a62f0-dc16-11e5-852e-60edd330500e.png)

This is a usability problem as it makes saving the settings to multiple lists unusable.
Thanks for taking a look at this!
Frederick

**Comment by frederickjh** [comment]
An update. I just found that in **Sending / Advanced Options** that the **Save For Selected Mailing Lists** although editable is clickable. Not sure if that helps find the root of this issue.

**Comment by frederickjh** [comment]
Hi justingit!
With these changes I can no longer edit the button text but I find it is still not clickable. Cancel works to exit the popup but  the **Save for selected list** button does not work.
Greetings!
Frederick

**Comment by justingit** [comment]
Hi Frederick, are you having this problems when using the Chrome browser?
