### ISSUE TITLE
Hide Disabled Screens not working with classic side bar V9.1.1

### ISSUE THREAD

**Issue by rtzee** [justingit/dada-mail#549]
Please see screen cap showing option settings. With this configuration, individual menu items are shown as disabled. However, if an entire menu block is disabled, then it is hidden as expected. 

![control panel settings enable_disable features](https://cloud.githubusercontent.com/assets/7243499/13534237/fba27e54-e1e8-11e5-8908-4dea1e239441.jpg)

![mass mailing send a message](https://cloud.githubusercontent.com/assets/7243499/13534265/19b0ed18-e1e9-11e5-8ae2-3bda7f018f94.jpg)

**Comment by justingit** [comment]
Appreciate the report, Rob, I'll look into it,
