### ISSUE TITLE
"Switch..." menu cut off

### ISSUE THREAD

**Issue by cosmocanuck** [justingit/dada-mail#550]
Hi Justin! I've noticed in the new version of Dada Mail, the "Switch..." menu has an issue when there are a lot of lists. It just cuts off near the bottom of the window, with no ability to scroll down to see anything more. (There are in my case 16 more lists I can't access via this menu.)

Tested it in Safari and Firefox on Max OS 10.11.3, El Capitan.

Hope it's not too tricky a fix!  
Adam

[screen shot 2016-01-07 at 11 01 56 am](https://cloud.githubusercontent.com/assets/5876049/13594471/7fc83732-e4b9-11e5-8429-07f91186fd88.jpg)

**Comment by justingit** [comment]
That's a lot of lists! 

Maybe a workaround for now would be to make the width of the window smaller, so you can use the mobile navigation - that should just have a popup menu to select the list you want to log into.

**Comment by cosmocanuck** [comment]
Yep, a lot of lists, but I have set up lists for many of my clients… still, the mobile-menu workaround works well. Not a major issue and indeed most people won’t run into it ,but wanted to let you know…

Adam



> On Mar/8/2016, at 10:01 AM, Justin J <notifications@github.com> wrote:
> 
> That's a lot of lists!
> 
> Maybe a workaround for now would be to make the width of the window smaller, so you can use the mobile navigation - that should just have a popup menu to select the list you want to log into.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/justingit/dada-mail/issues/550#issuecomment-193893350>.
> 




CLICK TO VIEW MORE ABOUT...
web solutions <http://adamabramsdesign.com/tag/website/>  print design <http://adamabramsdesign.com/tag/print/>
database + organization <http://adamabramsdesign.com/tag/database/>
technical support
 <applewebdata://36DD42EF-2A9C-4C21-A0B4-9A9735E00618#>video production <applewebdata://36DD42EF-2A9C-4C21-A0B4-9A9735E00618#>
(604) 685-7634 <tel:6046857634> • www.adamabramsdesign.com <http://www.adamabramsdesign.com/>

**Comment by justingit** [comment]
I'm def. interested in knowing about the problem, and I'll leave this issue, until I can figure out a fix,

**Comment by rspilk** [comment]
This is still an ongoing issue in 11.1.1 Stable.

It is necessary to work around by manipulating the window size for mobile view and not use the standard view when administrating the lists as root
