### ISSUE TITLE
¿bug? Password 

### ISSUE THREAD

**Issue by luism566** [justingit/dada-mail#571]
I have installed dada 9.2.2.

By putting passwords over 8 characters only leaves 8 characters.
eg 1234567890 pasword: 12345678

Passes for options:
Change the program Root Pasword and
Password list

Is this normal?
I think not

**Comment by justingit** [comment]
This is actually normal, as Dada Mail uses the crypt algorithm, 

https://www.ratliff.net/blog/2007/09/20/password-length/
