### ISSUE TITLE
Problems sending via SMTP: Can't call method "auth" on an undefined value at /DADA/Mail/Send.pm

### ISSUE THREAD

**Issue by deanet** [justingit/dada-mail#576]
i'm using Dada Mail 9.4.1

getting error when setup external smtp to mailgun.org . all port outbond not blocked, host is up, still doesnt understand why can't call auth in Send.pm

```


You changes have been saved!

Testing SMTP Sending...

Results:
Host smtp.mailgun.org could not be pinged at port 587. Outbound port may be blocked, or host is down at specified port

Raw Log:
Problems with connecting to the SMTP Server: Permission denied at /DADA/App/Messages.pm line 154
Debug => 1
Hello => abc.co.id
Port => 587
Timeout => 60
Host => smtp.mailgun.org
at /DADA/App/Messages.pm line 154
Problems sending via SMTP: Can't call method "auth" on an undefined value at /DADA/Mail/Send.pm line 424.
at /DADA/App/Messages.pm line 154
```

any advices ?

thank you,

**Comment by justingit** [comment]
Well, it does seem the ping test is failing, 

    Host smtp.mailgun.org could not be pinged at port 587. Outbound port may be blocked, or host is down at specified port

Maybe double check that port is open?

**Comment by deanet** [comment]
@justingit 

sure, port is open, host is pingable

![image](https://cloud.githubusercontent.com/assets/275259/16831418/198fdcf6-49cf-11e6-8caf-06e1ca42ef47.png)

**Comment by deanet** [comment]
should i install smtp_auth module via cpan manually ?

**Comment by deanet** [comment]
apologize, Selinux has been enabled. solved this issue.
