### ISSUE TITLE
Cellphone Access

### ISSUE THREAD

**Issue by Falcon911** [justingit/dada-mail#577]
Every Time  try and access the Dadamail admin section from my cellphone it gives me "Your IP address has changed" . even though I am inside my house with Wifi...

**Comment by justingit** [comment]
I won't be able to debug your cellular or local wifi network, but that is a feature (checking matched IP addresses) that you can disable in Dada Mail, 

http://dadamailproject.com/d/changes_9_x.pod.html#Disabling-IP-Check-in-List-Control-Panel-sessions

**Comment by Falcon911** [comment]
Thanks you sir for the quick response.
