### ISSUE TITLE
Invalid header reported in unsubscription

### ISSUE THREAD

**Issue by plabong** [justingit/dada-mail#585]
I have my own subscription page; subscription is ok;
unsubscription throws error - mail.cgi is called with this line:

`https://<mydomain>/dm/mail.cgi?list=rv01&f=unsubscribe&email=localpart%40web.de`

dadas error.log tells me this: 

```
Invalid header value contains a newline not followed by whitespace: location="Status: 302 Found
Location: https://<mydomain>/dm/mail.... at (eval 18) line 34, <CONFIG> line 1.
```

Peter
_Debian 9 (stretch) kernel 4.6.0-1-amd64 / Apache/2.4.23 (Debian) / Perl 5.22 / Dada pro 9.6.0_

**Comment by justingit** [comment]
Version of Dada Mail?

**Comment by plabong** [comment]
dada pro 9.6.0
