### ISSUE TITLE
Can't set a Reply-To header for discussion list emails

### ISSUE THREAD

**Issue by ashmcc** [justingit/dada-mail#586]
I'm trying to migrate a discussion list onto dada/bridge (v9.6.0), and one issue is snagging the process.  I can set a default Reply-To header in Config.pm (line 1821, %EMAIL_HEADERS), but no such header appears in issued emails.  I believe this is probably a bug?
As is the convention with discussion lists, replies should always go back to the List Email address by default, and therefore to all subscribers rather than to the individual sender.  I can't see any way to ensure that the appropriate header is included to make this happen, and the default headers config is apparently being ignored.

**Comment by justingit** [comment]
There is a preference in Bridge to change where replies go to by default. In the end though, it would be up the mail reader on how to interpret those headers, unfortunately.

**Comment by ashmcc** [comment]
Hi, thanks for replying so fast.
I've set the "Replies to messages should:" setting to "be addressed to the mailing list", however this doesn't seem to have any effect.
I understand that interpretation of the headers is up to the mail reader, but my issue is that the header isn't appearing in the first place.  Looking at the raw message received, there is no "reply-to" header at all.
