### ISSUE TITLE
Bridge loses mails if stopforumspam is down

### ISSUE THREAD

**Issue by smy213** [justingit/dada-mail#588]
If stopforumspam.com is down and "Enable StopForumSpam Protection" is checked for a list, the bridge runs unto an irrecoverable error and the mailing is lost.

`mail.cgi: bridge - irrecoverable error processing message. Skipping message (sorry!)`

Here is the related snippet of errors.txt: 
```
[Thu Sep  1 08:37:37 2016] mail.cgi: Problem fetching url, 'http://www.stopforumspam.com/api?f=json&ip=37.17.224.74':502 Bad Gateway at DADA/MailingList/Subscriber/Validate.pm line 404
[Thu Sep  1 08:38:37 2016] mail.cgi: Problem fetching url, 'http://www.stopforumspam.com/api?email=XXXXXX%40YYY.de&f=json':502 Bad Gateway at DADA/MailingList/Subscriber/Validate.pm line 418
[Thu Sep  1 08:38:37 2016] mail.cgi: bridge - irrecoverable error processing message. Skipping message (sorry!): Undefined subroutine &DADA::MailingList::Subscriber::Validate::ping_test called at DADA/MailingList/Subscriber/Validate.pm line 432.
[Thu Sep  1 08:38:37 2016] mail.cgi:  at plugins/bridge line 1057
[Thu Sep  1 08:38:37 2016] mail.cgi:    bridge::__ANON__('Undefined subroutine &DADA::MailingList::Subscriber::Validate...') called at /home/www/xxxxxxx.de/dada/DADA/perllib/Try/Tiny.pm line 100
[Thu Sep  1 08:38:37 2016] mail.cgi:    Try::Tiny::try('CODE(0x2c5c430)', 'Try::Tiny::Catch=REF(0x2c32a18)') called at plugins/bridge line 1060
[Thu Sep  1 08:38:37 2016] mail.cgi:    bridge::start(undef) called at plugins/bridge line 892
[Thu Sep  1 08:38:37 2016] mail.cgi:    bridge::scheduled_task('_all') called at /home/www/xxxxxxx.de/dada//DADA/App.pm line 13759
[Thu Sep  1 08:38:37 2016] mail.cgi:    DADA::App::__ANON__() called at /home/www/xxxxxxx.de/dada/DADA/perllib/Try/Tiny.pm line 76
[Thu Sep  1 08:38:37 2016] mail.cgi:    eval {...} called at /home/www/xxxxxxx.de/dada/DADA/perllib/Try/Tiny.pm line 67
[Thu Sep  1 08:38:37 2016] mail.cgi:    Try::Tiny::try('CODE(0x1b3ac40)', 'Try::Tiny::Catch=REF(0x1d05c88)') called at /home/www/xxxxxxx.de/dada//DADA/App.pm line 13762
[Thu Sep  1 08:38:37 2016] mail.cgi:    DADA::App::schedules('DADA::App=HASH(0x1b15c90)') called at /home/www/xxxxxxx.de/dada/DADA/perllib/CGI/Application.pm line 143
[Thu Sep  1 08:38:37 2016] mail.cgi:    eval {...} called at /home/www/xxxxxxx.de/dada/DADA/perllib/CGI/Application.pm line 142
[Thu Sep  1 08:38:37 2016] mail.cgi:    CGI::Application::__get_body('DADA::App=HASH(0x1b15c90)', '_schedules') called at /home/www/xxxxxxx.de/dada/DADA/perllib/CGI/Application.pm line 191
[Thu Sep  1 08:38:37 2016] mail.cgi:    CGI::Application::run('DADA::App=HASH(0x1b15c90)') called at /home/www/xxxxxxx.de/dada/mail.cgi line 24
```
I would expect this to be handled gracefully:
- inform the sender about the problem
- keep the mailing queued
- inform admin about the problem
- allow configuration "send anyway, if stopforumspam is not reachable for 10 minutes" (or so...)

**Comment by justingit** [comment]
> I would expect this to be handled gracefully:

Your solution has a lot of complexity! :) 

I think there is a design choice made. If the StopForumSpam service  IS down, the module I use always returns a false negative, which is what you're seeing. Their rationale is that spam shouldn't be able to be posted, if the service itself is down, and its up to the site administrator to check on the issue. 

https://metacpan.org/pod/WWW::StopForumSpam
    # Returns 1 if spammer (caution: it will return 1 also on errors, this is to
    # prevent mass spam registration due to services not working properly, you 
    # should therefor always check logs)

I'm not sure if I agree, as I think it's first and foremost absolutely critical that the main function of the app friggin work, despite problems with a service we're relying. I think you have a similar opinion. 

Although, what version of Dada Mail are you currently using? This: 

    [Thu Sep  1 08:38:37 2016] mail.cgi: bridge - irrecoverable error processing message. Skipping message (sorry!): Undefined subroutine &DADA::MailingList::Subscriber::Validate::ping_test called at DADA/MailingList/Subscriber/Validate.pm line 432.

Shouldn't currently be a problem ( Undefined subroutine &DADA::MailingList::Subscriber::Validate::ping_test ) in the latest release.

**Comment by smy213** [comment]
Thanks for your prompt attention! I'm still using Dada Mail 9.5.0 07/11/16; time to update... 

I do understand the approach of $sfs->check() returning 1 in case of error. But for a low traffic private mailing list silently disappearing messages are just not acceptable. I will have to go without stopforumspam then, which is OK for my case. 

Thanks again!

**Comment by justingit** [comment]
Yeah, I def. think I'll change the behavior of this module (I forked it, actually!) to work like we're thinking, and maybe just complain loudly about the service not being accessible in the error logs.

**Comment by justingit** [comment]
Thanks for the feedback, I'm happy I to have another voice on the current behavior.

**Comment by justingit** [comment]
This behavior will be changed in v9.6.1 - if the service is down, the check will now NOT give a potential false positive.
