### ISSUE TITLE
Adding a Profile Field "group" produces SQL Syntax Error

### ISSUE THREAD

**Issue by joaoflux** [justingit/dada-mail#589]
DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group TEXT NOT NULL DEFAULT ''' at line 1 at DADA/ProfileFieldsManager/baseSQL.pm line 148.
cannot do statement (at add_field)! You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group TEXT NOT NULL DEFAULT ''' at line 1
 at /kunden/499355_10711/dada/DADA/App.pm line 8707.

**Comment by justingit** [comment]
So, is it the name, "group" that fails? Does a different name work, instead?

**Comment by joaoflux** [comment]
Hey Justin,
yes, other names work. I suppose it’s not properly escaped and interpreted as SQL.

Cheers,
Joachim
