### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by off1now** [justingit/dada-mail#590]
I have tried to install v9.6.0 with no success due to my Perl script not being high enough (5.8.8) on the server. Got this error.

Bad name after tmp' at /hermes/bosnaweb09a/b375/ipg.scergaorg/dada/installer/lib/DadaMailInstaller.pm line 48.
Compilation failed in require at /home/users/web/b375/ipg.scergaorg/dada/installer/install.cgi line 23.
BEGIN failed--compilation aborted at /home/users/web/b375/ipg.scergaorg/dada/installer/install.cgi line 23.

Through iPage where my account is hosted I can install an older v9.1.3 through Mojo Marketplace but keep getting this error message. 

Unfortunately something went wrong. While attempting to step through the normal user procedures required to complete your request something went wrong. This typically means we ran in to an unforeseen event in the process which caused the process to fail in order to avoid delivering an incomplete or damaged application post process.

I'd really like to be able to use this product for our nonprofit. Need advice/instructions please.

**Comment by zentico** [comment]
Have exactly the same issue.

off1now, also found that DADA/config.pm needed to have the right localhost for ipage (which is yourdomain.ipagemysql.com), but this didn't fix the above installation error.

**Comment by justingit** [comment]
Perl v5.10.1 is required; Perl v5.8.8 will not work. 

v9.1.3 of Dada Mail also requires v5.10.1 of Perl to work.

**Comment by zentico** [comment]
Thanks, justingit.  Already asked iPage to get with the program and upgrade.  Will attempt to host Dadamail elsewhere for now, though don't know if that would still allow me to use my iPage SMTP.  Guess it shouldn't be a problem.
