### ISSUE TITLE
Email Sending Options Test Only Shows a PlainText Message (no HTML)

### ISSUE THREAD

**Issue by gizzyman** [justingit/dada-mail#594]
appears the file
mail_sending_options_test_message.html 
is missing in v10

**Comment by gizzyman** [comment]
just added the patch, ran test (sending -> options -> test)
received this error

$html_file does not exist at, /home/vcomm/public_html/dada_mail_support_files/themes/email/default/dist/mail_sending_options_test_message.html at /DADA/App/EmailThemes.pm line 143.
<<< 220-ns1.vcomm.net ESMTP Exim 4.87 #1 Thu, 20 Oct 2016 22:00:00 -0700

**Comment by justingit** [comment]
$html_file does not exist at, /home/vcomm/public_html/dada_mail_support_files/themes/email/default/dist/mail_sending_options_test_message.html at /DADA/App/EmailThemes.pm line 143.

I'm not too worried about that, so long as test email is actually sent AND received. 

I'll ship with a HTML version of this email - the templates that make up the theme are developed in a separate project (for example:) 

https://github.com/justingit/dada_mail_foundation_email_templates/blob/46c07462167949dbacebde30f74a288c84d19927/src/pages/mail_sending_options_test_message.html

That will stop the above error from happening.

**Comment by justingit** [comment]
> I really like version 10.

Awesome!
