### ISSUE TITLE
error migrating dada

### ISSUE THREAD

**Issue by therealteenidol** [justingit/dada-mail#597]
i have some problems migrating my dada files from one server to another. i  have a conterporary version, so i moved /.dada_files/ to root  and dada folder on cgi-bin.

Then i changed the config files with the new directories.

but i cannot acces to the program, it shows an error, and if i look into de errors.log it says: 
couldn't tie /var/www/vhosts/creaccion.org/.dada_files/.lists/mj-prensa for reading: No such file or directory; If your server recently upgraded software or moved 
mail.cgi: 			your lists to a different server, you may need to restore your list settings. Visit http://creaccion.org/cgi-bin/dada/mail.cgi?f=restore_lists  at /DADA/Template/Widgets.pm line 389 

but i have the files on the folder, so whats the problem (the dir names are wrote good cause the log is updated)

please could you help me? the url is http://creaccion.org/cgi-bin/dada/mail.cgi/

i also have this error on server log:
Premature end of script headers: bridge.cgi

**Comment by justingit** [comment]
Closing this, as this is not an issue report, this is a support request.
