### ISSUE TITLE
Web Services API Issue

### ISSUE THREAD

**Issue by jgodish06** [justingit/dada-mail#601]
Tried using the WS API with a small test to send a mailing.  Took the code from your example.  Keep getting this error.   { "status" : 0, "errors" : { "invalid_digest" : 1 } } 1 

[sendDadaphp.txt](https://github.com/justingit/dada-mail/files/551492/sendDadaphp.txt)

**Comment by justingit** [comment]
Please don't dupe a closed issue. This isn't the a forum to get trouble shooting help.
