### ISSUE TITLE
Filenames in attachments are not properly encoded

### ISSUE THREAD

**Issue by luism566** [justingit/dada-mail#602]
I have a problem with the characters in Spanish ñ, Ñ, space=%20, accents (á-Á-ú-Ú.....).

Example : 
File attachment:    ÑÑÑ AAÁ.txt
Display  file           %C3%91%C3%91%C3%91%20AA%C3%81.txt
File received :        ÑÑÑ%20AAÁ.txt

 how can I solve that?
 I can set characters set in UTF-8.

where?.

Thank

**Comment by justingit** [comment]
Thanks for this report! It does seem as if filenames are not properly encoded when attached to an email message. I will release a bugfix release of Dada Mail in the future to fix this.

**Comment by justingit** [comment]
This looks and works much better, 

![untitled 2](https://cloud.githubusercontent.com/assets/39739/21208123/5892d84a-c229-11e6-814d-aa3338e9879c.jpg)
![mass_mailing_ _send_a_message_-_justin_s_test_list_-_pro_dada_-_2016-12-14_18 12 44](https://cloud.githubusercontent.com/assets/39739/21208124/5893ed98-c229-11e6-9866-ca20487a716a.png)
