### ISSUE TITLE
Problem: dadamail does not work with google apps domain

### ISSUE THREAD

**Issue by raffaelepaparella** [justingit/dada-mail#607]
Hi,

I have dada mail 10.0.1
I have free google apps domain.
My server mail is google.
I add this code "v=spf1 include:_spf.google.com ip4:72.34.36.132 ~all" into txt host
It does not work sending newsletters, email sending tests on all email google apps domain.
How can I fix the problem?
Thank you

raffaele

**Comment by justingit** [comment]
Here are the requirements to run Dada Mail. 

http://dadamailproject.com/d/requirements.pod.html

We don't suggest using Google Mail for Domains, as the limits are so low, that running a mailing list is somewhat unrealistic. 

http://dadamailproject.com/d/FAQ-email_sending.pod.html#Dada-Mail-and-Google-Apps-for-Domains

I'm not really seeing an issue being presented, just confusion. Closing
