### ISSUE TITLE
"From" header broken after v10

### ISSUE THREAD

**Issue by luisbarona** [justingit/dada-mail#608]
Hi, before v10 the "from" header was displayed as "list_name <list_email>" but now it is displayed as "list_email", affecting the appareance of the messages sent by the platform.
I've checked all the settings options in v10 and I think i'm not missing any field empty to not display this correctly, if i'm missing something please let me know.

Thanks.

**Comment by justingit** [comment]
Thanks for telling me about this issue - I'm closing, as it has been fixed in the latest version of Dada Mail (v10.2.0), cheers,
