### ISSUE TITLE
Address Verification Error

### ISSUE THREAD

**Issue by DJWardell** [justingit/dada-mail#609]
My newly installed Dada Mail application returns a non-descript "server problem" whenever attempting to verify an email address--as part of the new subscriber process. the application error log has no information (empty). Current (downloaded) version of the application

This, by the way, is the **same error** returned by the Profile Creation process at **dadamailproject.com**.

Suggestions for troubleshooting or another resolution would be greatly appreciated. the screen shot from dadamailproject.com is attached, for reference.
![dada error](https://cloud.githubusercontent.com/assets/17709254/20391186/42179de2-aca0-11e6-840f-91881aa12b06.PNG)

Many thanks.

**Comment by justingit** [comment]
It's nondescript, so not to leak sensitive information to people via a person's browser. You'll have to look in the error log itself, to see what the actual cause of the error is, 

	http://dadamailproject.com/d/FAQ-errors.pod.html#In-Browser-Error-Messages

**Comment by DJWardell** [comment]
Hi Justin,

There is no error log--none was created in the log directory, as specified in config, not is it viewable in the application log viewer. 

The fact that your installation displays the same error under similar conditions makes me think there may be a big.

In any event, I'd appreciate troubleshooting advice where there is no error log.

Many thanks. 

Sent from David Wardell's mobile. Please excuse any typos.

David Wardell
1.757.561.0582
david@wardell.org
Skype: techreality

**Comment by babalou** [comment]
Hi,

Hi Justin,

I have exactly the same issue with Dadamail 10.1.0 on my server (Apache 2.4.23 / PHP 5.5.38 / MySQL 5.6.33).

If I try to subscribe to a list using a HTML subscription form (minimal or full), I have the same error message : "Yikes! App/Server Problem! We apologize, but the server encountered a problem when attempting to complete its task".

If I try to subscribe to a list using the default "Subscribe to a Mailing List" page, I have another error message : "Blocked. Your email address or location has been blocked from using this app."

When I look the error logs, the errors messages are :
Can't use string ("") as a HASH ref while "strict refs" in use at /home/admin05/public_html/cgi-bin/dada//DADA/App.pm line 9477.
IP Address: XXX.XXX.XXX.XXX flagged for suspicious activity in, suspicious_activity_by_ip() at /DADA/MailingList/Subscriber/Validate.pm line 551.

(XXX.XXX.XXX.XXX is the IP address I used to make the subscription test).

Do you have a explanation for this issue ?

**Comment by justingit** [comment]
> If I try to subscribe to a list using the default "Subscribe to a Mailing List" page, I have another 
> error message : "Blocked. Your email address or location has been blocked from using this app."

When testing, you probably want to turn the 


http://blog.dadamailproject.com/2016/08/02/dada-mails-subscription-abuse-prevention-systems/

**Comment by babalou** [comment]
Thanks Justin !

I disabled the "Enable Suspicious IP Address Activity Protection" option and now, I can subscribe to all the lists without any problems.

By the way, is there a way to enable "Enable Suspicious IP Address Activity Protection" and also create a white IP addresses list (subscriptions from the IP addresses in this list will be always accepted) ?

**Comment by justingit** [comment]
> By the way, is there a way to enable "Enable Suspicious IP Address Activity Protection" and also create a white IP addresses list (subscriptions from the IP addresses in this list will be always accepted) ?

No.

**Comment by babalou** [comment]
Okay, I understand.

A white list for the IP Address Activity Protection would be a useful feature for a future version of DM (ex.: for companies who have a global fix IP and make several subscription tests from this IP).
