### ISSUE TITLE
Encoding Issues with HTML Message Body in Send a Message screen

### ISSUE THREAD

**Issue by babalou** [justingit/dada-mail#610]
Hi Justin,

I upgraded Dadamail Pro from 9.6.0 to 10.1.0 on my server (Apache 2.4.23 / PHP 5.5.38 / MySQL 5.6.33 / Perl 5.10.1).

The sending advanced options are : 
- Default Character Set : UTF8
- Default Plain Text Message Encoding : quoted-printable
- Default HTML Message Encoding : quoted-printable

I'm using DM Pro to send newsletters both in Japanese and French. With those sending advanced options, I didn't have any encoding issues with DM Pro 9.6.0. Since the upgrade to 10.1.0, HTML (and TEXT also) emails display strange characters when :
- the contents is (for ex.) in Japanese.
- the content is written inside the DM HTML editor.

For ex., I put "テストです。" (Japanese text) as HTML content, but when I lunch the preview (or send a test message), "テストです。" becomes "ãƒ†ã‚¹ãƒˆã§ã™ã€‚".

When I use "Grab content from a URL" with an external HTML file (using the same content), there's no encoding issues.

How can I solve the encoding issue withe the DM HTML editor ?

**Comment by justingit** [comment]
I can recreate the problem, thank you for the report. I will update this issue when I find out more.

**Comment by justingit** [comment]
Thanks for your patience! 
I think I'm coming close to fixing this issue, 

![mass_mailing_ _send_a_message_-_justin_s_test_list_-_pro_dada_-_2016-12-12_17 09 08](https://cloud.githubusercontent.com/assets/39739/21122148/c2e30866-c08d-11e6-8e98-3d85df8635c2.png)
