### ISSUE TITLE
mailing puts list name in from header

### ISSUE THREAD

**Issue by gizzyman** [justingit/dada-mail#617]
In version 10 it seems that in the "from header" dada is putting the list name instead of the senders name or email address (which ever is used), I cant see any place to change this to a name so I had to change list name to the name I want in the from header.

**Comment by justingit** [comment]
Can you give an example (header source) 

This is on a discussion list?

**Comment by gizzyman** [comment]
without changing any setting in mailer or dada, shows difference in 10 beta and 10.2, the from now shows from the list name instead of senders name.

from header dada 10.2
Received: from mail.vcomm.net ([95.211.117.198]:52158 helo=vcomm.net)
	by ns1.vcomm.net with esmtpa (Exim 4.87)
	From: "My Mailing List 2" <jeff@vcomm.net>
To: "My Mailing List 2 Subscriber" <jeff@vcomm.net>

from header dada 10 beta
Received: from mail.vcomm.net ([95.211.117.198]:56406 helo=vcomm.net)
	by ns1.vcomm.net with esmtpa (Exim 4.87)
	for jeff@vcomm.net; Fri, 28 Oct 2016 20:04:39 -0700
Date: Fri, 28 Oct 2016 20:04:39 -0700
From: jeff@vcomm.net
To: jeff@vcomm.net

**Comment by justingit** [comment]
What you're seeing in the beta is def. a bug, where the phrase is missing - this part: "My Mailing List 2"

What you're seeing in v10.2.0 is most def. the correct behavior, here.

**Comment by justingit** [comment]
The bug was in the theme templates, that come with Dada Mail. Those are in a separate project, but was documented here: 


https://github.com/justingit/dada_mail_foundation_email_templates/issues/2

**Comment by gizzyman** [comment]
thanks that fixed it, pretty cool we can just edit a few lines to fix small issues ..
