### ISSUE TITLE
Subscribe issue with certain addresses

### ISSUE THREAD

**Issue by TeamVeritas** [justingit/dada-mail#622]
I'm getting a "problems with subscribing" error.
I'm not sure at this point if it's because the address has two underscores in the username:
first_last_2014@mydomain.com or if it's that the username has too many characters, in this case 18 characters.  

The error is:
You've attempted to subscribe to a list (even when using a valid pin), without first asking for a confirmation.

Just to experiment though I tried a really long username email, which didn't work, and a two-underscore short username, which didn't work, and a short username with no underscores, no work, and a reasonably short username on a different domain with one underscore, which worked.

Server error log is complaining about "parenthesis closed with a semicolon" from modsecurity from /cgi-bin/dada/mail.cgi/_schedjRjytX7QeHypPU2B/_all/_all/_silent/

**Comment by TeamVeritas** [comment]
Update: 
I'm using the single-address invite form to generate the invite.
I tried a fairly simple address like first_last@mydomain.com
I'm getting two "invite" messages to the subject address.
I tried the "click here to join" in one email - it failed.
I tried the "click here to join" in the other email - it succeeded.
The links for the "click here" buttons are different for the two invite emails.

**Comment by TeamVeritas** [comment]
This is DadaMail 10.2.1 Stable 12/06/16 running on CentOS on a virtual private server, with WHM/Cpanel

**Comment by justingit** [comment]
>  I'm using the single-address invite form to generate the invite.

What's this? I'm not familiar with what you're using . It sounds like you're using a tool, outside of Dada Mail (that would lead me to believe there's a bug in this third party tool, and not in Dada Mail)

**Comment by TeamVeritas** [comment]
Thanks for replying Justingit!

No, it's standard Dada, and actually it's been part of the Invite/Subscribe/Add for quite a while.  

Almost-current version (10.2.1):  When logged into the dashboard for a mailing list, pull down the membership menu, then pick invite/subscribe/add.  On that page, there are three tabs, with the default being "Subscribers".  On the Subscribers tab, the first form is upload addresses as a csv.  A bit under that is a paste addresses form for adding/inviting several addresses at once.  Scroll down a bit further and you get the "Invite/Subscribe Just One Address:" form.  It's a dynamically generated form based on the defined profile fields.

**Comment by justingit** [comment]
Maybe something else is at play? Have you chceked the error log? Testing this locally, it seems to function just fine for me, 

![1](https://cloud.githubusercontent.com/assets/39739/21366203/eea2abae-c6b5-11e6-829a-6323f53bc0ad.jpg)

![untitled](https://cloud.githubusercontent.com/assets/39739/21366236/0f76a33a-c6b6-11e6-9e32-cf3504d8878e.jpg)

**Comment by justingit** [comment]
> I tried a fairly simple address like first_last@mydomain.com
> I'm getting two "invite" messages to the subject address.
> I tried the "click here to join" in one email - it failed.

I can get this to fail, but only if I try it on the copy sent to the list owner - is that perchance what you're doing, here?

**Comment by TeamVeritas** [comment]
Maybe that’s what’s happening.  I can’t tell if the invite is going to the subscriber or the list owner, so I don’t know which one to respond to.  Maybe the “bug” is that the copy sent to the list owner needs to be identified as such in the email or subject line?

Thanks!

**Comment by justingit** [comment]
Yeah, it's a confusing behavior for sure. I branched out that into it's own issue (#624), and changed the behavior of the app so the list owner doesn't receive a copy of the list invite. This change is in the latest release (v10.2.4)
