### ISSUE TITLE
Resend Confirmation Email: Fails if email contains "+" (character is stripped from address).

### ISSUE THREAD

**Issue by CosmicPuppy** [justingit/dada-mail#633]
The "+" plus sign is now frequently used in email addresses, because GMail allows it to be an automatic infinite ***alias*** to the user's base email. This is *particularly* common for email list subscriptions because subscribers want to be able to trace where sudden junk mail may have originated from and/or apply an inbox filter.

e.g., "`me+1@gmail.com`", "`me+mykid@gmail.com`", etc., all arrive at mailbox "`me@gmail.com`" (but with their sendto address retained so that filtering rules can be applied).

I have encountered, I think, *2 or more places* in Dada Mail v10.3.2 where "+" character is not handled and either results in an error or possibly ignored entry.

**I am only reporting one reproducible case at this moment:**

- On the Unconfirmed Emails membership list; pressing the "resend confirmation button" errors out:
e.g., unconfirmed email = `me+1234@gmail.com`
Error log:
```
email, 'me 1234@gmail.com' passed in, -email is not valid, type: sub_confirm_list at /home/actiontiles/domains/mlist.actiontiles.com/public_html/dada/DADA/MailingList/Subscribers.pm line 277.`
```

*Thank-you.*

**Comment by justingit** [comment]
Pretty stellar issue report, thank you!

**Comment by CosmicPuppy** [comment]
*My pleasure to be as helpful as possible, since it might expedite a resolution! Feel free to ask for details or assistance anytime.*

Great software, and nothing is bug free... but some bugs are harder to workaround than others. Not sure how critical this particular scenario is, but if it turns out to be critical or spills over, then I'll need to hack in a quick fix. I have a couple other issues, but ought to ZenDesk them to you once I subscribe. Cheers. ...Terry.

**Comment by justingit** [comment]
CosmicPuppy, please do let me know other instances you're finding this problem. I've found a few, myself.
