### ISSUE TITLE
multiple subscribe

### ISSUE THREAD

**Issue by DavidGwydion** [justingit/dada-mail#635]
10.3.3: If I subscribe to multiple lists, the first one succeeds, but all the others get captcha_challenge_failed.

Also, the heading says: Subscribe/Unsubscribe to Multiple Lists, but there is only a subscribe button.

I have disabled this on my lists for now.

**Comment by DavidGwydion** [comment]
My bad. I had 10.3.2. It is fixed in 10.3.3

**Comment by justingit** [comment]
Yup, looks like a dupe of #636 

I appreciate the report, nonetheless.
