### ISSUE TITLE
Mailing List Password Reset Broken

### ISSUE THREAD

**Issue by TeamVeritas** [justingit/dada-mail#640]
If I use the link at login - after the root password didn't work - to change the list password, the email that gets sent bounces with a malformed address:

A message that you sent contained one or more recipient addresses that were incorrectly constructed:

  "" <>: missing or malformed local part

This address has been ignored. There were no other addresses in your message, and so no attempt at delivery was possible.

**Comment by justingit** [comment]
Thank you for the report - there seems to be multiple problems with the List Password Reset functionality,
