### ISSUE TITLE
Mail says it is sent, but it does not send

### ISSUE THREAD

**Issue by cmghome** [justingit/dada-mail#644]
My Dadamail has been working great since you installed it until two weeks ago.  All of a sudden, my mailings do not send.  I create the message attempt to send it, wither a test message to myself, or directly to a mass mailing.  I get the message that it has been sent, or the mailing has successfully completed.  Tracking says it has been sent.  None of my recipients get the email.  If I send it to myself as a test message, I am not getting the email.  Any thoughts?

**Comment by justingit** [comment]
Please email me directly and include the URL to your Pro Dada installation
