### ISSUE TITLE
No profile fields data when viewed in 'Unconfirmed Subscribers'

### ISSUE THREAD

**Issue by Nivgit** [justingit/dada-mail#646]
When someone subscribes, data in the profile fields stays empty when viewed in the screen 'Unconfirmed Subscribers'.

Two things can happen:
1. When the unconfirmed subscriber completes the subscription, the profile fields are correctly filled in. The data is preserved.
2. When  re-sending a confirmation email, the data in the profile fields is empty/lost.

This error occurred in my own installation (10.3.2 Stable) and in the Demo Dada Mail (10.3.4 Stable).

**Comment by justingit** [comment]
Def. can recreate this, thank you for the report and sorry for taking so long in checking this out. I'll see what I can't do to make this a bit better working.

**Comment by justingit** [comment]
(note for myself): profile field data is saved, but in a field with the col. "email" that doesn't match the address. So, instead of the email address, "test@example.com", it saved in, "*test@example.com" 

Any way to grab the "unconfirmed" row?
