### ISSUE TITLE
Recurring schedules don't work (single scheds do)

### ISSUE THREAD

**Issue by haensli1** [justingit/dada-mail#647]
A scheduled mass mailing works as desired, when I set it up as a single schedule. This proves that the cronjob is configured correctly.
A recurring mass mailing never shows up in the monitor and never gets send.
Required CPAN modules have been installed by the web hoster.

Any ideas?

**Comment by haensli1** [comment]
This is what is shown when accessing http://mydomain.de/dada/mail.cgi/_sched72CFEE41C46CCCEC/_all/_all/


Shortly before scheduled time:

Running Schedules for, test (test)
------------------------------------------------------------------------
Current Server Time:              Mon Apr  3 15:10:08 2017
Scheduled Mass Mailings Last Ran: Mon Apr  3 15:08:07 2017 (2 minutes, 1 second ago)
* 1 Schedule(s)
	* Subject: 
	* Schedule is Activated!
	* This is a *Recurring* mass mailing,
			between: 2017-04-03 and 2017-04-10
			on: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday, 
			at: 15:11:00
	* Schedule runs at: Mon Apr  3 15:11:00 2017
		(52 seconds from now)
	* Schedule runs at: Tue Apr  4 15:11:00 2017
		(1 day, 52 seconds from now)
	* Schedule runs at: Wed Apr  5 15:11:00 2017
		(2 days, 52 seconds from now)
	* Schedule runs at: Thu Apr  6 15:11:00 2017
		(3 days, 52 seconds from now)
	* Schedule runs at: Fri Apr  7 15:11:00 2017
		(4 days, 52 seconds from now)
	* Schedule runs at: Sat Apr  8 15:11:00 2017
		(5 days, 52 seconds from now)
	* Schedule runs at: Sun Apr  9 15:11:00 2017
		(6 days, 52 seconds from now)

		
		
Shortly after:

Running Schedules for, test (test)
------------------------------------------------------------------------
Current Server Time:              Mon Apr  3 15:11:16 2017
Scheduled Mass Mailings Last Ran: Mon Apr  3 15:10:08 2017 (1 minute, 8 seconds ago)
* 1 Schedule(s)
	* Subject: 
	* Schedule is Activated!
	* This is a *Recurring* mass mailing,
			between: 2017-04-03 and 2017-04-10
			on: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday, 
			at: 15:11:00
	* Schedule runs at: Mon Apr  3 15:11:00 2017
	* Checking message content...
		* Primary Content same as previously sent scheduled mass mailing.
		* Skipping sending scheduled mass mailing.

	* Schedule runs at: Tue Apr  4 15:11:00 2017
		(23 hours, 59 minutes, 44 seconds from now)
	* Schedule runs at: Wed Apr  5 15:11:00 2017
		(1 day, 23 hours, 59 minutes, 44 seconds from now)
	* Schedule runs at: Thu Apr  6 15:11:00 2017
		(2 days, 23 hours, 59 minutes, 44 seconds from now)
	* Schedule runs at: Fri Apr  7 15:11:00 2017
		(3 days, 23 hours, 59 minutes, 44 seconds from now)
	* Schedule runs at: Sat Apr  8 15:11:00 2017
		(4 days, 23 hours, 59 minutes, 44 seconds from now)
	* Schedule runs at: Sun Apr  9 15:11:00 2017
		(5 days, 23 hours, 59 minutes, 44 seconds from now)

In fact a mail was not sent!

**Comment by justingit** [comment]
This part looks important: 

```
Checking message content...

Primary Content same as previously sent scheduled mass mailing.
Skipping sending scheduled mass mailing.

```

Do you have the option to NOT send a message, if the content is the same as last?

**Comment by haensli1** [comment]
That might be possible. I don't know. Where can I find this option?

**Comment by justingit** [comment]
In Dada Mail, do you see an option labeled, 

**Only send the next scheduled mass mailing, if the primary content differs from the previous scheduled mass mailing** 

and is it checked? 

![image](https://cloud.githubusercontent.com/assets/39739/24625538/8d7d1c8e-186c-11e7-88de-87e4997a06f7.png)

**Comment by haensli1** [comment]
No, I don't see that option. But I remember there was such an option in previous versions. I have the latest version (10.5.0) installed.

**Comment by haensli1** [comment]
![image](https://cloud.githubusercontent.com/assets/26660465/24630473/2a366242-18bd-11e7-921e-f391714b215b.png)

**Comment by justingit** [comment]
Seems like the option is available in the Send a Webpage screen, but not in the Send a Message screen (so workaround for now: use the Send a Webpage screen). 

What's the scenario, where you want to continue to send the same messages to your subscribers on a schedule?

**Comment by haensli1** [comment]
I'm using the scheduled mailings as a recurring reminder for the subscribers to work on sth. every week. There is always the same text and the same link (to the spreadsheet to work on) in the message.

**Comment by justingit** [comment]
OK, that makes sense. In the next version, I'll have the option to enable/disable that setting available. Until then, you could use the Send a Webpage screen to create your message - there is an option just to write the message out, rather than giving the app a URL to send, 

Cheers,

**Comment by haensli1** [comment]
Great. Thanks a lot!

Cheers
