### ISSUE TITLE
List Shortname is always added to subject

### ISSUE THREAD

**Issue by holzhannes** [justingit/dada-mail#648]
Even if the short name placeholder is removed in the subject of a message `<!-- tmpl_var list_settings.list_name -->` the message will be sent including the shortname of the list.

Version: 10.5.0 Stable 03/22/17

**Comment by justingit** [comment]
Do you have Bridge enabled? There is an option in Bridge that appends the list shortname to the Subject.

**Comment by holzhannes** [comment]
> Do you have Bridge enabled? There is an option in Bridge that appends the list shortname to the Subject.

This was the reason why the shortname was added. Thank you! Would be nice if there at the bridge settings would be an option to allow message from the webpage to be sent without shortname. Maybe it would help to change the text from `Prefix message subjects with the:` to `Always prefix message subjects with the:` ;-)
