### ISSUE TITLE
Umlauts (ü, ö, ä, ß) in Email Themes are escaped to \xFC \xF6 \xE4 \xDF

### ISSUE THREAD

**Issue by holzhannes** [justingit/dada-mail#649]
In case you translate the mail themes in `dada_mail_support_files > themes > email` and you add Umlauts (ü, ö, ä, ß) in the plaintext mails they will be escaped to \xFC \xF6 \xE4 \xDF.

Version: 10.5.0 Stable 03/22/17

**Comment by justingit** [comment]
OK, I can recreate this. Strange!

**Comment by holzhannes** [comment]
I tested this but, the problem is still there.

**Comment by justingit** [comment]
OK, thanks for try it - I'm sorry it didn't work. I'll give it some more of my attention to see what I can come up with,

**Comment by holzhannes** [comment]
I tested commit [be81f89](https://github.com/justingit/dada-mail/commit/be81f89f85efc6e523d67f1a09df231a3a8227ed), but it is not solving the Issue it is making many more issues. Mails will have no subjects and for example subscribing a subscribed mail will cause an Error and the you_are_already_subscribed_message won´t get sent.

**Comment by justingit** [comment]
I think the latest commit is working a bit better, now (if you would like to try it) 

![untitled](https://cloud.githubusercontent.com/assets/39739/24623972/8520fc86-1867-11e7-95a4-9a6a224320af.png)

**Comment by holzhannes** [comment]
OK I tested commit https://github.com/justingit/dada-mail/commit/317d9fefc2a02d08b824130bde177859eab37b5a and it is **working half way**. In the body of the mail the encoding is OK 😄 , but in the header (subject) it is still somehow broken (see the image, from thunderbird but in Apple Mail the same) 
![mail](https://cloud.githubusercontent.com/assets/4320619/24625158/6b4c719a-18ae-11e7-999e-11d4c3beba18.png)

Subject as it should be: `Test ä ö ü List Abonnentbestätigung für Mailing-Liste` where `Test ä ö ü List` is the list_name
In the source of the mail from Dada the subject is:
```
Subject: [jonews] Test =?UTF-8?Q?=C3=A4_=C3=B6_=C3=BC?= List =?UTF-8?Q?Abonnentbest=EF=BF=BDtigung_f=EF=BF=BDr?= Mailing-Liste
```
If I send myself an email with the same subject the source is:
```
Subject: =?utf-8?Q?=5Bjonews=5D_Test_=C3=A4_=C3=B6_=C3=BC_List_Abonnentbes?==?utf-8?Q?t=C3=A4tigung_f=C3=BCr_Mailing-Liste?=
```
A quick look on both subjects seems to state no issues compared to: [RFC 2047 Syntax of encoded-words](http://tools.ietf.org/html/rfc2047#section-2), but I check all these DadaMails with different E-Mail Clients on different operating systems (MacOS, Android, iOS, Windows) and every where I see the replacement character �. 🤔

**Comment by justingit** [comment]
Can you attach the, confirmation_message.txt file you're using for your tests?

**Comment by holzhannes** [comment]
Yes of course here it is: 
```
---
to_phrase: <!-- tmpl_var list_settings.list_name --> Abonnent
from_phrase: <!-- tmpl_var list_settings.list_name --> Inhaber
preheader: Die Bestätigung ist nur ein Klick entfernt!
subject: <!-- tmpl_var list_settings.list_name --> Abonnentbestätigung für Mailing-Liste
---

<!-- tmpl_var email.preheader -->

Bereit zum Beitritt zu: <!-- tmpl_var list_settings.list_name -->?

Klicken Sie hier, um Ihr Abonnement zu bestätigen:
<!-- tmpl_var list_confirm_subscribe_link -->

<!-- tmpl_var list_settings.info -->

Ihre Privatsphäre ist uns wichtig:

Diese E-Mail ist teil der doppelten Bestätigung system and was sent to protect the 
privacy of the owner of this email address (that's you!). doppelten Bestätigung 
confirmation helps guarantee that only the owner
einer E-Mail-Adresse für eine Mailing-Liste anmelden kann.

Datenschutzerklärung für: <!-- tmpl_var list_settings.list_name -->:
<!-- tmpl_var list_settings.privacy_policy -->
```

[confirmation_message.txt](https://github.com/justingit/dada-mail/files/891275/confirmation_message.txt)

**Comment by justingit** [comment]
I actually think the issue is fixed, but you bring up another, separate issue: 

I noticed that you have the list short name in brackets at the beginning of your subject. That's an option in Bridge. If I enable that myself, I see the same problem: 

![image](https://cloud.githubusercontent.com/assets/39739/24632126/3f40ee7e-1880-11e7-9530-92f4a73d8342.png)


But if I disable it, the problem goes away. Can you double check this, by disabling this option yourself, and seeing if the encoding is correct?

**Comment by holzhannes** [comment]
I double checked this and can confirm, if the bridge is disabled the encoding in the subject is OK.

**Comment by justingit** [comment]
Thanks. I'm going to call this issue, "closed" and open up a new issue for the other problem,
