### ISSUE TITLE
Some values like list name are not stored correctly in the MySQL DB as UTF-8

### ISSUE THREAD

**Issue by holzhannes** [justingit/dada-mail#651]
While investigating issue #649 I noticed the list name (and other fields on the same settings page) are not saved with UTF-8 encoding inside the MySQL-Database: Just see the image: 
![mysql](https://cloud.githubusercontent.com/assets/4320619/24629504/806744c8-18b9-11e7-8764-d43bed018bde.png)

If the characters would be saved correctly it would look like this: 
![shouldbe](https://cloud.githubusercontent.com/assets/4320619/24629815/af9e0f5a-18ba-11e7-8bb7-3b688f5ab7fc.png)

Version: 10.5.0 Stable 03/22/17
MySQL: 5.5.54, Perl v5.18.2
Ubuntu 14.04.5 LTS

**Comment by justingit** [comment]
Can you verify this by looking a little more directly into the MySQL data? It could be whatever you're using to view the data that's actually having the encoding problem. For example, it does seem to work for me:  

<img width="647" alt="image" src="https://cloud.githubusercontent.com/assets/39739/24632361/16f5f97c-1881-11e7-8961-092d5256881b.png">

![untitled 2](https://cloud.githubusercontent.com/assets/39739/24632429/4ddd115a-1881-11e7-8c43-127e45697a03.png)

**Comment by holzhannes** [comment]
Heres a screenshot of the CLI and the settings webpage.

![cli-mysql](https://cloud.githubusercontent.com/assets/4320619/24633368/75e0f0e4-18c8-11e7-9be9-1efab9fc95f1.png)
![listview](https://cloud.githubusercontent.com/assets/4320619/24633409/a6da7bde-18c8-11e7-8a5c-7406c70a2acd.png)

**Comment by holzhannes** [comment]
I tested this on another fresh and clean server Installation and there it is the same:
CentOS Linux 7.3.1611
MySQL 5.5.52
Perl v5.16.3

**Comment by justingit** [comment]
I would need instructions on how to recreate the problem locally. Without that, I won't be able to debug this. 

(That is why I talked to you about these issues privately, and gave you my opinion that I may need to look at this personally.)

**Comment by holzhannes** [comment]
> (That is why I talked to you about these issues privately, and gave you my opinion that I may need to look at this personally.)

I respect this! With this issue report I was trying to pick out a specific part of the failure which should be easy to recreate.

> I would need instructions on how to recreate the problem locally. Without that, I won't be able to debug this.

OK I will do my value best, or we just do it the other way around. Which environment are you using for Testing at the moment? OS, MySQL and Perl version then I will first try to run it on my local computer.

**Comment by holzhannes** [comment]
I am running DadaMail with FastCGI so I will first double check this documentation [FastCGI Support](http://dadamailproject.com/support/documentation-10_5_0/features-fastcgi.pod.html) maybe this is part of the issue.

**Comment by holzhannes** [comment]
> I am running DadaMail with FastCGI so I will first double check this documentation FastCGI Support maybe this is part of the issue.

Could not find anything 🤕 

**About my Installation(s)**
- all my DadaMail installations are set up as vHost through the Plesk 17.0 or 17.5 Admin-Panel 
- Perl, CGI and FastCGI is enabled and served through Apache 2.4 or Ngnix
- I upload `.zip` and `uncompress_dada.cgi` change it to 755 and run it
- afterwards I run the installation script and set up the MySQL DB
- Installation ist stating: FastCGI Support is enabled and I install with CGI selected.
- In the next Step everything is finishing with Success and I am renaming and changing rights of Installer script.
- MySQL-DB is set to UTF-8
- all DadaTables have a collation of `utf-8_bin` or `utf-8` like stated [here](http://dadamailproject.com/support/documentation-8_4_0/features-UTF-8.pod.html#Changing-the-character-set-of-tables)

Here is an extremely extensively Stackoverflow Post about Perl & UTF-8: [Why does modern Perl avoid UTF-8 by default?](http://stackoverflow.com/questions/6162484/why-does-modern-perl-avoid-utf-8-by-default?answertab=votes#tab-top)

**Comment by holzhannes** [comment]
Maybe my Issue is connected to this one fixed in ([DBD::mysql 4.041_1](https://github.com/perl5-dbi/DBD-mysql/blob/master/Changes)) I am running DBD::mysql 4.042 🤔 

> 2016-12-12 Patrick Galbraith, Michiel Beijen, DBI/DBD community (4.041_1)
Unicode fixes: when using mysql_enable_utf8 or mysql_enable_utf8mb4,
  previous versions of DBD::mysql did not properly encode input statements
  to UTF-8 and retrieved columns were always UTF-8 decoded regardless of the
  column charset.
  Fix by Pali Rohár.
  Reported and feedback on fix by Marc Lehmann
  (https://rt.cpan.org/Public/Bug/Display.html?id=87428)
  Also, the UTF-8 flag was not set for decoded data:
  (https://rt.cpan.org/Public/Bug/Display.html?id=53130)
