### ISSUE TITLE
Bridge: Appending List  Name/List Shortname to Subject can break encoding of Subject

### ISSUE THREAD

**Issue by justingit** [justingit/dada-mail#652]
As found out in issue #649, if this option

 **Prefix message subjects with the:** 

is enabled, the Subject may also be encoded incorrectly.

**Comment by jan-battenfeld** [comment]
Problem exists (again?) in Dada-Mail 10.8.2 Stable.
![bildschirmfoto dadamail](https://user-images.githubusercontent.com/3909385/39097337-4096fe08-465b-11e8-8cfa-331c3fcf5750.png)

**Comment by justingit** [comment]
Can you post the source of the Subject: header from the original message you tried to send? 

-- 

Justin J: Lead Dadaist. 
url:         http://dadamailproject.com
email:    justin@dadamailproject.com
twitter:  @dadamail
skype:   leaddadaist

Dada Mail Announcements: 
http://dadamailproject.com/cgi-bin/dada/mail.cgi/list/dada_announce/
