### ISSUE TITLE
Recurring scheduled webpages get sent far too late

### ISSUE THREAD

**Issue by haensli1** [justingit/dada-mail#654]
Schedule:
![image](https://cloud.githubusercontent.com/assets/26660465/24719109/d26715e8-1a38-11e7-81a2-93c148efebfe.png)

![image](https://cloud.githubusercontent.com/assets/26660465/24719085/b79b7d62-1a38-11e7-933d-39566de59628.png)

Tracker:
![image](https://cloud.githubusercontent.com/assets/26660465/24719127/e7da2136-1a38-11e7-8408-181c827ebf29.png)

**Comment by haensli1** [comment]
The Tuesday mailing was in time:
![image](https://cloud.githubusercontent.com/assets/26660465/24719825/68944502-1a3b-11e7-94cd-4bfb08dbe78c.png)

**Comment by justingit** [comment]
cronjob setup correctly?

**Comment by haensli1** [comment]
Yes. And as far as I understand the functionality, the display of the tracker is independent of the cronjob, right?
But anyways, the cronjob runs every minute this command: /usr/bin/curl --user-agent "Mozilla/5.0 (compatible;)" --silent --get --url http://mydomain.de/dada/mail.cgi/_sched72CFEE41C46CCCEC/_all/_all/_silent/

**Comment by justingit** [comment]
Were there any other messages that were being sent out at the time this scheduled message was supposed to go out ?

Are there any error logs that pertain to this timeframe? 

This is shaping up as more of a support request, rather than filing a bug report - I don't have a way to recreate this problem...

**Comment by haensli1** [comment]
No other messages were sent out.
The usage log shows:
[Wed Apr  5 19:40:34 2017]    squash    84.155.178.63    Mass Mailing Starting    Message-Id: <20170405194033.52539368@t-online.de>    Subject:     Started: Wed Apr  5 19:40:34 2017    Mailing Amount: 9
[Wed Apr  5 19:41:46 2017]    squash    84.155.178.63    Mass Mailing Completed    Message-Id: <20170405194033.52539368@t-online.de>    Subject:     Started: Wed Apr  5 19:40:34 2017    Finished: Wed Apr  5 19:41:46 2017    Mailing Amount: 9

The error log:
[Wed Apr  5 11:07:47 2017] mail.cgi: running scheduled jobs at teardown @ Wed Apr  5 11:07:47 2017 at /home/www/dada/DADA/App.pm line 361.
running scheduled jobs at teardown @ Wed Apr  5 19:40:31 2017 at /home/www/dada/DADA/App.pm line 361.
[Wed Apr  5 19:40:33 2017] mail.cgi: cannot use HTML::Packer:Can't locate HTML/Packer.pm in @INC (you may need to install the HTML::Packer module) (@INC contains... at DADA/App/FormatMessages/Filters/HTMLMinifier.pm line 87.
[Wed Apr  5 19:40:34 2017] mail.cgi: cannot use HTML::Packer:Can't locate HTML/Packer.pm in @INC (you may need to install the HTML::Packer module) (@INC contains... at DADA/App/FormatMessages/Filters/HTMLMinifier.pm line 87.
running scheduled jobs at teardown @ Wed Apr  5 19:48:30 2017 at /home/www/dada/DADA/App.pm line 361.
running scheduled jobs at teardown @ Wed Apr  5 19:48:33 2017 at /home/www/dada/DADA/App.pm line 361.
[Wed Apr  5 19:48:33 2017] mail.cgi: running scheduled jobs at teardown @ Wed Apr  5 19:48:33 2017 at /home/www/dada/DADA/App.pm line 361.
running scheduled jobs at teardown @ Wed Apr  5 19:48:33 2017 at /home/www/dada/DADA/App.pm line 361.
[Wed Apr  5 19:48:35 2017] mail.cgi: PID: 32382 Semaphore does not exist to delete at, '/home/.dada_files/.tmp/_scheduled_tasks.lock at DADA/App/ScheduledTasks.pm line 210.
[Wed Apr  5 19:48:37 2017] mail.cgi: PID: 32394 Semaphore does not exist to delete at, '/home/.dada_files/.tmp/_scheduled_tasks.lock at DADA/App/ScheduledTasks.pm line 210.
running scheduled jobs at teardown @ Wed Apr  5 19:57:19 2017 at /home/www/dada/DADA/App.pm line 361, <CONFIG> line 1.
running scheduled jobs at teardown @ Wed Apr  5 20:05:04 2017 at /home/www/dada/DADA/App.pm line 361.
running scheduled jobs at teardown @ Wed Apr  5 20:05:51 2017 at /home/www/dada/DADA/App.pm line 361.
running scheduled jobs at teardown @ Wed Apr  5 20:15:24 2017 at /home/www/dada/DADA/App.pm line 361, <CONFIG> line 1.
[Wed Apr  5 20:15:55 2017] mail.cgi: running scheduled jobs at teardown @ Wed Apr  5 20:15:55 2017 at /home/www/dada/DADA/App.pm line 361.

My test job which runs daily was sent out in time yesterday. Maybe this was a one time "bug" on the 5th... We will see next Tuesday/Wednesday...

**Comment by haensli1** [comment]
All list get sent in time now. So I think this was a temporary malfunction. Thanks!

**Comment by justingit** [comment]
If I may ask that In the future, please abstain from using the issues tracker for support requests - there's a different system for that (Zendesk). See, 

http://dadamailproject.com/contact
