### ISSUE TITLE
"Not authorised to use filemanager" error

### ISSUE THREAD

**Issue by philmck** [justingit/dada-mail#655]
After upgrading to Dada Mail Pro 10.5.0 Stable I set it to use the new RichFilemanager, but when I tried to add an attachment to an outgoing message I got the error "You are not authorised to use filemanager" despite being successfully logged in as the root user. There was nothing in the Dada error log or the Apache error log.

It seems to be a session-related problem because I eventually solved it simply by logging out and logging in again. I don't think this is a local cache issue though because I cleared out the .tmp folder after upgrading. I can't reproduce the problem now to test it further but it happened to a customer as well as to me personally so it wasn't an isolated incident.

**Comment by justingit** [comment]
This makes a lot of sense, since RFM will need a new session cookie to be created, before authentication will work for it. That's simply done by logging ot, then in. So, nothing truly surprising to me (at least?)

**Comment by philmck** [comment]
Maybe not surprising but for me it's a waste of time and for customers who don't even know what a cookie is it's a showstopper.

I'm not just whingeing here - most Dada upgrades end up costing me so much time that in practice I avoid doing them. That's bad for security.

**Comment by justingit** [comment]
I guess what I can do is expire all the sessions in Dada Mail, when an upgrade is performed. That way, if there's anything different happening with the sessioning system (like this) it won't just cause unexpected/strange behavior.

**Comment by philmck** [comment]
Update - just upgraded to 10.7.1 Stable 10/04/17 and the problem is back, only this time logging out and deleting all temp files and using incognito mode in my browser doesn't help. Nor does rolling back to the backup version of RichFilemanager. I'm really fed up with wasting hours every time I upgrade. :-(
