### ISSUE TITLE
Indented message quotes truncated in Outlook

### ISSUE THREAD

**Issue by philmck** [justingit/dada-mail#658]
In Dada Mail Pro 10.5.0 stable, messages sent to a discussion list with the default layout "For Discussion List Messages" are not fully visible in Outlook 2016 (Office 365 desktop client), because the indentation applied to the original quoted message causes text at the right to be truncated, even if the window is resized.

I'm quite prepared to believe this is a Microsoft bug but unfortunately since it's in the latest version of Outlook used by millions of people I think it needs to be addressed. 

The message displays OK in Gmail and there's also a workaround in Outlook by clicking the "view message in browser" link.

**Comment by justingit** [comment]
Can you provide a screenshot of this?

**Comment by philmck** [comment]
Sure: 

![truncation](https://cloud.githubusercontent.com/assets/293914/24920382/e2b371f8-1ede-11e7-8fce-3fb276c26cf8.png)
