### ISSUE TITLE
List messages viewed in Gmail on Android are not responsive, or squeezed

### ISSUE THREAD

**Issue by philmck** [justingit/dada-mail#659]
Messages sent from Dada Mail Pro 10.5.0 stable using the default layout are not "responsive" when viewed in the Gmail client on an Android phone - fonts are small and it's necessary to pan and zoom or use landscape mode to read the message.

The same messages viewed in the Samsung mail client are responsive, but there is still a problem - the side margins cause the message text to be compressed into a narrow column in the middle.

I realise this is a difficult problem but I'm not seeing the same issues in other messages viewed on the same clients so a solution must be possible.

**Comment by justingit** [comment]
According to the docs on the Framework Dada Mail uses, 

https://foundation.zurb.com/emails/docs/compatibility.html

**Gmail app for Android** does have some limitations: 

> *Gmail app for Android: Works - does not recognize media queries so it will render large breakpoint.

So this may be a documented limitation of the framework.
