### ISSUE TITLE
Template and subject blank in new list

### ISSUE THREAD

**Issue by DennHRMC** [justingit/dada-mail#665]
I have pro dada mail for life. In an installation of 8.4 I just added a new list. Borrowed the config from another list. Can't see anything wrong but at first I had trouble tweaking the mailing list template and having it save. It seemed like it was but then I'd go back after other issues and it wasn't. Never seen that before.

Anyway, it did finally. But what it is sending is an email with (no subject) and the message is blank (literally, that is what it says). The message composition page shows the right thing and returns to it after the test. None of the other lists that I tested in this install have this issue, just the new one.

The template, as I modified it is essentially the same as the others and is:

`

<p style="font-family:Verdana, sans-serif; font-size: 9pt;text-align:center;margin-top:20px;";><a href="http://www.highroadmc.com" target ="_blank"><img border="0"
src="http://www.highroadmc.com/externalimages/sigilMail.jpg" alt="High Road Marketing and Communications image"/></a><br /><a style="color:#000000" href="http://www.highroadmc.com" target ="_blank">Mail List Mangement by High Road Marketing and Communication</a></p>
<table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%">
	<tbody>
		<tr>
			<td align="center" valign="top">
			<table border="0" cellpadding="0" cellspacing="0" class="container" style="width:600px;max-width:600px;margin:0 auto;" width="600">
<tr>
<td><br /><br /><p style="text-align:center; color:#000000;">
<a style="color:#000000" href="">Unsubscribe </a> or <a style="color:#000000" href="[PROGRAM_URL]/list/[list_settings.list]">update or change</a> your subscription or <a href="">
		   Forward this Message to a Friend &#187;
		  </a> </p>
</td></tr>

</table>
</td>
</tr>
</tbody>
</table>
`

Thoughts?

**Comment by DennHRMC** [comment]
Hmmm, I thought the insert code tags would leave the code, not execute it. Trying here:



<p style="font-family:Verdana, sans-serif; font-size: 9pt;text-align:center;margin-top:20px;";><a href="http://www.highroadmc.com" target ="_blank"><img border="0"
src="http://www.highroadmc.com/externalimages/sigilMail.jpg" alt="High Road Marketing and Communications image"/></a><br /><a style="color:#000000" href="http://www.highroadmc.com" target ="_blank">Mail List Mangement by High Road Marketing and Communication</a></p>
<table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%">
	<tbody>
		<tr>
			<td align="center" valign="top">
			<table border="0" cellpadding="0" cellspacing="0" class="container" style="width:600px;max-width:600px;margin:0 auto;" width="600">
<tr>
<td><br /><br /><p style="text-align:center; color:#000000;">
<a style="color:#000000" href="">Unsubscribe </a> or <a style="color:#000000" href="[PROGRAM_URL]/list/[list_settings.list]">update or change</a> your subscription or <a href="">
		   Forward this Message to a Friend &#187;
		  </a> </p>
</td></tr>

</table>
</td>
</tr>
</tbody>
</table>

**Comment by justingit** [comment]
I'm not sure if I'd be able to give much help to a version so much older than the most recent release (v10.5.2).

**Comment by DennHRMC** [comment]
OK. Never seen this before. Haven't had the time to update the installation.

**Comment by DennHRMC** [comment]
Can you think of some reason it MIGHT not pick up the info from a new list when the previous lists all work? Wild guesses are fine.... ;-)

**Comment by justingit** [comment]
I don't :(
