### ISSUE TITLE
Bridge: From header getting brocken if " " is inside the alias of mail address

### ISSUE THREAD

**Issue by holzhannes** [justingit/dada-mail#670]
I have customer who has entered his firstname lastname and middlename including ```" "``` as Alias in the E-Mail-Client. I told him to change but also I think this should not happen. ``` "Firstname Middlename Lastname" <his@email.com>``` this is breaking the from address and it will look like this:
```
From: "\\"@smtp.server.com, Firstname@smtp.server.com,
 Lastname@smtp.server.com, =?UTF-8?Q?Lastname=22?=@smtp.server.com,
 his@email.com,
 "[List_SHORTNAME]"@smtp.server.com,
 " <LIST-EMAIL@domain.com>"@smtp.server.com
```
Google Mail will receict all these Mails because of multiple from addresses.

```550-5.7.1 ... Messages with multiple addresses in From: 550 5.7.1 header are not accepted```

DadaMail Version: 10.5.3 & 10.5.4

**Comment by holzhannes** [comment]
**Update**: After testing this I could only reproduce it if the alias is also including an umlaut. You may test with: ```"First Middle Löstname"```.

**Comment by justingit** [comment]
Thanks for the report, I'll see if I can't recreate the problem,

**Comment by justingit** [comment]
I finally had time to try to recreate this problem, but wasn't able to myself - everything works correctly. Can you tell me what version of Dada Mail you are using? I'm using the latest (v10.5.4)

**Comment by holzhannes** [comment]
It is happening with all the Versions: 10.5.3, 10.5.4 and 10.5.5. Did you enter the Alias including " " in the mailclient sending the mail, this is important?
![bildschirmfoto 2017-06-19 um 17 54 38](https://user-images.githubusercontent.com/4320619/27294043-7da9918c-5518-11e7-8f72-dd3929d8395e.png)

**Comment by justingit** [comment]
So quotes "" are part of the Name of the email address?! I guess I didn't, but I guess you may also see the silliness in doing that.

**Comment by holzhannes** [comment]
> So quotes "" are part of the Name of the email address?!

Yes

> but I guess you may also see the silliness in doing that.

**I know it silly**, but there are some webmailer and/or Clients who are doing this. Therefore it should be part of DadaMails input validation to handle this "silliness" or reject to process this mails if it is not possible to handle mails with such a silly name. From my point of view this is also a security issue because it is possible to inject headers.

**Comment by justingit** [comment]
Can you provide an example of what this From: header that's causing problem looks like in the source of an email message? I'm wondering if it's already invalid. If so, trying to parse an invalid From: header isn't going to be much good.

**Comment by holzhannes** [comment]
Human readable: ```From: "First Middle Löstname" <mail@example.com>```
original header in a mail: ```From: =?utf-8?Q?=22First_Middle_L=C3=B6stname=22?= <mail@example.com>```

**Comment by justingit** [comment]
Can you provide the *exact* header? (you can anonymize the email address itself, I guess) Quotes around the phrase isn't out of the ordinary. I'm trying to figure out if there are actually embedded quotes within the phrase, and if that is causing the problem. In my tests, the From header looks like this: 

    From: =?UTF-8?B?VGjDtsO8bmRlckLDrnJkIFTDqXN0?= <test@example.com>

Works just fine. There are quotes *around* the phrase, but there aren't any embedded in the phrase.

**Comment by holzhannes** [comment]
Your header ist Base64 encoded mine Quoted Printable could not find a mail client doing it in Base64. Here are two messages with all headers, one from Apple Mail (Issue exist) one from Thunderbird (Issue does not exist).

## Issue exist

Send via Apple Mail Version 10.3 on macOS Siera 10.12.5  
```"First Middle Löstname" <mail@example.com>```  
Apple Mail seems to keep the qoutes while sending.

```
Return-Path: <mail@example.com>
X-Spam-Checker-Version: SpamAssassin 3.4.1 (2015-04-28) on server.destination.com
X-Spam-Level: 
X-Spam-Status: No, score=-1.0 required=5.0 tests=ALL_TRUSTED,TVD_SPACE_RATIO
	autolearn=ham autolearn_force=no version=3.4.1
X-Original-To: justacopy@example.com
Delivered-To: justacopy@example.com
From: =?utf-8?Q?=22First_Middle_L=C3=B6stname=22?= <mail@example.com>
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
Mime-Version: 1.0 (Mac OS X Mail 10.3 \(3273\))
Subject: TestAppleMail2
Date: Sat, 24 Jun 2017 09:50:01 +0200
X-Mailbutler-Link-Tracking-Uuid: 
Cc: justacopy@example.com
To: bridge-account@dadamailhost.com
Message-Id: <E8E73D00-7E81-48C8-9E9C-8084C4D74974@destination.com>
X-Mailer: Apple Mail (2.3273)
X-PPP-Message-ID: <149829060405.23049.2399215255295234778@server.destination.com>
X-PPP-Vhost: destination.com

Test
```

## Issue does NOT exist

Send via Thunderbird Version 45.7.1 on macOS Siera 10.12.5  
```"First Middle Löstname" <mail@example.com>```  
Thunderbird seems to remove the qoutes while sending.

```
Return-Path: <mail@example.com>
X-Spam-Checker-Version: SpamAssassin 3.4.1 (2015-04-28) on server.destination.com
X-Spam-Level: 
X-Spam-Status: No, score=-1.0 required=5.0 tests=ALL_TRUSTED,TVD_SPACE_RATIO
	autolearn=ham autolearn_force=no version=3.4.1
X-Original-To: justacopy@example.com
Delivered-To: justacopy@example.com
To: bridge-account@dadamailhost.com
Cc: justacopy@example.com
From: =?UTF-8?Q?First_Middle_L=c3=b6stname?= <mail@example.com>
Subject: TestThunderbird
Message-ID: <82d2d276-1773-baaf-cfa3-8c07f0f0a077@destination.com>
Date: Sat, 24 Jun 2017 09:51:15 +0200
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:45.0)
 Gecko/20100101 Thunderbird/45.7.1
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit
X-PPP-Message-ID: <149829067564.23269.7913412855120446198@server.destination.com>
X-PPP-Vhost: destination.com

Test
```
