### ISSUE TITLE
Problem can't attach file using RichFilemanager

### ISSUE THREAD

**Issue by nerdykit** [justingit/dada-mail#671]
I don't seem to be able to attach a file to a Dada mail message.  I'm using the latest version 10.5.4 with the RichFilemanager which is in place when I look into my dada_mail_support_files directory.  When I click the link for Select a file... it opens a window with the URL
http://www.mydomain.org/dada_mail_support_files/RichFilemanager/index.html?custom_function=SetAttachmentUrl  and I get an endless "busy" wheel and a message on screen appears briefly that reads "Unable to perform initial request to server"  upload file directory exists and is defined.  I have attached other files to other mailings using earlier versions of Dada Mail Pro.

**Comment by nerdykit** [comment]
Further... edited my config file to re-enable the old kcfinder and it worked just fine and I could send out my mailing with attachment.  So the problem is probably with RichFilemanager or it's config.

**Comment by justingit** [comment]
It's possible, for whatever reason, Rich Filemanager just doesn't work with your server environment. That *is* why there are 3 different choices for a file manager in Dada Mail. All of the choices are third party apps, so I have a lot less control on the code and its quality (unfortunately)

**Comment by nerdykit** [comment]
> On May 26, 2017, at 9:59 PM, Justin J <notifications@github.com> wrote:
> 
> It's possible, for whatever reason, Rich Filemanager just doesn't work with your server environment. That is why there are 3 different choices for a file manager in Dada Mail. All of the choices are third party apps, so I have a lot less control on the code and its quality (unfortunately)
> 
> 

I did check that I had the version of php (5.4 or newer) required for RichFilemanager.  I couldn’t find a setting for selecting the file manager on any of the menus, did I miss finding it?  To make the change, I had to edit the dada config file which could be a challenge for some users.

Kit

**Comment by justingit** [comment]
You would make the change in the installer, 

http://dadamailproject.com/d/install_dada_mail-advanced_configuration.pod.html#File-Browsers-Uploaders

This would have been how you initially selected Rich Filemanager over KCFinder.
