### ISSUE TITLE
%3C in the first tmpl_var tags regex on analytics tag

### ISSUE THREAD

**Issue by pestevao** [justingit/dada-mail#674]
Hi,

Recently when we upgrade to Pro 10.5.4 we become with an odd behaviour of tmpl_var tags.

We use some pixel image to get opens of our newsletters and wish to automate them as most as possible. So we made the tag with tmpl_var tags to capture some information. But this doesn't work well.

For example:
`(...)%2F<!-- tmpl_var date.year -->%2F<!-- tmpl_var date.padded_month -->%2F<!-- tmpl_var date.padded_day -->%2F(...)`

The first tag in our testing email become **%3C--" tmpl_var date.year -->** the other ones replace for their expected values so it ends on %2F%3C!--" tmpl_var date.year -->%2F05%2F29%2F.

It always happens with the first tag no matter which one is. If we change to or some other, it allways happends a wrong regex function on the first one.

In some other part of the body the tmpl_var are working fine.

Maybe the url encode values before the value are broking the regex? %2F = /

The full analytics tag:
`<img src="http://www.google-analytics.com/collect?v=1&tid=UA-_XXXXXX_-_XX_&t=event&ec=_XXX_&ea=_XXX_&ev=open&cn=_XXX_&cs=_XXX_&cm=email&ck=_XXX_&cc=<!-- tmpl_var date.year -->%2F<!-- tmpl_var date.padded_month -->%2F<!-- tmpl_var date.padded_day -->&dt=%2F_XXX_%2F<!-- tmpl_var date.year -->%2F<!-- tmpl_var date.padded_month -->%2F<!-- tmpl_var date.padded_day -->%2F_XXX_&z=<!-- tmpl_var date.time -->&cid=<!-- tmpl_var date.time -->" width="0" height="0" style="border:0" alt="" />`

Thank you,

  Pedro

**Comment by justingit** [comment]
Hi Pedro, what should the correct analytics tag look like? I may have some ideas, 

-- 

Justin J: Lead Dadaist. 
url:         http://dadamailproject.com
email:    justin@dadamailproject.com
twitter:  @dadamail
skype:   leaddadaist

Dada Mail Announcements: 
http://dadamailproject.com/cgi-bin/dada/mail.cgi/list/dada_announce/

**Comment by pestevao** [comment]
Sorry for late reply Justin.

It should be like this:

`<img src="http://www.google-analytics.com/collect?v=1&tid=UA-000000-0&t=event&ec=newsletters&ea=press&ev=open&cn=newsletters&cs=press&cm=email&ck=press&cc=2017%2F06%2F12&dt=%2Fnewsletters%2F2017%2F06%2F12%2Fsubs&z=1497289337" width="0" height="0" style="border:0" alt="" />`

Thank you, Pedro

**Comment by pestevao** [comment]
Hi Justin,

Just have time to test the correction on this. It isn't corrected unfortunately.

Now it displays like this:

<img  src=3D"http://www.google-analytics.com/col=
lect?v=3D1&tid=3DUA-000000-0&cid=3D%3C!--" tmpl_var date.time -->&t=
=3Devent&ec=3Dnewsletters&ea=3Dpress&ev=3Dopen&cn=3Dnewsletters&cs=3Dpress&=
cm=3Demail&ck=3Dpress&cc=3D2019%2F01%2F21&dt=3D%2Fnewsletters%2F2019%2F01%2=
F21%2Fsubs&z=3D1548087253" width=3D"0" height=3D"0" style=3D"border:0=
" alt=3D""/>

Thank you, Pedro

**Comment by pestevao** [comment]
Hi @justingit ,

Just have time to test the correction on this. It isn't corrected unfortunately.

Now it displays like this:

<img  src="http://www.google-analytics.com/collect?v=1&amp;tid=UA-000000-0&amp;cid=%7BC%7D%7BC%7D%7BC%7D%3C!--" tmpl_var date.time -->&amp;t=event&amp;ec=newsletters&amp;ea=press&amp;ev=open&amp;cn=newsletters&amp;cs=press&amp;cm=email&amp;ck=press&amp;cc={C}{C}{C}2019%2F{C}{C}{C}01%2F{C}{C}{C}21&amp;dt=%2Fnewsletters%2F{C}{C}{C}2019%2F{C}{C}{C}01%2F{C}{C}{C}21%2Fsubs&amp;z={C}{C}{C}1548088093" style="border:0" width="0" height="0" alt="" />

Thank you, Pedro

**Comment by justingit** [comment]
Google Analytics is now baked into Dada Mail - no need to roll your own: 

https://blog.dadamailproject.com/2017/07/06/easily-use-dada-mail-with-google-analytics-campaign-tracking/
