### ISSUE TITLE
ReCaptcha

### ISSUE THREAD

**Issue by gizzyman** [justingit/dada-mail#681]
I keep getting invalid key when I enter my recaptcha site and private key, the keys are correct, I have used them on dada before

**Comment by justingit** [comment]
I've been setting up the reCAPTCHA system on a good number of sites, and it does seem to work. 

I would probably need a little more information on how to reproduce this problem to keep this issue valid. 

Perhaps to start, you can show me a screenshot of configuring reCAPTCHA in the installer?
