### ISSUE TITLE
10.4.0 to 10.6.0 Pro-Data Upgrade

### ISSUE THREAD

**Issue by dennypaz** [justingit/dada-mail#682]
I downloaded the install file and the uncompress file (755) into my cgi-bin. I renamed my old cgi-data folder. When I ran the uncompress file I got a 500 Internal Server Error.

Please advise. Thanks.

**Comment by justingit** [comment]
Hi Denny, the issues tracker isn't a general support forum for issues like this. Please refer to, 

http://dadamailproject.com/contact

Cheers,

**Comment by dennypaz** [comment]
My apologies. The github link was under the Support dropdown and I didn’t see any other link.

 

DennyP Travel  <http://www.facebook.com/pages/Phoenix-AZ/DennyP-Travel/97858601228>  <http://twitter.com/dennyptravel>  | DennyP Travel Hedonism II  <http://www.facebook.com/DennyPTravelHedonismIIFans> 

Denny Pasternak
DennyP Travel

Office Hours:
Mon.-Fri. 730a--430p Arizona Time



602-882-0390 (local & international)

877-DENNYPTravel (toll-free)
877-336-6978 (toll-free)

602-798-8270 (fax)

 

 <http://www.dennyp.com/> http://www.dennyp.com- DennyP Travel

 <http://www.facebook.com/denny.pasternak> http://www.facebook.com/denny.pasternak - Facebook (business)

 <http://www.facebook.com/denny.pasternak.az> http://www.facebook.com/denny.pasternak.az - Facebook (personal)

 <http://www.twitter.com/dennyptravel> http://www.twitter.com/dennyptravel - Twitter (business)

 <http://www.twitter.com/DennyPasternak> http://www.twitter.com/DennyPasternak - Twitter (personal)

 

 

19234 N 31st St.

Phoenix, AZ 85050
