### ISSUE TITLE
Subscriber's Email Address Always Filled in with List Owner's Email Address in Mass Mailing Email Messages

### ISSUE THREAD

**Issue by gizzyman** [justingit/dada-mail#683]
in version 10.7, when sending an email, at the bottom where it says your subscribed using the address cxxx@cccc.com , it only displayes the list owners email address, when I switch back to 10.5 it displays the correct email address

**Comment by justingit** [comment]
I'll look at this ASAP - this escaped my attention,

**Comment by justingit** [comment]
Hmm, I tried testing this by sending a message via the list control panel, but the correct behavior happens - the subscribers email is shown, and not the list owner. Is there anything unique about your list that may cause the behavior you're seeing? For example, is this a discussion list, or are you relying on any specific settings? Is this a scheduled mailing? I'm just throwing things at a wall - very strange!
