### ISSUE TITLE
SSL Not Working for POP validation

### ISSUE THREAD

**Issue by wdseelig** [justingit/dada-mail#690]
We are getting an error message asking us to install IO::Socket::SSL version greater than 2.007 when we try to test our POP3 Login information with "Use Secure Sockets Layer (SSL)" set.  If I understand what is happening here, the encryption applies to the connection between dada mail and the POP3 server.  In our case, they are both on the same ISP host, so presumably the risk is negligible.  Is this correct?

[As best I can tell, the version of SSL.pm that we are using is 1.94]

**Comment by justingit** [comment]
The communication would still be in clear text if you're not using SSL. I may not be able to exactly, 100%, confirm what the routing would be, and I'd hate to give you the wrong answer on that.
