### ISSUE TITLE
mail.cgi: problems completing sending message to SMTP server. (dataend) at DADA/Mail/Send.pm line 569

### ISSUE THREAD

**Issue by kingofthering** [justingit/dada-mail#693]
Hi Justin,
I ran 10.3 and got the following problem hundrets of times in error.log. Only about 1% of the mails arrived.
mail.cgi: problems completing sending message to SMTP server. (dataend) at DADA/Mail/Send.pm line 569

I upgraded to 10.7 and the problem is still there.

Any ideas?

Thx,
Axel

**Comment by justingit** [comment]
What is the actual error in 10.7? The line numbers at the very least would be different.

**Comment by kingofthering** [comment]
Hi Justin, 

the version is Pro Dada version 10.7.0 Stable 07/06/17 

The errors are 





[Wed Aug 30 21:44:33 2017] mail.cgi: problems completing sending message to SMTP server. (dataend) at DADA/Mail/Send.pm line 569.

[Wed Aug 30 21:44:34 2017] mail.cgi: problems completing sending message to SMTP server. (dataend) at DADA/Mail/Send.pm line 569.

[Wed Aug 30 21:44:34 2017] mail.cgi: problems completing sending message to SMTP server. (dataend) at DADA/Mail/Send.pm line 569.

[Wed Aug 30 21:44:34 2017] mail.cgi: problems completing sending message to SMTP server. (dataend) at DADA/Mail/Send.pm line 569.

[Wed Aug 30 21:44:35 2017] mail.cgi: problems completing sending message to SMTP server. (dataend) at DADA/Mail/Send.pm line 569.

[Wed Aug 30 21:44:35 2017] mail.cgi: problems completing sending message to SMTP server. (dataend) at DADA/Mail/Send.pm line 569.

[Wed Aug 30 21:44:42 2017] mail.cgi: problems completing sending message to SMTP server. (dataend) at DADA/Mail/Send.pm line 569.

[Wed Aug 30 21:44:42 2017] mail.cgi: problems completing sending message to SMTP server. (dataend) at DADA/Mail/Send.pm line 569.

[Wed Aug 30 21:44:43 2017] mail.cgi: Wide character in print at /usr/lib/perl/5.18/IO/Handle.pm line 159.

[Wed Aug 30 21:44:43 2017] mail.cgi: Problems sending via SMTP: Wide character in syswrite at /var/www/.../DadaMail/dada/DADA/perllib/Net/Cmd.pm line 212.

[Wed Aug 30 21:44:43 2017] mail.cgi:  at DADA/Mail/Send.pm line 569.

[Wed Aug 30 21:44:43 2017] mail.cgi: Wide character in print at /usr/lib/perl/5.18/IO/Handle.pm line 159.

[Wed Aug 30 21:44:43 2017] mail.cgi: problems sending FROM:&lt;&gt; command to SMTP server. at DADA/Mail/Send.pm line 569.

[Wed Aug 30 21:44:43 2017] mail.cgi: problems sending FROM:&lt;&gt; command to SMTP server. at DADA/Mail/Send.pm line 569.





Problems sending via SMTP:Connecting to SMTP host:dav-tak.de on port:25

SSL: disabled

STARTTLS: disabled

NOT Verifying SSL Certificate during connection



xyzcom ESMTP Postfix (Ubuntu)



SSL Supported.

no STARTTLS

Connection to 'xyz' failed: 

 at DADA/Mail/Send.pm line 569.







Best,

Axel





---- On Di, 19 Sep 2017 18:46:32 +0200 Justin J &lt;notifications@github.com&gt; wrote ----




What is the actual error in 10.7? The line numbers at the very least would be different.

**Comment by naylina** [comment]
Did you manage to solve this?
