### ISSUE TITLE
Strange sending errors

### ISSUE THREAD

**Issue by asuweb** [justingit/dada-mail#695]
Seeing the following in the logs when sending to a particular address - the address is of standard format and is valid.  We can send to it using normal mail clients / telnet etc.

Any ideas?  

The email itself sent to every other recipient without issue.

```[Mon Sep 25 11:03:13 2017] mail.cgi: Wide character in print at /usr/lib64/perl5/IO/Handle.pm line 417.
[Mon Sep 25 11:03:13 2017] mail.cgi: Problems sending via SMTP: Wide character in syswrite at /home/.../public_html/dada/DADA/perllib/Net/Cmd.pm line 212.
[Mon Sep 25 11:03:13 2017] mail.cgi:  at DADA/Mail/Send.pm line 569.
[Mon Sep 25 11:03:14 2017] mail.cgi: problems 'QUIT'ing SMTP server. at DADA/App/MassSend.pm line 581.
```

**Comment by justingit** [comment]
@smoothstreams Closing this as way, way too old to be relevant. Perhaps look at, #744 and see if the diff'd file helps.
