### ISSUE TITLE
10.7.0 Saves Inserting Multiple Copies of a Line

### ISSUE THREAD

**Issue by johngoold** [justingit/dada-mail#696]
When looking at the source of a saved Draft (or Stationery), the following line is inserted after the &lt;html&gt; and before the &lt;head&gt; tag. The line is being re-added at each save, resulting in it occurring multiple times.

`<script type="text/javascript">window["_gaUserPrefs"] = { ioo : function() { return true; } }</script>`

**Comment by justingit** [comment]
I think this line is being inserted by a browser plugin/extension - 

https://stackoverflow.com/questions/10490218/how-to-get-rid-of-google-preference-script

I don't know if I have a way to remove it from the source of draft, except to disable that extension (for your domain, only perhaps?)
