### ISSUE TITLE
10.7.1 install fails, 10.4.0 & 7.2.1 install succeed

### ISSUE THREAD

**Issue by bretmaverick999** [justingit/dada-mail#701]
'perl -v' says 5.10.1.

In my browser the 'uncompress_dada.cgi' times out as my hosting sees a large amount of I/O operations  happening (due to the untar'ing) and thus slows it down. Via ssh I see the script is doing a 'tar -xvzf' so I: 
1. Remove the 'dada' directory, 
2. untar the file (it's slow but does finish, hence the timeout), 
3. Edit the script and comment out the tar command. 
4. The 'uncompress_dada.cgi' now succeeds and I get the link for 'install.cgi'.

Running 'install.cgi' in my browser I select 'Installation', Continue. In the next screen:
1. Manual shows '~/.dada_files'.
2. The 'Pro Dada URL' looks good.
3. The 'Support Files Directory' looks good.
4. I enter a 'Pro Dada Root Password'.
5. I 'Test SQL Connection' and the connection is successful.
6. For 'Show/Hide Options' they look fine so I don't change anything.
7. I click 'Configure Pro Dada'.  39 seconds later the following is displayed:
        Opps, 504 says '/cgi-bin/dada/installer/install.cgi' timed out!
8. If I 'rm -rf ~/.dada_files', run the script, tell the Backend to use the tables, I can try 'Advanced Configuration' options (like FastCGI), but still get the same 'Gateway Timeout'.

In the 'cgi-bin/dada/installer/install.cgi' script I uncommented the 'Carp' lines but the same gateway timeout messages were displayed.

In the Dada Documentation webpage, in the Google Custom Search box, entering 'gateway timeout' returns nothing.

In the Dada Documentation, reading thru all of the FAQs there is nothing related to 'gateway timeout'. It does mention the ~/.dada_files/.logs/errors.txt file. That directory exists but the file does not.

**Comment by bretmaverick999** [comment]
As part of trying to move forward I removed all dada files and directories, uploaded the two dada files again, read thru the documentation for 'Install Dada Mail, Command Line Interface', did the steps listed in 'Uncompress the Distribution', but then unsure of all the options so I decided to switch back to running 'install.cgi' from my browser to give it one more try AND to save off ~/.dada_files/.configs/.dada_config and ~/public_html/cgi-bin/dada/DADA/Config.pm. In doing this I found the file public_html/cgi-bin/dada/installer/errors.txt. The first two lines of it are:

Pro Dada 10.7.1 Stable 10/04/17 warning! Could not create, ' /.tmp/_screen_cache - No such file or directory - disabling screen cache. at ~/public_html/cgi-bin/dada/installer/..//DADA/App/ScreenCache.pm line 74.
DBI connect('dbname=;host=localhost;port=3306','',...) failed: Access denied for user 'root'@'localhost' (using password: NO) at ..//DADA/App/DBIHandle.pm line 127

I tested the connection to my DB so I know it works. Either this version of Dada is way messed up, or my hosting environment is limiting CGI script execution, or ???  Now that I have the two config files saved I'll try starting from scratch again and then try to do the install from the CLI. Stay tuned....

**Comment by bretmaverick999** [comment]
As documented in the previous post I've narrowed down the problem. Since I'm not getting any help I thought I would try the 'Install Dada Mail, Command Line Interface' route. Using this route I can get Dada to successfully install in 22 seconds (it displays the cronjob example and renames the installer directory). 

I saved the following config files after the browser and cli methods of running install.cgi:
1. ~/.dada_files/.configs/.dada_config
2. ~/public_html/cgi-bin/dada/DADA/Config.pm
3. ~/public_html/cgi-bin/dada/installer*/errors.txt

Comparing the two versions of each file shows the following differences:
1. the following are different: PROGRAM_ROOT_PASSWORD(ignoring this), rich_filemanager and SCHEDULED_JOBS_OPTIONS aren't configured via the CLI.
2. the browser method isn't setting PROGRAM_CONFIG_FILE_DIR. Since the CLI got it right this can be ignored.
3. A number of minor differences here, the major difference is the browser version dies as documented in my previous comment.

I spent lots of time trying to get the CLI version to set the rich_filemanager parameters like the browser version does, but after lots of reading the documentation and code I finally gave up.

A browser running the mail.cgi URL brings up the 'Congratulations, and Welcome to Pro Dada!' screen. I was able to create a list, but didn't try to configure it or use it. Doing 'Plugins/Extensions > Global Configuration' and 'Reconfigure Pro Dada' returned a Gateway Timeout again.

**Comment by bretmaverick999** [comment]
Just tried to install the previous version I was using, 7.2.1, and it installed without a problem.

**Comment by bretmaverick999** [comment]
Last comment, I'm done updating. Let me know if you want the dada/installer/errors.txt file, I'm uncertain who would have access to it here if I uploaded it.

**Comment by justingit** [comment]
What's the current hosting platform you're on, where you're experiencing problems with the most recent version of Dada Mail (as I write, v10.7.1)?

**Comment by bretmaverick999** [comment]
https://www.westhost.com/

# uname -a
Linux sl-508-7.slc.westdc.net 2.6.32-673.26.1.lve1.4.29.el6.x86_64 #1 SMP Tue Jun 20 13:27:00 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

# cat /proc/version
Linux version 2.6.32-673.26.1.lve1.4.29.el6.x86_64 (mockbuild@build.cloudlinux.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) ) #1 SMP Tue Jun 20 13:27:00 EDT 2017

If that's not the info you are looking for please let me know.

**Comment by justingit** [comment]
Try this, next to you try to install v10.7.1 (or later) via the web-based installer: 

When you go through the steps, and get the gateway timeout error again, try just renaming the "installer" directory manually (installer-bak will work just fine), then visiting Dada Mail via visiting http://example.com/cgi-bin/dada/mail.cgi (or wheverever "mail.cgi" lives) and see if the app comes up. 

When it comes down to it, this is a server-related error (gateway timeout error)
