### ISSUE TITLE
No New Users Can Subscribe - Dada 10.7.1

### ISSUE THREAD

**Issue by edcoates** [justingit/dada-mail#704]
I've recently upgraded to 10.7.1 and now when new subscribers try to subscribe they're getting a message that they're not allowed to subscribe.  I've checked the error log that resides in .dada_files/.logs and there's nothing in there about these denied subscriptions.

One of the subscribers had inadvertently unsubscribed himself from the list.  I removed him from the black list, but he's still gets the message that he's not allowed to subscribe.  I've tried to subscribe through multiple emails, and I always get an error saying that I'm not allowed to subscribe.  I finally had to manually add them to the list.

Not sure where to start looking for problems.

Ed Coates

**Comment by justingit** [comment]
Hi Ed, this is more of a general support question, than a bug/issue - you would want to report this to the app support Zendesk, along with your Pro Dada username: 

http://dadamailproject.com/contact/

Cheers,
