### ISSUE TITLE
Failed open stream error every time the cron job runs

### ISSUE THREAD

**Issue by kc8oye** [justingit/dada-mail#715]
<br />
<b>Warning</b>:  require(/home1/gcaresin/public_html/miskywarn/wp-blog-header.php): failed to open stream: No such file or directory in <b>/home1/gcaresin/public_html/miskywarn/index.php</b> on line <b>17</b><br /> <br />
<b>Warning</b>:  require(/home1/gcaresin/public_html/miskywarn/wp-blog-header.php): failed to open stream: No such file or directory in <b>/home1/gcaresin/public_html/miskywarn/index.php</b> on line <b>17</b><br /> <br /> <b>Fatal error</b>:  require(): Failed opening required '/home1/gcaresin/public_html/miskywarn/wp-blog-header.php' (include_path='.:/opt/php70/lib/php') in <b>/home1/gcaresin/public_html/miskywarn/index.php</b> on line <b>17</b><br />

isn't wp-yadda-yadda a word press file?

do i need to copy this file from somewhere, or what I can i do to stop it looking for it?

**Comment by justingit** [comment]
The error being reported is def. about Wordpress.
