### ISSUE TITLE
Mailing 

### ISSUE THREAD

**Issue by camkwc** [justingit/dada-mail#717]
This week, all of my mailings have been rejected after the mails have been sent.  Error message:

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

 kwcblade@gmail.com
   host smtp.mailchannels.net [54.191.203.134]
   SMTP error from remote mail server after end of data:
   550 5.7.1 [BFD] Sender prohibited by SPF
Reporting-MTA: dns; andromeda.thewebhostserver.com

Action: failed
Final-Recipient: rfc822;kwcblade@gmail.com
Status: 5.0.0
Remote-MTA: dns; smtp.mailchannels.net
Diagnostic-Code: smtp; 550 5.7.1 [BFD] Sender prohibited by SPF

From: "Village" <kwcblade@gmail.com>
Subject: Village Message
Date: 1 March 2018 at 16:30:44 GMT
To: "Village Subscriber" <kwcblade@gmail.com>

**Comment by justingit** [comment]
I've spoken to you directly via email - this is a support request, and not an issue with the app itself. Closing.
