### ISSUE TITLE
Removing List Consents is not working

### ISSUE THREAD

**Issue by holzhannes** [justingit/dada-mail#725]
I accidentally added a List Consent for a mailing List. When I try to remove it with the red button nothing happens.

**Comment by justingit** [comment]
Could you paste any errors you find in the error log, associated with when you try to do this action?

**Comment by bjxrn** [comment]
Are all JS files you need being properly loaded?

I had an issue with this resulting from not properly updating the dada_mail_support_files directory. I had the wrong permissions set during upgrading, which meant the new javascript files weren't added, which meant the buttons didn't work.

**Comment by holzhannes** [comment]
It was a problem of JS Files because I copied the old static folder content to the new version. Sorry.
