### ISSUE TITLE
Mailing lists set to hidden (but not private) are listed on the default screen

### ISSUE THREAD

**Issue by bjxrn** [justingit/dada-mail#728]
That's pretty much the whole issue. The option "Make your mailing list hidden" doesn't seem to have any effect for the default screen. This is using v 11.0.0.

There are a number of instances in /dada/DADA/Template/Widgets.pm where there seems to be a check whether a list is hidden. They are all of the form
`($ls->param('hide_list') == 1 && $ls->param('private_list') == 1)`
but they should probably be
`($ls->param('hide_list') == 1 || $ls->param('private_list') == 1)`

**Comment by justingit** [comment]
In Dada Mail, only private lists may currently be hidden. That's why the "hidden" option is listed under the, "private list" option.

**Comment by bjxrn** [comment]
Whoops. That makes sense. Thanks for the quick reply.
