### ISSUE TITLE
Mails are Not sent

### ISSUE THREAD

**Issue by holzhannes** [justingit/dada-mail#744]
Since DadaMail 11.0.3 Mails can’t be sent any more. Even testmails will fail. In the Error Log I found the following lines:

`[Mon Jul  9 19:39:36 2018] mail.cgi: problems sending '' in 'RCPT TO:<>' command to SMTP server. at DADA/Mail/Send.pm line 571.
[Mon Jul  9 19:39:37 2018] mail.cgi: problems sending, "RSET" command to SMTP server. at DADA/Mail/Send.pm line 571.
[Mon Jul  9 19:39:37 2018] mail.cgi: problems sending FROM:<> command to SMTP server. at DADA/Mail/Send.pm line 571.
[Mon Jul  9 19:39:37 2018] mail.cgi: problems sending FROM:<> command to SMTP server. at DADA/Mail/Send.pm line 571.
[Mon Jul  9 19:39:37 2018] mail.cgi: problems sending, "RSET" command to SMTP server. at DADA/Mail/Send.pm line 571.
[Mon Jul  9 19:39:37 2018] mail.cgi: problems sending FROM:<> command to SMTP server. at DADA/Mail/Send.pm line 571.
[Mon Jul  9 19:39:37 2018] mail.cgi: problems sending FROM:<> command to SMTP server. at DADA/Mail/Send.pm line 571.
[Mon Jul  9 19:39:37 2018] mail.cgi: problems sending, "RSET" command to SMTP server. at DADA/Mail/Send.pm line 571.
[Mon Jul  9 19:39:37 2018] mail.cgi: problems 'QUIT'ing SMTP server. at plugins/bridge line 2667.`

**Comment by justingit** [comment]
This is indicative to a problem with the SMTP login credentials. I would check those to make sure they're correct, before thinking this is a bug (there's a email sending tester within the Sending:Options screen.

**Comment by sandy-j** [comment]
Hi Justin, I am also seeing
`mail.cgi: problems sending '' in 'RCPT TO:<>' command to SMTP server. at DADA/Mail/Send.pm line 571.`
This is with Pro Dada 11.0.4. I do not see any other errors, but no mailing list messages are sent. The "Test" message and the "Mailing Complete" message ARE received OK at the list owner email address, so it seems that the SMTP login is OK. but the above message is issued for each recipient of a mass mailing. 
(Pro Dada 11.0.1 is working fine, I'm staying with that for production use for now.) 
Regards
Sandy

**Comment by justingit** [comment]
Investigating...

**Comment by justingit** [comment]
OK, can confirm. Strange!

**Comment by justingit** [comment]
Looks like a one-line fix: 

https://github.com/justingit/dada-mail/commit/95f64f865e4c2c27975f57a265adc9073d15f78c

I appreciate all the reports and my apologies @holzhannes I feel like you brought up an issue I didn't investigate as thoroughly as I should have on the day you reported it.
