### ISSUE TITLE
Installer creates mail.fcgi, but dada_config uses mail.cgi

### ISSUE THREAD

**Issue by admorgan** [justingit/dada-mail#747]
I installed 11.0.4 using the installer. The installed reported that everything worked correctly, but when I click on the Get Started With Dada button it redirects me to mail.fcgi. I updated my cgi redirect to accept fcgi as well as cgi. When I looked in the .dada_config PROGRAM_URL and S_PROGRAM_URL use mail.cgi. RUNNING_UNDER = CGI. I am not sure what to do to get a working instance at this point.

**Comment by justingit** [comment]
Basically, don't use FastCGI. Run under, "CGI" and make sure the Program URL uses "mail.cgi" in the URL. Although, I do not know what you did for this step: 

> I updated my cgi redirect to accept fcgi as well as cgi.

Also use v11.0.5; v11.0.4 had two nasty bugs that affected mass mailing.

**Comment by admorgan** [comment]
I didn't do anything I left the defaults. I did download and run 11.0.5 and was able to successfully get an instance running.
