### ISSUE TITLE
Custom "from_phrase" and "subject" set in email theme templates not used with Full Layout

### ISSUE THREAD

**Issue by sandy-j** [justingit/dada-mail#749]
Hi Justin, 
When testing Pro Dada 11.1.0, I find that the "from_phrase" and "subject" set in email theme templates are not being picked up, although the "to_phrase" IS being used. But strangely, this problem ONLY shows with the Full Layout option selected. When using Minimal Layout, Discussion List layout, Old School etc. everything works correctly. This is similar to issue #734 but maybe not quite the same. Seems to apply to every theme that I've tried.
TIA
Sandy

**Comment by justingit** [comment]
Can you walk me through the process of how you set up the custom from_phrase and header in your testing?

**Comment by sandy-j** [comment]
Hi Justin,
I'm just using the default Theme, which already has 
   from_phrase: 
   subject:  Message
set up in the mailing_list_message.txt file.  I haven't changed these. But they are not being picked up with the "Full layout" option, although they are picked up with every other Layout option. So the message comes from the list email address but with no List Name preceding it.
But the first line in mailing_list_message.txt, i.e.
   to_phrase:  Subscriber
IS being used, so the message comes with the correct "To" header, even with Full Layout.
Sandy

**Comment by sandy-j** [comment]
That last message didn't come out right, the lines should read:
`to_phrase:  Subscriber
from_phrase: 
subject:  Message`
Hope that looks better this time
