### ISSUE TITLE
Multiple Subscribe option  inside Plugins menu throws syntax error.

### ISSUE THREAD

**Issue by prbt2016** [justingit/dada-mail#750]
Hi,
After manual installation of Dada Mail version 11.1.0 ,visiting Plugins/Extensions->Multiple Subscribe throws the following syntax error.

**syntax error at /{{PATH}}//{{TO}}/{{CGI-BINDIR}}/{{DADA-ROOTDIR}}/extensions/multiple_subscribe.cgi line 91, near "} )"
Execution of /{{PATH}}//{{TO}}/{{CGI-BINDIR}}/{{DADA-ROOTDIR}}/extensions/multiple_subscribe.cgi aborted due to compilation errors**.
Could you please check and fix this issue.Downloaded the zip file from here 
https://sourceforge.net/projects/dadamail/files/dada-11_1_0.tar.gz/download

**Comment by justingit** [comment]
On line 91: 

`        $html_info = markdown_to_html { -str => $html_info } );`

change to: 

`        $html_info = markdown_to_html ({ -str => $html_info } );`

But do note: 

[http://dadamailproject.com/d/gdpr_guide.pod.html#Multiple-List-Subscribe-extension-non-functional-for-public-mailing-lists](http://dadamailproject.com/d/gdpr_guide.pod.html#Multiple-List-Subscribe-extension-non-functional-for-public-mailing-lists
)
> Multiple List Subscribe extension non-functional for public mailing lists
> 
> For the same reason as above, the multiple subscribe form isn't going to work, if you are running multiple mailing lists, with different privacy policies and/or list consents.
> 
> Because of that, we absolutely do NOT suggest using this extension at all. You'll have to figure out a different system to

 allow people to subscribe to more than one mailing list at once.

**Comment by prbt2016** [comment]
Hi Justin,
Thanks for the fix.works fine now.
