### ISSUE TITLE
The installation helper script for pro_dada version 11.1.2 looks to install version 11.1.1

### ISSUE THREAD

**Issue by ericcho** [justingit/dada-mail#752]
The installation helper script uncompress_dada.cgi for pro_dada version 11.1.2 looks for version 11.1.1 instead of 11.1.2, creating a Yikes! file not found error message.  The free version does not have this bug.

Free version uncompress_dada.cgi line 16
my $basic = 'dada-11_1_2.tar.gz';

Pro Dada uncompress_dada.cgi line 16
my $basic = 'dada-11_1_1.tar.gz';

**Comment by justingit** [comment]
Looks like you're right - the link to the script is incorrect. Here's the correct link: 

https://raw.githubusercontent.com/justingit/dada-mail/v11_1_2-stable_2018_08_04/uncompress_dada.cgi

I have fixed this on the download page. Thanks for the report,
