### ISSUE TITLE
Authenticating to POP3 box over ssl throws "To use SSL please install IO::Socket::SSL with version>=2.007"

### ISSUE THREAD

**Issue by gvdvenis** [justingit/dada-mail#764]
Strato shared accounts require SSL connections, but when i try to connect bridge (`List Email Configuration`  form) to my pop-box I receive this error:
```
To use SSL please install IO::Socket::SSL with version>=2.007 at 
/mnt/web410/d2/89/59460589/htdocs/cgi-bin/dada/DADA/perllib/Net/POP3.pm line 72.
Connection is NOT Successful.
```
I checked the `"Use Secure Sockets Layer (SSL)"` box, `Authentication Type == POP` and `Port == 995`

**Comment by justingit** [comment]
Closing this, as the error reported gives the reason, and fix to the issue: 

`To use SSL please install IO::Socket::SSL with version>=2.007
`
