### ISSUE TITLE
Dada auto installation fails

### ISSUE THREAD

**Issue by philmck** [justingit/dada-mail#776]
What I did:

- Unzipped pro_dada-11_2_4.tar.gz to the /cgi-bin folder of a newly installed website (www.mckerracher.net) on Ubuntu 18.04 LTS managed by Virtualmin 1.894 on a new VPS.  
- Changed ownership and permissions recursively on /cgi-bin/dada, 0755. Renamed installer-disabled to installer.
- Created an empty database for it and ran the installer by visiting /installer/install.cgi. Accepted defaults.

What I saw:
Two orange error boxes saying:
   Some problems were encountered when attempting to install and configure Pro Dada. Details are marked below.

   Can not create, /home/mckerracher/.local/share/.dada_files

What I expected to see: No errors.

What I did: Manually selected the path to be /home/mckerracher/.dada_files, which was the default location in earlier versions of Dada Mail. Clicked "Configure Pro Dada" again.

What I saw then: The same error boxes, but now with "Please provide root password" shown twice in red.

What I did next: Re-entered the root password twice and clicked "Configure Pro Dada" again.

What I saw: A new orange error box saying
The SQL information below is correct, but there are tables in this database that correspond to the tables that Pro Dada requires.

 Correct!
I know about these tables, please use them!

What I did next: Clicked the "Correct!" box, re-entered the root password again twice, clicked the Configure button again.

What I saw: The next screen in the installer.

This is a lot harder than it needs to be, IMHO.

**Comment by justingit** [comment]
This doesn't seem to be a problem, this just seems to be a misconfiguration when attempting to install. You fixed the misconfiguration, then it installed. 

> This is a lot harder than it needs to be, IMHO.

How would you make this easier?

**Comment by philmck** [comment]
I didn’t configure it, I left it as “Auto”. It would be easier if the default was a directory that could be created automatically (like /.dada_files or even just .dada_files) rather than one that requires the manual creation of a set of intermediate directories. I’m really not fussy about the location.

 

-- 
Phil McKerracher
+44 7565 803841
 <https://www.beechesit.uk/> www.beechesit.uk
