### ISSUE TITLE
Rich Filemanager doesn't work on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by philmck** [justingit/dada-mail#778]
What I did:

- A clean installation of pro_dada-11_2_4.tar.gz on Ubuntu 18.04.1 managed by Webmin 1.894 (tweaked to get it to install as described in other bug reports)
- Created a new list called "test"
- Visited Mass Mailing > New Draft Message > Attachments > Select a File...

What I saw:

A popup mainly blank but with a red AUTHORIZATION_REQUIRED message in the bottom right corner and an endlessly spinning cursor, 

What I expected: A list of files with an option to upload a new one.

What I tried: Logging out and in, since this has helped with the same problem in previous releases.

What I saw: No difference.

**Comment by justingit** [comment]
This isn't the Rich Filemanager project, so I'm closing this. My suggestion is to use an alternative file manager, which is one of the reason there are multiple file managers shipped with Dada Mail. Many times, the PHP sessioning system used for this file manager doesn't work when tried to mix in with Perl.
