### ISSUE TITLE
KCFinder doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by philmck** [justingit/dada-mail#779]
What I did:

- A clean installation of pro_dada-11_2_4.tar.gz on Ubuntu 18.04.1 managed by Webmin 1.894 (tweaked to get it to install as described in other bug reports)
- Visited Plugins/Extensions > Global Configuration > Install KCFinder > Configure Pro Dada > Move the dada/installer directory > start working with Pro Dada
- Logged in again with root password, visited Attachments > Select a File...

What I saw:

A popup saying
`You don't have permissions to browse server.`

What I expected: A list of files and an option to upload a new one.

**Comment by justingit** [comment]
This isn't the KCFinder project, so I'm closing this. My suggestion is to use an alternative file manager, which is one of the reason there are multiple file managers shipped with Dada Mail. Many times, the PHP sessioning system used for this file manager doesn't work when tried to mix in with Perl.
