### ISSUE TITLE
Core 5 Filemanager doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by philmck** [justingit/dada-mail#780]
What I did:

- A clean installation of pro_dada-11_2_4.tar.gz on Ubuntu 18.04.1 managed by Webmin 1.894 (tweaked to get it to install as described in other bug reports)
- Visited Plugins/Extensions > Global Configuration > Install KCFinder > Configure Pro Dada > Move the dada/installer directory > start working with Pro Dada
- Logged in again with root password, visited Attachments > Select a File...

What I saw:

A popup window with a sidebar and some buttons ("Upload", "New folder" etc) but mainly blank with an endlessly spinning cursor.

In addition, a browser warning that the popup was trying to load content from insecure sources.

What I expected: A list of files and an option to upload a new one.

**Comment by justingit** [comment]
Are there any errors logged from Core 5 Filemanager that you can report?

**Comment by philmck** [comment]
Ooh, yes, I didn’t notice:

 

[Sat Nov 03 04:25:26.909889 2018] [cgi:error] [pid 7394] [client 2a00:23c4:8081:2c00:58a:9fa7:589d:41ea:55499] AH01215: [Sat Nov  3 04:25:26 2018] filemanager.pl: Can't locate DADA/Config.pm in @INC (you may need to install the DADA::Config module) (@INC contains: /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../../cgi-bin/dada/DADA/perllib /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../../cgi-bin/dada /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../cgi-bin/dada/DADA/perllib /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../cgi-bin/dada /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../cgi-bin/dada/DADA/perllib /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../cgi-bin/dada /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base /home/mckerracher/perl5/lib/perl5 /home/mckerracher/perl5/lib/perl5/x86_64-linux-thread-multi /home/mckerracher/perllib /home/mckerracher/perl/home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../../cgi-bin/dada/DADA/perllib /home/mckerracher/perl/home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../../cgi-bin/dada /home/mckerracher/perl/home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../cgi-bin/dada/DADA/perllib /home/mckerracher/perl/home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../cgi-bin/dada /home/mckerracher/perl/home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../cgi-bin/dada/DADA/perllib /home/mckerracher/perl/home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../cgi-bin/dada /home/mckerracher/perl/etc/perl /home/mckerracher/perl/usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /home/mckerracher/perl/usr/local/share/perl/5.26.1 /home/mckerracher/perl/usr/lib/x86_64-linux-gnu/perl5/5.26 /home/mckerracher/perl/usr/share/perl5 /home/mckerracher/perl/usr/lib/x86_64-linux-gnu/perl/5.26 /home/mckerracher/perl/usr/share/perl/5.26 /home/mckerracher/perl/usr/local/lib/site_perl /home/mckerracher/perl/usr/lib/x86_64-linux-gnu/perl-base) at filemanager.pl line 24.: /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/filemanager.pl, referer: https://www.mckerracher.net/dada_mail_support_files/core5_filemanager/index.html?custom_function=SetAttachmentUrl

[Sat Nov 03 04:25:26.910094 2018] [cgi:error] [pid 7394] [client 2a00:23c4:8081:2c00:58a:9fa7:589d:41ea:55499] AH01215: [Sat Nov  3 04:25:26 2018] filemanager.pl: BEGIN failed--compilation aborted at filemanager.pl line 24.: /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/filemanager.pl, referer: https://www.mckerracher.net/dada_mail_support_files/core5_filemanager/index.html?custom_function=SetAttachmentUrl

 

I tried “cpan install DADA::Config” but it couldn’t find it.

 

-- 
Phil McKerracher
+44 7565 803841
 <https://www.beechesit.uk/> www.beechesit.uk

**Comment by justingit** [comment]
This isn't a support forum (so I'm closing this), but you may have to add a Perl Library path to the config of your Dada Mail, so that Core 5 Filemanager knows where to find, DADA::Config.pm

https://dadamailproject.com/d/install_dada_mail-advanced_configuration.pod.html#Additional-Perl-Library-Paths

Probably the two following: 

/home/mckerracher/public_html/cgi-bin/dada
/home/mckerracher/public_html/cgi-bin/dada/DADA/perllib

**Comment by philmck** [comment]
The path it needs is actually /home/mckerracher/public_html/cgi-bin/dada/DADA I think but it still doesn’t work, I’m still seeing this error even though Config.pm is definitely in that location and with correct ownership and permissions.

 

[Sat Nov 03 18:44:03.241483 2018] [cgi:error] [pid 2279] [client 2a00:23c4:8081:2c00:58a:9fa7:589d:41ea:61306] AH01215: [Sat Nov  3 18:44:03 2018] filemanager.pl: Can't locate DADA/Config.pm in @INC (you may need to install the DADA::Config module) (@INC contains: /home/mckerracher/public_html/cgi-bin/dada/DADA /home/mckerracher/public_html/cgi-bin/dada /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../../cgi-bin/dada/DADA/perllib /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../../cgi-bin/dada /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../cgi-bin/dada/DADA/perllib /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../cgi-bin/dada /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../cgi-bin/dada/DADA/perllib /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../cgi-bin/dada /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base /home/mckerracher/perl5/lib/perl5 /home/mckerracher/perl5/lib/perl5/x86_64-linux-thread-multi /home/mckerracher/perllib /home/mckerracher/perl/home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../../cgi-bin/dada/DADA/perllib /home/mckerracher/perl/home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../../cgi-bin/dada /home/mckerracher/perl/home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../cgi-bin/dada/DADA/perllib /home/mckerracher/perl/home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../../cgi-bin/dada /home/mckerracher/perl/home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../cgi-bin/dada/DADA/perllib /home/mckerracher/perl/home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/../../cgi-bin/dada /home/mckerracher/perl/etc/perl /home/mckerracher/perl/usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /home/mckerracher/perl/usr/local/share/perl/5.26.1 /home/mckerracher/perl/usr/lib/x86_64-linux-gnu/perl5/5.26 /home/mckerracher/perl/usr/share/perl5 /home/mckerracher/perl/usr/lib/x86_64-linux-gnu/perl/5.26 /home/mckerracher/perl/usr/share/perl/5.26 /home/mckerracher/perl/usr/local/lib/site_perl /home/mckerracher/perl/usr/lib/x86_64-linux-gnu/perl-base) at filemanager.pl line 34.: /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/filemanager.pl, referer: https://www.mckerracher.net/dada_mail_support_files/core5_filemanager/index.html?custom_function=SetAttachmentUrl

[Sat Nov 03 18:44:03.241685 2018] [cgi:error] [pid 2279] [client 2a00:23c4:8081:2c00:58a:9fa7:589d:41ea:61306] AH01215: [Sat Nov  3 18:44:03 2018] filemanager.pl: BEGIN failed--compilation aborted at filemanager.pl line 34.: /home/mckerracher/public_html/dada_mail_support_files/core5_filemanager/connectors/pl/filemanager.pl, referer: https://www.mckerracher.net/dada_mail_support_files/core5_filemanager/index.html?custom_function=SetAttachmentUrl

 



 

-- 
Phil McKerracher
+44 7565 803841
 <https://www.beechesit.uk/> www.beechesit.uk

**Comment by philmck** [comment]
In case it helps anyone (including me in the future!), I finally got this working with a configuration change and some extra Perl modules.

The configuration change was effectively adding another "../" level to the paths, because Virtualmin by default puts cgi-bin one level above public_html (for security). The safest place to add the new paths is in the master .dada_config file, and can be done by running Plugins/Extensions > Global Configuration > Advanced Configuration > Configure Perl Environment.

The extra Perl modules I needed (and are NOT included in Bundle::DadaMail) were:
File::Slurp
CGI::Session
Crypt::CipherSaber
Convert::UU
