### ISSUE TITLE
cpan install Bundle::DadaMail doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by philmck** [justingit/dada-mail#781]
What I did:

- A new installation of Ubuntu 18.04.1 managed by Webmin 1.894
- Connected to SSH, sudo to root.
- Ran the command
`cpan install Bundle::DadaMail`

What I saw:

A very long console output, most of which scrolled past fast but ending in an endless loop of 
```
Can't stat `../apache_x.x/src'
Please tell me where I can find your apache src
 [../apache_x.x/src] ../apache_x.x/src
```
What I did: Pressed CTRL + C to break out of the loop. 
 
What I saw: More console output, including this line
`Can't locate SOAP/Lite.pm in @INC (you may need to install the SOAP::Lite module)`

What I did:
`cpan install SOAP::Lite`

What I saw: Other errors including:
```
*** ExtUtils::PkgConfig requires the pkg-config utility, but it doesn't
*** seem to be in your PATH.  Is it correctly installed?
```

What I did:
```
sudo apt install pkg-config
sudo apt install libsoap-lite-perl
sudo apt install libxml-libxml-perl
sudo apt install libgd-gd2-perl
```

What I saw: No more errors!

My point: This took me hours, I have abbreviated a bit. Most people would lose patience.

**Comment by justingit** [comment]
Is this more of problem that there was additional steps to get CPAN modules installed (via, "cpan") in general?

**Comment by philmck** [comment]
If I understand you correctly I agree that this is more of a “cpan” problem than a “dada” problem, yes. But although it might not be your fault, it’s nevertheless your problem because the only way I can solve it is with hours of effort or by giving up on Dada.

So, can I suggest you could either document or automate the installation process that is actually necessary on some common platforms like Ubuntu and Centos, for example to include the extra commands I listed in the report. I suspect quite a few potential customers are giving up because it’s just too time-consuming.

 

-- 
Phil McKerracher
+44 7565 803841
 <https://www.beechesit.uk/> www.beechesit.uk

**Comment by justingit** [comment]
No, this is clearly not a problem of this project. If the underlying tool isn't functioning (cpan), it's not in my wheelhouse to somehow fix this. I'm not completely sold of the universality of the steps you've outlined.
