### ISSUE TITLE
"Local delivery failed" with mailing list as subscriber to another mailing list

### ISSUE THREAD

**Issue by RefereeBeau** [justingit/dada-mail#791]
DadaMail version 11.2.2, installed on domain "sjsra.org" hosted by GoDaddy.

New user of DadaMail. Testing two new mailing lists: "members" and "announcements". Using various of my own email addresses only, as test subscribers. Bridge is enabled. All testing and my learning curve going well with both lists, until: 

The "announcements" list is intended to contain _all members_ plus non-member interested parties, so I added "members@sjsra.org" as a subscriber to "announcements@sjsra.org".

Test message to "announcements" was delivered to all subscribers, including "members". But the bridge forwarding of the "members" copy failed with this error:

  **pipe to |/usr/local/cpanel/3rdparty/mailman/mail/mailman post members_sjsra.org
    generated by members@sjsra.org
    local delivery failed

The following text was generated during the delivery attempt:

------ pipe to |/usr/local/cpanel/3rdparty/mailman/mail/mailman post members_sjsra.org
       generated by members@sjsra.org ------

cagefs_enter: /usr/local/cpanel/3rdparty/mailman/mail/mailman: Permission denied**

I wasn't able to find any information about this error or my "list subscribed to list" configuration in the documentation or via Google searches, so submitting this issue via Github.

**Comment by justingit** [comment]
> The "announcements" list is intended to contain _all members_ plus non-member interested parties, so I added "[members@sjsra.org](mailto:members@sjsra.org)" as a subscriber to "[announcements@sjsra.org](mailto:announcements@sjsra.org)".

That sounds like a terrible, terrible idea. 

The other error is about Mailman, not Dada Mail. 

> I wasn't able to find any information about this error or my "list subscribed to list" configuration

Don't. 

Closing this... ... this just isn't the support forum for Dada Mail, so I'm not going to be troubleshooting your configuration here. I hope that makes sense.
