### ISSUE TITLE
excluded subdir in pro 11.2.7

### ISSUE THREAD

**Issue by hvillemoes** [justingit/dada-mail#795]
It seems, that the subdir dada_mail_support_files is missing in the 11.2.7 package.
That causes me a couble of hours of debugging at each upgrade.
Is it moved? Or why?

**Comment by justingit** [comment]
The, dada_mail_support_files directory is created by Dada Mail during installation programmatically, but it's not something present in the distribution itself. 

Running the installer will create it, if it's not present, and the one of the things the installer requires that you do is set the location for it.

**Comment by hvillemoes** [comment]
Thank you for your reply.
I followed the documentation for upgrading:
rename dada to dada_old, untar package, change acls and run installer with upgrade.
That did not create the dada_mail_support_files.
The documentation for upgrade might be changed to:
untar new package on top of old pachage, change acls and run installer with upgrade.
That procedure worked for me.
