### ISSUE TITLE
Images broken in email

### ISSUE THREAD

**Issue by kristinpp** [justingit/dada-mail#797]
Hello... 
Trying to send out a mailing today (last one sent in September), and this time, when I receive the test email, all of the embedded image links are broken... ???  (Worked fine in September, and I haven't updated!) The images all show up correctly in my draft.

I tried a couple of recipients - including a Gmail one, and no luck. The Gmail indicated that they were mime attachments. 
Here's a sample of the source code as copied from a received email:
`<img  src="cid:d264493270263a3e8977ccc0f5df9926_Brasilient5_Nov2019_closing.jpg" />`
The original image in the draft was called via:
`<img  src="https://resilitator.com/images/graphics-nl/Brasilient5_Nov2019_closing.jpg" />`

Running version  10.0.0 Stable 10/27/16  (only send 1-3 messages a year -- always mean to upgrade but forget about it until time to send new message!) 

Thx...

**Comment by justingit** [comment]
You'd want to upgrade first, then report back on this issue if there's still a problem.

**Comment by kristinpp** [comment]
OK, so I upgraded the installation -- and now I have a different issue. Two symptoms: 
1) some of the small icons don't show up properly, and 
2) when I click into my current draft, the header with all the options hangs on load. (See screenshots) 

Also, installation of the perl module Bundle::DadaMailXXL was not complete. Some modules installed, others didn't. I contacted my web host who had the same results (sample of log errors attached), here's their reply:
> 
I checked the link you have sent which is only about installing a module and what module contains dadamail bundle, I couldn't find any information that module is part of the update. It's only your account that is trying to install older packages like, Text-Balanced-1.98.tar.gz. I still checked this further and found it's only your account which is not able to install that bundle module so it looks like there were some changes have been done. You may need to revert them back and retry. You could also install the latest version through cPanel > Softaculous. It has latest dadamail version available for installation.
 - - - - 
I chose not to retry the installation through Softilicious as I haven't looked into how it will affect / tie into my existing DB (or not).

Thoughts? Could it be a simple permissions issue?
Thanks!
[DaDa-Perl-Error-List.txt](https://github.com/justingit/dada-mail/files/2979163/DaDa-Perl-Error-List.txt)
<img width="1038" alt="Missing-Icons" src="https://user-images.githubusercontent.com/48491662/54545494-066c6a80-495f-11e9-860c-34c252af95a7.png">
<img width="1059" alt="Loading-hang" src="https://user-images.githubusercontent.com/48491662/54545496-066c6a80-495f-11e9-928a-92da80c668d3.png">

**Comment by justingit** [comment]
I'm closing this, as it's not really a bug issue that you want to file, but rather a general support request. If you do have a Pro Dada account, please start a new thread by emailing: 

(mention your Pro Dada username) 

support@dadamail.zendesk.com

And I'll make sure you're served.
