### ISSUE TITLE
Cloning list settings during list creation does not work

### ISSUE THREAD

**Issue by justingit** [justingit/dada-mail#799]
Error reported back: 

    BAD List name "new_list_shortname" No such file or directory at DADA/MailingList.pm line 101.

where, "new_list_shortname" is the list short name of your new list.

**Comment by justingit** [comment]
This issue most likely won't affect people unless they have the following settings saved in the list you're cloning from: 

* sasl_smtp_password 
* discussion_pop_password

An interesting side effect of cloning is the cipher key will also be shared between lists. I really don't see a *great* utility in encrypting these if the key itself is saved in the same place as the encrypted passwords, so I'm letting this stay as-is, for now.

**Comment by rspilk** [comment]
Hi Justin,

Thanks for investigating this issue. Do you know when we might see this fix included in an update?

**Comment by justingit** [comment]
@rspilk should have been fixed in the v11.2.9 release of Dada Mail: 

https://dadamailproject.com/d/changes_11_x.pod.html#Cloning-list-settings-during-list-creation-does-not-work-799
