### ISSUE TITLE
bounce stopped working after upgrade to 11.2.7

### ISSUE THREAD

**Issue by hvillemoes** [justingit/dada-mail#803]
After upgrade to 11.2.7 the previously well-working bounce handler stopped working i.e. it reports no bouncing mails, although we know, that there are many.
OS: Ubuntu 18.04.2 LTS
The bounce.txt has not been updated since the upgrade.
The errors.txt has some strance install/upgrade msgs.
[dada_logs.zip](https://github.com/justingit/dada-mail/files/3059755/dada_logs.zip)

Please advice.

**Comment by justingit** [comment]
Closing this - this isn't the support forum, but a place primarly to open bugs/issues. Please use the Zendesk email listed at, 

https://dadamailproject.com/contact/

for support requests. Make sure to include your Pro Dada username,
