### ISSUE TITLE
Unable to subscribe user when logged in with root password

### ISSUE THREAD

**Issue by cheveuxroux69** [justingit/dada-mail#829]
Unable to subscribe a new user to a list when logged in as Dada Mail Root. Either a documentation fault or a coding error (depending on expected result)
Set up: Public list with "Allow subscriptions in the List Control Panel, without confirmation" unticked
Try to subscribe someone from the admin pages when logged in with Root password
Get warning "importing subscribers via the List Control Panel has been disabled" but the (?) tooltip next to it says "Certain features... are only enabled when logging into a mailing list with the Dada Mail Pro Root Password. You are currently logged in with the List password"
The error is that I *am* logged in with the Root password not the list password. The message should not give incorrect information about my login status and should make it easier to find which option I need to change in order to correct the problem ("Ensure "Alow subscriptions..." is ticked") -- OR should allow me to subscribe the address despite the setting in the control panel. 
![bug2](https://user-images.githubusercontent.com/3187201/62942001-42511200-bdcf-11e9-8e81-15364d2457ed.PNG)
![bug1](https://user-images.githubusercontent.com/3187201/62942003-42511200-bdcf-11e9-8d0d-e091eb150966.png)

**Comment by justingit** [comment]
Thanks for the report, I'll investigate and try to recreate this.

**Comment by justingit** [comment]
@cheveuxroux69 can you let me know what version of Dada Mail you're running? I'm not able to recreate the problem in the most recent version (currently v11.4.4)

**Comment by justingit** [comment]
Any input on the version you're using? I'm going to close this bug if I can't recreate it with the most recent version of the app,

**Comment by cheveuxroux69** [comment]
Hi Justin, running "11.4.4 Stable 07/26/19"

**Comment by cheveuxroux69** [comment]
Just tested it again and the tooltip error is there, although the subscribe logic works as expected:
- "Allow subscriptions in the List Control Panel, without confirmation" unticked
- logged in with Root password
- try to add subscriber, tooltip says "You are currently logged in with list password" which is incorrect.

**Comment by cheveuxroux69** [comment]
The mistake is in add_email_import_subscribers_disabled.tmpl
root_login = 1
list_settings.enable_mass_subscribe = 0
list_settings.enable_mass_subscribe_only_w_root_login = 0
Line 5 then evaluates as follows:
( 0 == 1 && (  ( 1 == 1 ) || ( 0 != 1) )
( false && ( (true) || (true) )
( false && true) 
( false )
tmpl_unless false is then true and the block is output.
The block contains the text "You are currently logged in with the List Password"
Looking at the logic, this text is output regardless of the value of root_login because if "list_settings.enable_mass_subscribe_only_w_root_login != 1" is true, the value of root_login is irrelevant anyway?

**Comment by justingit** [comment]
Thanks for the followup, I'll look deeper into this,
