### ISSUE TITLE
What happens when there's not an HTML-version of a email template in the theme? 

### ISSUE THREAD

**Issue by justingit** [justingit/dada-mail#839]
As in, if you remove a HTML-version of the email template, will the plaintext-only version be used, or will a default, HTML-version be used (grabbed from... somewhere?) 

This behavior should be specifically documented. I'm leaning on, "well, the text version will ONLY be used...)

**Comment by admorgan** [comment]
I agree with text version will ONLY be used

**Comment by justingit** [comment]
Using the default theme's version of a missing file is explicitly what the app is supposed to do, as the comment here notes, in a sub that basically does just this: 

https://github.com/justingit/dada-mail/blob/8f6bdb2d7c6cdc8890b66f00297c14c3278626e0/dada/DADA/App/EmailThemes.pm#L200

I'll change this from a bug (which it really isn't) to a feature request.

**Comment by justingit** [comment]
I'm closing this, as the answer to the question has been made, and it was documented all along.
