### ISSUE TITLE
Mystery unsubscriptions

### ISSUE THREAD

**Issue by gagutman** [justingit/dada-mail#851]
At least two members of my list were unsubscirbed without any request from them or from me. I was able to re-subscribe them successfully, but I'd like to prevent this from happening in future.

**Comment by justingit** [comment]
For an issue report, I'll need a way to recreate the problem (so: closing). Here's though what I think may be happening, and ways to solve it: 

https://blog.dadamailproject.com/2019/04/26/dada-mails-new-unsubscription-options-v11-3-0/
