### ISSUE TITLE
Error when creating mailing list w/List Consent

### ISSUE THREAD

**Issue by justingit** [justingit/dada-mail#856]
The app will error out during list creation, if you have a list consent. Error reported is the following: 

`
Undefined subroutine &DADA::MailingList::strip called at DADA/MailingList.pm line 81, <CONFIG> line 1.`

This is a quick fix.... (just import DADA::App::Guts) but why wasn't this error caught in the test suite? This issue should not be closed until this is checked in the test suite.

**Comment by vvsms** [comment]
Hello Justin,
from where to import DADA::App::Guts
