### ISSUE TITLE
Log IP behind a proxy

### ISSUE THREAD

**Issue by wmalgadey** [justingit/dada-mail#861]
dadamail doesn't regognize the `X-Real-IP` or `X_HTTP_FORWARDED_FOR` header, which is added -for example by nginx- proxy

**Comment by justingit** [comment]
Thanks for the report. Can you give me instructions on how you can recreate the problem?

**Comment by wmalgadey** [comment]
hi justin!

i am using a nginx proxy behind apache running dadamail with fastcgi. nginx adds the real_ip header, because remote_addr is the ip of the proxy:

```
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
```

```
HTTP_X_FORWARDED_FOR [89.0.xxx.xx]
HTTP_X_REAL_IP [89.0.xxx.xx]
REMOTE_ADDR [192.168.150.29]
REMOTE_PORT [52854]
```

this are the environment parameter. And in my concent-logs I always get the `REMOTE_ADDR` instead of the `REAL_IP`.

**Comment by justingit** [comment]
So am I looking for, X-Real-IP or, HTTP_X_REAL_IP in the environment? And is, 

        roxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;

Something standard?

**Comment by justingit** [comment]
also, can you walk me through an instance where something is logged, and this isn't logged correctly? Dada Mail can log many thing. I'm trying to target exactly where this problem is happening.

**Comment by wmalgadey** [comment]
Thank you for your efforts. I think perl is doing some of this already by itself. I tested dadamail on my local network and saw only a known IP instead of the external one.

My problem was, that in the subcriber history, I didn't saw external IP-Addresses. But this actually works.

So I think, my problem does not exists. Everything is fine with dadamail behind a proxy :)
