### ISSUE TITLE
No acces to 'Administration' options

### ISSUE THREAD

**Issue by LonTrailRufus** [justingit/dada-mail#866]
When I select 'Administration' from mail.cgi I am asked to select a mailing list and password. The page refreshes with the main screen--not the administration options.

I have switched domain hosts and installed 11_5_0. The hourly cron job sends out messages fine, using the configuration imported from the previous domain host. I tried with the new administration password and a unencrypted password. Nothing in the error log.

How do I get to the Administration options?

**Comment by LonTrailRufus** [comment]
I may have a solution--don't waste time responding until I work it out.
(Stale mysql reference in .config; administration silently died but left a log message about a bad SQL connection.)

**Comment by justingit** [comment]
My guess would be a misconfiguration in the app or even the webserver itself (http vs https), a redirect set in the webserver, the webserver not relaying something like POST variables - stuff like that. I don't think it's a bug though, so if you don't mind, I would like to close this.

**Comment by LonTrailRufus** [comment]
Justin--
Thanks for the hint about https: I can figure it out now.
OK to close it.
