### ISSUE TITLE
New Template Tag: Authorized Sender Email Address

### ISSUE THREAD

**Issue by dickmo** [justingit/dada-mail#874]
My system is used by our club newsletter and in the body of the emails I want to identify the real sender of the newsletter. In the announcement-only I have set the reply to    to the real sender. I would like to identify the real sender in the body but am not able to find an existing variable that identifies it.   Is there One ?  
I had to modify your code to create it in the /DADA/Mail/Send.pm  which I rather not do if it exists somewhere else.  If it does not exist or I cannot reference it can it be created in another version. 
If you would like to see the code that I created I have attached it.  It starts at line 844 and ends at 866.
The variable I made    $vars->{'reply_sender.email'}   = $e2; 

[Send-modified-n.txt](https://github.com/justingit/dada-mail/files/3870397/Send-modified-n.txt)

**Comment by justingit** [comment]
Can you give me a little background? Is this is an announcement list, but sent through bridge by an authorized sender? You want to show the email address of the authorized sender?

**Comment by dickmo** [comment]
Yes it is an announcement list   that is a mass mailing   so thru the 
bridge

In the body of the message at the bottom I show the member who really 
sent the email (authorized sender)
Here is what the body looks like

Top of the body of message

Bla bla bla etc  .. .. .. .. .. .


This is the bottom of the body
----------------------------------------------------------

Sent from the South Bay Cruising Club by
mizzmara@aol.com                                       this is the field 
that I created in the send.pm code as I could not find a variable

Visit Our Web Site at  https://sbccsail.org
Visit Our Racing Web Site at  https://www.sbccracing.org/
Visit Our FaceBook account at  
https://www.facebook.com/groups/southbaycruisingclub/?ref=bookmarks

To Unsubscribe from this newsletter click below
https://newsemails.sbccsail.org/dada/mail.cgi/t/beFUs5gToNyIoEK7VHveonqcETj4guamKKiE32KV/



Code in the custom mailing  layout screen

  


<br />   <br />  <br /> 
----------------------------------------------------------
<br />
<img src="https://newsemails.sbccsail.org/SBCC_Logo3b.jpg" />
  <br />
Sent from the South Bay Cruising Club by  <br /> 

<br /> <br />  Visit Our Web Site at &nbsp; 
<br />  Visit Our Racing Web Site at &nbsp; 
<br />  Visit Our FaceBook account at &nbsp; 

<br /> <br /> To Unsubscribe from this newsletter click below <br /> 




Richard Mourino




------ Original Message ------

**Comment by justingit** [comment]
Gotcha

**Comment by justingit** [comment]
_(Note to myself: double-check that messages sent by authorized senders which aren't changed to use the list owner are being properly re-written like we do for discussion messages. )_

**Comment by dickmo** [comment]
Just to be clear.
Your code works great    but there is no variable that I can reference 
in the Mass mailing Layout screen "Who send the email".
That is why I created the additional variable in the send.pm   script.
An I am asking you to add a new variable that I can reference without 
changing your code as an Enhancement.
Thank You

Richard Mourino



------ Original Message ------

**Comment by justingit** [comment]
> An I am asking you to add a new variable that I can reference without 
changing your code as an Enhancement.

Yeah, I gotcha.

**Comment by justingit** [comment]
Be on the lookout in the next point release - I'll have the ability to find this info out, using the template tag: 

`<!-- tmpl_var sender.email --> `

(and friends).
