### ISSUE TITLE
Mail server upgrade broke mailing lists

### ISSUE THREAD

**Issue by cexclamation** [justingit/dada-mail#887]
After Bluehost migrated the mail server to a new server, all the mailing lists stopped working. A test message generates this error in the log.

Using the default of SSL_verify_mode of SSL_VERIFY_NONE for client
is deprecated! Please set SSL_verify_mode to SSL_VERIFY_PEER
together with SSL_ca_file|SSL_ca_path for verification.
If you really don't want to verify the certificate and keep the
connection open to Man-In-The-Middle attacks please set
SSL_verify_mode explicitly to SSL_VERIFY_NONE in your application.
at /home3/gornahoo/public_html/cgi-bin/dada/DADA/perllib/Mail/POP3Client.pm line 372.

Version: 10.5.4 Stable 05/16/17

Nothing else has changed. Is there a workaround for this?
This issue has been reported before, but was closed without explanation.

**Comment by cexclamation** [comment]
Odd that messages that were queued for the past day or two, are suddenly being sent. But I am not getting the Mail Complete message, presumably because of the SSL_verify_mode error.

**Comment by justingit** [comment]
This is less a bug in Dada Mail, and more a problem communicating with the mail server. My suggestion though would be to upgrade to the latest version, then if the problem isn't fixed, use one of the support channels listed at, 

https://dadamailproject.com/support/

**Comment by cexclamation** [comment]
I agree that it is not a dada mail bug.

It seems that the error occurs when sending to the list owner; e.g., “mass mailing complete” message, subscription requests

 

Blue host changed the email server, so I assume there needs to be a setting to identify the new host. I can’t find it anywhere. Nor can I find out where to set the SSL_verify_mode.

 

I’d like to start keeping the dada version up to date, so, yes, we can move forward with the quote. However, I don’t want to pay $300 and still end up with errors.

 

I’ll send you the cpanel login tomorrow.

**Comment by justingit** [comment]
> I’d like to start keeping the dada version up to date, so, yes, we can move forward with the quote. However, I don’t want to pay $300 and still end up with errors.

Sure, I'm happy to back up the work with a complete guarantee that I can fix the problem, or a full refund. 

Do make sure to send the login via my actual email address (justin@dadamailproject.com), and not through the Github issues system - if you do the latter, it may get posted on Github!

-- 

Justin J: Lead Dadaist. 
url:         http://dadamailproject.com
email:    justin@dadamailproject.com
twitter:  @dadamail
skype:   leaddadaist

Dada Mail Announcements: 
http://dadamailproject.com/cgi-bin/dada/mail.cgi/list/dada_announce/

**Comment by cexclamation** [comment]
I’m sure there is a setting for the SMTP server that needs to change.

 

Bluehost file manager won’t show hidden files, namely  .dada_files  … I assume that is where it is

 

So I’ll stop looking for it and let you set it up.
