### ISSUE TITLE
New "Dada Mail Support Forum" is not usable as one cannot register due to missing confirmation code image

### ISSUE THREAD

**Issue by frederickjh** [justingit/dada-mail#916]
@justingit I tried several days ago to use the contact us form on the [Dada Mail Support Forum](https://forum.dadamailproject.com/phpBB3/index.php) to contact you about this, but since the forum registration is broken I was not sure what else is broken or not configured too. So, I decided to create an issue here. Sorry if you already got the email via the contact us about this.

Currently the **Dada Mail Support Forum** is not usable as one cannot register due to missing confirmation code image. My guess is that there is a missing API key to allow getting the image. Since the forum was setup in November there have only been posts by the only user **dadamail**.

I was hoping to post a question about email theming  in Dada Mail but was unable to register on the forum to do so. I also did not see an appropriate section to post a question about this on the forum no a general question section, so maybe you want create one or both of those sections.

Thanks for your work on Dada Mail and for setting up the **Dada Mail Support Forum**!
Frederick

**Comment by justingit** [comment]
Thanks for letting me know! I had absolutely no idea,
