### ISSUE TITLE
Bridge - Email encoding

### ISSUE THREAD

**Issue by frederickjh** [justingit/dada-mail#917]
First off I am using the newest version of Dada Mail 11.10.1 Stable 3/24/20. The installation is use to send emails via the Bridge plugin. As far as I can tell the senders to the list do not login to send email, but both Tiny MCE and CKeditor have been installed to allow this.

### What does work 
When an email to a list email address is sent that includes special characters like German umlauts (ä Ä ö Ö ü Ü) in either the title or the message body this is send out to the list and displays correctly.

![image](https://user-images.githubusercontent.com/864159/79737479-aa131180-82fb-11ea-919f-cdf7f96e0e65.png)

#### Sender Response Messages - Message titles containing special characters
When a response email message is sent to a sender of an email to a bridge email address that includes special characters like German umlauts (ä Ä ö Ö ü Ü) in either the title of the sent message, this is not displayed correctly. The screenshot below is the response email for the test message above.

![image](https://user-images.githubusercontent.com/864159/79737932-5c4ad900-82fc-11ea-80bd-7ac87d68f7f1.png)

the message above should read:
> Thanks, xxxxxxxxxx. Your message with the subject, **A test message with umlauts ä Ä ö Ö ü Ü** will be delivered to, Testing ASAP!

#### Translated Sender Response Messages containing special characters
The previous messages were sent using the **default** email theme that comes with Dada Mail. If I switch to using the **Default-de** theme from [ holzhannes/dada_mail_email_themes-de-formal ](https://github.com/holzhannes/dada_mail_email_themes-de-formal) that has German text messages that include special characters then another issue is seen.

![image](https://user-images.githubusercontent.com/864159/79739061-ef384300-82fd-11ea-82dd-371ed773ca50.png)

In the green box you see the word **baldmöglichst** which contains the German umlaut ö.  It should look like this.:
![image](https://user-images.githubusercontent.com/864159/79739233-31fa1b00-82fe-11ea-889b-00b1489f3395.png)

I will post source code from the email sent to help diagnose this further in my next comments on this issue.

**Comment by frederickjh** [comment]
Looking at the source of the emails sent out using the **Default** theme we see that the **Content-Transfer-Encoding** is different.

Source code of the email sent to the list:
![image](https://user-images.githubusercontent.com/864159/79751675-48f73800-8313-11ea-901b-01f2b30c3a6e.png)

Source code of the email sent to the sender of the email via the bridge plugin:
![image](https://user-images.githubusercontent.com/864159/79751720-5c0a0800-8313-11ea-8c8b-1acb76be2064.png)

**Comment by frederickjh** [comment]
Taking a look at the emails sent out using the **Default-de** theme we see that the template text is not being encoded into UTF-8.

Here is the source code of the email sent to the sender of the email. Notice that the **ö** in baldmöglichst is not encoded.

![image](https://user-images.githubusercontent.com/864159/79752616-e9019100-8314-11ea-914b-51439a296d14.png)

Now look at the source code of the email sent to the list that is presented correctly. Notice that the umlauts themselves do not appear in the source code but are encoded.

![image](https://user-images.githubusercontent.com/864159/79753087-a3919380-8315-11ea-8cb6-0a3805f37a8e.png)

**Comment by justingit** [comment]
@frederickjh, thank you for this very thorough issue report. There's a lot going on and I may split this issue you've opened into multiple issues. But, I think discussion of the issues you have brought up would be easiest to do here for now.

**Comment by justingit** [comment]
**Sender Response Messages - Message titles containing special characters**
This is most clearly a bug, and I'll open a separate issue for this: https://github.com/justingit/dada-mail/issues/919

**Comment by justingit** [comment]
**Translated Sender Response Messages containing special characters**
Seems like a clear bug, as well. Opened up an issue:  https://github.com/justingit/dada-mail/issues/920

**Comment by justingit** [comment]
For some of the other issues you're reporting, what have you set the **Default Plain Text Message Encoding** and, **Default HTML Message Encoding** in the list control panel under, 

_Sending: Advanced Options_

?

**Comment by frederickjh** [comment]
@justingit here are the setting you asked for.

![image](https://user-images.githubusercontent.com/864159/79835301-c3c16100-83ae-11ea-9c8e-1d477c808e44.png)

I have not changed these recently. It has been a long time since I would have changed these settings. I did recently upgrade from version 9.1.1, so maybe what these setting should be has changed with the newer versions.

**Comment by frederickjh** [comment]
@justingit I am closing this issue as #920 was solved by changing the encoding to *quoted-printable* and you have #919 open for the other issue.
