### ISSUE TITLE
Broken link in Email Themes Documenation

### ISSUE THREAD

**Issue by frederickjh** [justingit/dada-mail#921]
I looked to see if you had a separate repository for the Dada Mail documentation, but I did not find one, otherwise I would have submitted a pull request for this issue.

On the [Email Themes](https://dadamailproject.com/support/documentation-11_10_1/features-email_themes.pod.html) page in the section [Create a New Email Theme Using the Foundation for Emails Workflow](https://dadamailproject.com/support/documentation-11_10_1/features-email_themes.pod.html#Create-a-New-Email-Theme-Using-the-Foundation-for-Emails-Workflow) the link: 
~~http://foundation.zurb.com/emails/docs/sass-guide.html~~
does not work nor redirect to the new page at 
https://get.foundation/emails/docs/sass-guide.html

![image](https://user-images.githubusercontent.com/864159/79841986-81048680-83b8-11ea-9682-f5a89a15c314.png)

**Comment by justingit** [comment]
Thanks again @frederickjh for the issue report.

**Comment by justingit** [comment]
Thanks again @frederickjh for the issue report.

**Comment by justingit** [comment]
Thanks again @frederickjh for the issue report.

**Comment by frederickjh** [comment]
:+1:  :smiley:

**Comment by justingit** [comment]
Hi @frederickjh, you don't have to close the issues manually. When the code changes are committed, they'll be closed automatically (and not before) 

Cheers,
