### ISSUE TITLE
Dadamail Unsubscribe not working

### ISSUE THREAD

**Issue by inet-dsps** [justingit/dada-mail#923]
Hi,

Please advice how can i get my unsubscribe link to appear correctly on the footer of my email.
Im not using any built in dadamail template.  However, Im sending the mail throught bridge and gets forwarded from my custom application.

This is the code i used on my aspx application . cs file:

message.Body += "<br />Should you require any further information, please do not hesitate to contact us or visit our website at <a href='http://www.domain.com.fj'>www.domain.com.fj</a> "
             + "<br /><br />Thank you<br /><br />" + 
                "Address here<br />" + 
                "Phone:  999 9999<br />" + 
                "<a href=''>Click here to unsubscribe</a>" +
              "</tr></td></table></body></html> ";

This is the output i get  on email im seeing the actual html code:
![image](https://user-images.githubusercontent.com/63686906/80323691-10121280-8881-11ea-88b0-ce674048003f.png)

Im using the dadamail version  11.10.1 , kindly assist, am i missing something?

Thanks.

**Comment by justingit** [comment]
This is not a support forum, please use the appropriate place to ask such questions.
