### ISSUE TITLE
Error editing Profile Fields NAME value

### ISSUE THREAD

**Issue by dakuzen** [justingit/dada-mail#924]
** When using SQLite ** 

If you attempt to edit the Field Name value of an existing Profile Field, the Field Name will not update but all other values (Label, Fallback Value, Required Flag) are erased.  

No error is rendered on screen.

**Comment by justingit** [comment]
What version of the app are you using? 

What backend are you using (Mysql, PostgreSQL, SQLite)

**Comment by justingit** [comment]
Thanks for clarifying which backend you're using. Can you also let me know which version of the app you're running?

**Comment by justingit** [comment]
Nevermind about the version - I've tested this with the most recent version, and can recreate the bug. Thank you for this report.

**Comment by justingit** [comment]
Confirm that it doesn't seem to affect MySql backend. Funny that this hasn't been caught by the testing suite.

**Comment by justingit** [comment]
Aha, doesn't look like renaming columns is support in Dada Mail, if you're using the SQLite backend. So, I won't be adding this support (soon), but I will make sure that renaming support isn't something available. Here's the error that gets posted to the error log if you do this: 

`sorry! renaming columns is currently not available for the SQLite backend!`
