### ISSUE TITLE
Error Log item Information

### ISSUE THREAD

**Issue by jbarsuglia** [justingit/dada-mail#940]
I am working on a new installation of dadamail pro. the cronjob is spooling off these error log messages. There are no active emails on the bounce handler email associated account.
Is this indicative of an issue to correct?

[Wed Jun  3 06:45:13 2020] mail.cgi: running scheduled jobs at teardown @ Wed Jun  3 06:45:13 2020 at /home3/kulakswo/public_html/dada//DADA/App.pm line 381.
running scheduled jobs at teardown @ Wed Jun  3 08:08:09 2020 at /home3/kulakswo/public_html/dada//DADA/App.pm line 381.
running scheduled jobs at teardown @ Wed Jun  3 08:08:24 2020 at /home3/kulakswo/public_html/dada//DADA/App.pm line 381.
[Wed Jun  3 08:08:24 2020] mail.cgi: running scheduled jobs at teardown @ Wed Jun  3 08:08:24 2020 at /home3/kulakswo/public_html/dada//DADA/App.pm line 381.
running scheduled jobs at teardown @ Wed Jun  3 08:08:24 2020 at /home3/kulakswo/public_html/dada//DADA/App.pm line 381.
[Wed Jun  3 08:08:25 2020] mail.cgi: PID: 441044 Semaphore does not exist to delete at, '/home3/kulakswo/.dada_files/.tmp/_scheduled_tasks.lock at /DADA/App/ScheduledTasks.pm line 210.
[Wed Jun  3 08:18:25 2020] mail.cgi: running scheduled jobs at teardown @ Wed Jun  3 08:18:25 2020 at /home3/kulakswo/public_html/dada//DADA/App.pm line 381.

**Comment by justingit** [comment]
These are not lines produced by the cronjob, but the could indicate that the cronjob isn't being fired correctly - the times aren't very normalized, as they would be a on cronjob schedule. "running scheduled jobs at teardown" is the message printed to the error log when the schedule is just run after the app's job is done serving a user through the web browser. 

Here's the support forum -

https://forum.dadamailproject.com/

 this isn't an actual issue, so I'd appreciate if we could move this over to there, where I can help you. (or email me directly if you're a Pro Dada subscriber)
