### ISSUE TITLE
Internal server error when saving draft

### ISSUE THREAD

**Issue by rotarypot** [justingit/dada-mail#948]
Hi Justin :)

when trying to either send a test of a new draft or saving a draft, i get an internal server error dialog, and upon checking the log found this.

_Column 'created_timestamp' cannot be null at DADA/MailingList/MessageDrafts/baseSQL.pm line 233.
cannot do statement 'INSERT INTO dada_message_drafts (list, role, draft, created_timestamp, last_modified_timestamp) VALUES (?,?,?, NULL, NULL)'! Column 'created_timestamp' cannot be null
 at DADA/App/MassSend.pm line 1715._

is this an issue with my server (dreamhost VPS) ?

Please let me know if you need more info.

**Comment by justingit** [comment]
The latest version of Dada Mail requires MySQL v5.7 to work correctly. That's the first thing I would check.

**Comment by rotarypot** [comment]
My VPS uses a shared MySQL server which uses v5.7 
https://help.dreamhost.com/hc/en-us/articles/215099117

**Comment by justingit** [comment]
And what version of Dada Mail are you using?

**Comment by rotarypot** [comment]
According to the _About Dada_ menu 
_This is Pro Dada version 11.10.1 Stable 3/24/20_

**Comment by rotarypot** [comment]
Hi, @justingit , 
i just wanted to know if you need to know anything else, or is there anything i can try ?
let me know :)

**Comment by rotarypot** [comment]
@justingit 
i just tried saving drafts with a clean install of dada 11.10.3 and even though the saving works, the created timestamp shown on the UI is empty. Upon checking the database, its value its NULL.

![Annotation 2020-07-24 131735](https://user-images.githubusercontent.com/857684/88432179-91117500-cdb0-11ea-9ee3-503ace721921.jpg)

![Annotation 2020-07-24 132146](https://user-images.githubusercontent.com/857684/88432243-af777080-cdb0-11ea-9992-820a0fa3276a.jpg)

**Comment by justingit** [comment]
Are there lines of Dada Mail's own error log pertaining to saving a draft?

**Comment by rotarypot** [comment]
well, 
just  this

_DBD::mysql::st execute failed: Column 'last_modified_timestamp' cannot be null at DADA/MailingList/MessageDrafts/baseSQL.pm line 233.
cannot do statement 'INSERT INTO dada_message_drafts (list, role, draft, created_timestamp, last_modified_timestamp) VALUES (?,?,?, NULL, NULL)'! Column 'last_modified_timestamp' cannot be null_

**Comment by justingit** [comment]
Again, that's what happens when the MySQL version is < 5.7. You can try removing that table, and creating it again. This should be the correct schema for the table, 
```


CREATE TABLE IF NOT EXISTS dada_message_drafts (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
list varchar(16),
created_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
last_modified_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
name varchar(80), 
screen varchar(80),
role varchar(80),
draft mediumtext
);
```

**Comment by rotarypot** [comment]
> Again, that's what happens when the MySQL version is < 5.7. You can try removing that table, and creating it again. This should be the correct schema for the table,
> 
the MySQL version was indeed 5.7

I think that the problem was that i exported the database from a dada version prior to the latest one, and restored said batabase into a current dada version.

The problem was resolved by dropping the _dada_message_drafts_ table and re-creating it with the correct schema as indicated above.

**Comment by justingit** [comment]
Hmm, strange - as schema updating should be done by default by the app automatically.
