### ISSUE TITLE
Changing value of  mailing_list_message_subject  in Config.pm does not work

### ISSUE THREAD

**Issue by frederickjh** [justingit/dada-mail#951]
Hi @justingit !
I have been trying to trace this down but I was unable to figure it out. 
When sending emails via the bridge, the list name in the subject is surrounded by square brackets ([]), but not when you send an email out via the web interface. I believe it use to also have the square brackets around the list name as the default.

In trying to add the square brackets  to the default I edited dada/DADA/Config.pm and changed:

`mailing_list_message_subject     => '<!-- tmpl_var list_settings.list_name --> Message',`
to
`mailing_list_message_subject     => '[<!-- tmpl_var list_settings.list_name -->] -  Message',`

but when I create a new draft in the web interface, I still do not have the square brackets around the list name.

Any ideas what I am doing wrong?
Thanks in advance for your time and help!
Frederick

**Comment by justingit** [comment]
If you've set up your mailing list as a discussion list, the list name in brackets is applied after the message is submitted through the UI - there's nothing you'd have to do to make it work for messages sent through Dada Mail. 

The `mailing_list_message_subject` list setting isn't used for anything except setting a default for the custom mailing list subject you'll see in **Appearance: Custom Mass Mailing Layout**, and per-list you can change it there. 

The default subject you see in the Send a Message screen is set using the layout templates.

**Comment by frederickjh** [comment]
@justingit the list is not a discussion list. It is an information list.

If I go in to **Appearance > Custom Mass Mailing Layout** and set `mailing_list_message_subject`, what I set does not appear as the default subject unless I go into **Mass Mailing > Options** and set **Default Mass Mailing Layout** to custom. However then my custom them that I made with Foundations for Emails that I set under **Appearance > Email Themes** is not shown only black text on a white background, which of course is also not what I want.

**Comment by frederickjh** [comment]
I would like to use the full layout but change the default subject. What is the recommended way to do this?

**Comment by justingit** [comment]
> If I go in to Appearance > Custom Mass Mailing Layout and set mailing_list_message_subject, what I set does not appear as the default subject unless I go into Mass Mailing > Options and set Default Mass Mailing Layout to custom. 

Correct. 

 > However then my custom them that I made with Foundations for Emails that I set under Appearance > Email Themes is not shown only black text on a white background, which of course is also not what I want.

Correct - you are now using a custom Mass Mailing Layout (since that's what you chose) 

> I would like to use the full layout but change the default subject. What is the recommended way to do this?

Change it in the theme file, itself. The subject would be set in, "mailing_list_message.txt"

**Comment by frederickjh** [comment]
Thanks @justingit! That is exactly what I was looking for!
