### ISSUE TITLE
After upgrade to 11.11.0 the send menu in the SEND_A_MESSAGE page is loading forever

### ISSUE THREAD

**Issue by hvillemoes** [justingit/dada-mail#952]
Browser: New Edge, Chrome and Firefox.
See attached screendump.
![Capture](https://user-images.githubusercontent.com/17951407/89718634-62a2b500-d9c0-11ea-8e7d-8d97cbb347cb.PNG)

**Comment by justingit** [comment]
My guess is that a javascript file is in your browser cache, and the new version of the javascript file is not loading, causing this problem. Clear the browser cache, and see if that helps. If not, paste the errors being logged in the browser's console.

**Comment by hvillemoes** [comment]
Hi Justin 

The problem was, that the filestructure at some point was changed from using the dir: dada_mail_support_files to using the extras dir. 
I have for a long time copied the dada_mail_support_files from old to new version during update in order to make it work (after an unsuccesfull errormessage to you at some point). 

And now this old version of support files no longer works in 11_11_0 

So I will make a new empty installation, edit the .config file to reflect my installation and cp -r this over the working 11_10_2 directory. 

Or do you have a better idea? A plain web-installer update does not work. 

Med venlig hilsen 

Harald Villemoes 
Ramten Hedevej 10, 8586 Ørum Djurs 
tlf: +45 20305193 / email: harald@villemoes.dk 


Fra: "Justin J" <notifications@github.com> 
Til: "justingit/dada-mail" <dada-mail@noreply.github.com> 
Cc: "Harald Villemoes" <harald@villemoes.dk>, "Author" <author@noreply.github.com> 
Sendt: søndag, 9. august 2020 22:01:14 
Emne: Re: [justingit/dada-mail] After upgrade to 11.11.0 the send menu in the SEND_A_MESSAGE page is loading forever (#952) 





My guess is that a javascript file is in your browser cache, and the new version of the javascript file is not loading, causing this problem. Clear the browser cache, and see if that helps. If not, paste the errors being logged in the browser's console.

**Comment by justingit** [comment]
The files in the dada_mail_support_files directory are managed by the installer, and new copies of things like the javascript libraries are added in, while the old copies are backed up, then later: removed. Nowhere in the instructions does it say you can or should do this manually. So, if that's where you're problems are coming from, that's the real bug, I guess. 

As to why this isn't working for you - separate issue. My guess is that there's a file/directory user permission issue you should straighten out, so that the app has the permission to work with the dada_mail_support_files directory.

**Comment by hvillemoes** [comment]
Hi again 

I'm sorry, but for the last many updates, the updater has not created the dada_mail_support_files directory. 
Consequently I have copied the old dada_mail_support_files dir to the new dada dir. 
And until v.11.11.0 this fix has worked. 

Is it possible for me to make a new install and somehow copy the configuration and history to this new installation? 
Or how do I debug the update script to see, why it does not create the dada_mail_support_files directory? 

The GUI shows no errors during or after the update. 

I would be unhappy to stay on v.11.10.2 forever. 


Kind regards 

Harald Villemoes 
Ramten Hedevej 10 
DK-8586 Ørum Djurs 
Denmark 
ph: +45 20305193 - email: harald@villemoes.dk 


Fra: "Justin J" <notifications@github.com> 
Til: "justingit/dada-mail" <dada-mail@noreply.github.com> 
Cc: "Harald Villemoes" <harald@villemoes.dk>, "Author" <author@noreply.github.com> 
Sendt: tirsdag, 11. august 2020 21:13:37 
Emne: Re: [justingit/dada-mail] After upgrade to 11.11.0 the send menu in the SEND_A_MESSAGE page is loading forever (#952) 





The files in the dada_mail_support_files directory are managed by the installer, and new copies of things like the javascript libraries are added in, while the old copies are backed up, then later: removed. Nowhere in the instructions does it say you can or should do this manually. So, if that's where you're problems are coming from, that's the real bug, I guess. 

As to why this isn't working for you - separate issue. My guess is that there's a file/directory user permission issue you should straighten out, so that the app has the permission to work with the dada_mail_support_files directory.

**Comment by justingit** [comment]
> I'm sorry, but for the last many updates, the updater has not created the dada_mail_support_files directory.
> Consequently I have copied the old dada_mail_support_files dir to the new dada dir.
> And until v.11.11.0 this fix has worked.

You've been lucky, but that idea is not something which is documented to have ever worked. 

> Is it possible for me to make a new install and somehow copy the configuration and history to this new installation?

You just described how the upgrade process works. 

> Or how do I debug the update script to see, why it does not create the dada_mail_support_files directory?

The installer does create an error log. In the, dada/installer directory, look for a file named, "installer_errors.txt"  

> The GUI shows no errors during or after the update.

So, then: how do you know that problems are occurring? The problem of not being able to create new files/directories in the dada_mail_support_files directory or creating that directory itself would be reported in the UI.

**Comment by hvillemoes** [comment]
Hi 

I solved my problem by establishing a brand new server and installing dada 11.11.1 
Then I dumped the old system mysql data, changed all dns refs. in the sql from the old server name to the new server name and imported it to the new system database. 

This seems to work fine, and functions on the new system seems to be ok. 

Thanks 


Kind regards 

Harald Villemoes 
Ramten Hedevej 10 
DK-8586 Ørum Djurs 
Denmark 
ph: +45 20305193 - email: harald@villemoes.dk 


Fra: "Justin J" <notifications@github.com> 
Til: "justingit/dada-mail" <dada-mail@noreply.github.com> 
Cc: "Harald Villemoes" <harald@villemoes.dk>, "Author" <author@noreply.github.com> 
Sendt: mandag, 17. august 2020 18:16:57 
Emne: Re: [justingit/dada-mail] After upgrade to 11.11.0 the send menu in the SEND_A_MESSAGE page is loading forever (#952) 







I'm sorry, but for the last many updates, the updater has not created the dada_mail_support_files directory. 
Consequently I have copied the old dada_mail_support_files dir to the new dada dir. 
And until v.11.11.0 this fix has worked. 



You've been lucky, but that idea is not something which is documented to have ever worked. 
BQ_BEGIN


Is it possible for me to make a new install and somehow copy the configuration and history to this new installation? 
BQ_END


You just described how the upgrade process works. 
BQ_BEGIN


Or how do I debug the update script to see, why it does not create the dada_mail_support_files directory? 
BQ_END


The installer does create an error log. In the, dada/installer directory, look for a file named, "installer_errors.txt" 
BQ_BEGIN


The GUI shows no errors during or after the update. 
BQ_END


So, then: how do you know that problems are occurring? The problem of not being able to create new files/directories in the dada_mail_support_files directory or creating that directory itself would be reported in the UI.
