### ISSUE TITLE
cron job fails with message "Scheduled Tasks may be running in a different process, stopping."

### ISSUE THREAD

**Issue by frederickjh** [justingit/dada-mail#969]
Hi!
The boss contacted me that he sent out an email last Friday via the bridge plugin but it never arrived. I went in and manually clicked the button to check and send emails and they got sent out.

I then sent a test message to my test list on the same Dada Mail installation. The cron job is running but the message do not get sent out. I changed the **_silent** in the cron job URL to **_verbose** as I use `cronic` to email when a job fails with an error code other than 0. So it seem that the job finishes without an error code being returned, but still no email sent.

Testing by calling the cron job URL in the browser return this:

![image](https://user-images.githubusercontent.com/864159/92398943-b91f2280-f129-11ea-9bf5-adb7d5146cf7.png)

Any idea what the  "Scheduled Tasks may be running in a different process, stopping." message means? I searched through the running processes on the server but I couldn't find anything that look like the same process. I am guessing a lock file did not get deleted. So, I am going to try a reboot instead of hunting for it.

**Comment by frederickjh** [comment]
Yep, that looks like it was the issue. After rebooting the server emails are being sent out. Found this in the log file `.dada_files/.logs/errors.txt`

```bash
Couldn't create an exclusive semaphore file at, '/home/username/domains/example.com/.dada_files/.tmp/_scheduled_tasks.lock'
```
If this happens again how does one check if it is safe to delete the lock file?

Also I see the cron job finishing with an error code of **0** as wrong. If the process is not running because of a stale lock file, I should be getting an email from the cron job and not from my boss. I think that in this case the cron job should return an error code of **1** or higher. That way I would get an email.

I know that this cron job can return an error code as occasionally it occasionally returns either the error code **6** or **7** but neither returns an error message as to what is going on.

**Comment by frederickjh** [comment]
Strangely today I got a bunch of email that the cron job failed with a different code **60**, but once again no output what so ever to help understand what happened. Is there a switch other than the **_venbose** one that would enable more output when the cron job fails?

Is there a list somewhere of the exit codes and their meaning?

**Comment by frederickjh** [comment]
Thanks @justingit for the info.

I did run it in the browser and I had the same issue. See the screenshot of the browser above. Anyway rebooting took care of it, but next time I will try removing the semaphore file. 

As to the output when the cron job errors out I just thought it strange that it pops out an error code with no other output.

**Comment by justingit** [comment]
> As to the output when the cron job errors out I just thought it strange that it pops out an error code with no other output.

It's not an error per say, it's just a message that's written out if Dada Mail feels that another process is running the schedules because the lockfile is around - running the schedule concurrently leads to race conditions, which is what the lockfile is trying to prevent. Seems like you have a stale lock - I'm not sure why. Lock files > 1 day old should be removed automatically.

**Comment by frederickjh** [comment]
Sorry, I believe I have been talking about two different things in this issue. Lets forget the error codes with no error message, as that could be another issue on its own.

Back to the cron job aborting but exits cleanly with a **0** all is OK. I still do not think that is correct. It should exit with an error code 1 or higher so  I would get informed by [cronic](https://habilis.net/cronic/).

**Comment by justingit** [comment]
I do disagree, as the lockfile existing isn't an error - it just says, "hey, schedules _could_ be running right now, let's not run the risk of running it twice". If there was certainty that something was wrong, then I think you have a point. There's valid reasons that these schedules could be running outside of the cronjob firing out, or the schedules running for a longer time than the cronjob is set to run them.

**Comment by frederickjh** [comment]
OK, I thought about what you said @justingit and it make sense. If someone uses the button to manually run the scheduled tasks or if a mailing going out takes longer than the recommended 5 minutes that the cron job is scheduled for, it does not make sense to error out.

Since this is the first time that I have had a stale lock file, I am going to leave this as maybe a once in a long time issue and close this.
