### ISSUE TITLE
Comma on the end of line 2462 of Guts.pm is a SQL syntax error

### ISSUE THREAD

**Issue by frederickjh** [justingit/dada-mail#970]
I checked the `error.txt` log file and found these lines over and over again., as cronjobs were returning error codes. Mostly **60**.
```perl
running scheduled jobs at teardown @ Tue Sep  8 16:34:49 2020 at /home/user/domains/example.com/public_html/cgi-bin/dada/DADA/App.pm line 381.
DBD::mysql::db do failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 at /home/user/domains/example.com/public_html/cgi-bin/dada/DADA/App/Guts.pm line 2452, <CONFIG> line 1.
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 at /home/user/domains/example.com/public_html/cgi-bin/dada/DADA/App/Guts.pm line 2464.
```

Line 2452 of `Guts.pm`  looks likethis:

`. " MODIFY COLUMN last_modified_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE`

Line 2464 is a closing curly bracket and seimcolon.

Here is the code block surrounding these lines.

```perl
                        if(
                                $m_info->{last_modified_timestamp}->{COLUMN_DEF} =~ m/00/
                        ) {
                                my $query =  'ALTER TABLE '
                                . $DADA::Config::SQL_PARAMS{message_drafts_table}
                                . " MODIFY COLUMN last_modified_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,";
                                my $sth = $dbh->do($query)
                                        or croak $dbh->errstr;
                                undef $query;
                                undef $sth;
                        }

                        else {
                                # warn "ALL SET!";
                        }
                }
        } catch {
                warn $_;
        };

    return 1;
}

```
The server is running MySQL version 5.7.31-0ubuntu0.18.04.1.

**Comment by justingit** [comment]
See there's a comma at the end of this line (right after, CURRENT_TIMESTAMP), 

```
				. " MODIFY COLUMN last_modified_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,";
```

Remove that, save the file, and see if that error comes back.

**Comment by frederickjh** [comment]
OK, @justingit  I have removed the comma and sent a test message.

This server is at my house and monitoring has been showing (and my kids have been telling me) that the Internet is not working for minutes at a time (~7 - 10). I have to wonder if this has anything to do with this. I am using the bridge so it is trying to check emails. Does it do a check to see if it has an internet connection before checking emails?
I find it weird that this would cause an error message about MySQL syntax. Otherwise this install is working correctly.

OK, message got sent and was received. The message in the log is:

`[Tue Sep  8 21:15:08 2020] mail.cgi: were reseting the from header?:1 at DADA/App/FormatMessages.pm line 1457.`

Nothing about MySQL syntax this time, but only time will tell.

**Comment by justingit** [comment]
> Nothing about MySQL syntax this time, but only time will tell.

Well, if the SQL runs correctly, it'll only run once, as the update to the SQL schema has been made.

**Comment by frederickjh** [comment]
I went back and took at look a the [blame for line 2462](https://github.com/justingit/dada-mail/blame/83fb6fab4e3277885b857f7ceb10ed883004fad3/dada/DADA/App/Guts.pm#L2464) and found that the comma was there. It looks like it came in work related to #820.

It appears that the comma is still there on the SQL on[ line 2462](https://github.com/justingit/dada-mail/blob/83fb6fab4e3277885b857f7ceb10ed883004fad3/dada/DADA/App/Guts.pm#L2464) in the current master branch.

**Comment by frederickjh** [comment]
@justingit I just created a pull request that fixes this.

**Comment by justingit** [comment]
I already have the fix in, https://github.com/justingit/dada-mail/commit/3647606c88f7d67bdbee55c210403d91b18ccc5b

(I try to create new branch outside master for most every changes, before merging them into master.). 

I appreciate the patch, though!
