### ISSUE TITLE
11.11.3: Installer error with POSIX

### ISSUE THREAD

**Issue by roxaloxa** [justingit/dada-mail#979]
```
Undefined subroutine &POSIX::strftime called at /home/dev1/public_html/_archives/dada/installer/..//DADA/Template/Widgets.pm line 2226.
```

Running into this with a fresh install on a new line that was added in 11.11.3 using POSIX.
![image](https://user-images.githubusercontent.com/556484/93287392-c10f4e80-f81c-11ea-813f-9771c7feb110.png)

Maybe isn't loaded at this point?

**Comment by justingit** [comment]
OMG I suck, 

the version that's up on SourceForge was a dev version mislabeled. I've uploaded a new version that shouldn't have the dev changes. If you could re-download it, I think you won't run into problems.

**Comment by roxaloxa** [comment]
Ah, that fixed it! Thanks!

**Comment by justingit** [comment]
Thanks again for the report, it's much appreciated.
