### ISSUE TITLE
SMTP Sending Option not working

### ISSUE THREAD

**Issue by RayGX** [justingit/dada-mail#980]
After years of using the sendmail sending option and having to constantly wrangle with mail not being delivered/forwarded, etc. I decided to switch to the SMTP sending option to see if delivery could be improved.  I can not get it to work despite using the settings that Bluehost recommends, as follows:
  SMTP server:  smtp.mydomain.org
  Port:  465
  Use Secure Sockets Layer (SSL): checked
  Upgrade from an insecure connection (STARTTLS): unchecked
  Verify SSL certificate: unchecked
  Set the sender of SMTP mailings to the list administration address: unchecked
  Use SMTP Authentication (SASL): checked
  Username/password:  set to an active email address in the same domain as the DADA installation
  Type: PLAIN

There are errors showing up in the DADA error log as follows when I attempt to send test messages:
[Mon Sep 21 09:08:23 2020] mail.cgi: SSL: enabled
[Mon Sep 21 09:08:23 2020] mail.cgi: STARTTLS: disabled
[Mon Sep 21 09:08:23 2020] mail.cgi: NOT Verifying SSL Certificate during connection
[Mon Sep 21 09:08:23 2020] mail.cgi: 
[Mon Sep 21 09:08:23 2020] mail.cgi:  at DADA/Mail/Send.pm line 571.
[Mon Sep 21 09:08:25 2020] mail.cgi: Use of uninitialized value in subroutine entry at /home4/txssaror/public_html/cgi-bin/dada/DADA/perllib/URI/Escape.pm line 184.
[Mon Sep 21 09:08:25 2020] mail.cgi: Use of uninitialized value in subroutine entry at /home4/txssaror/public_html/cgi-bin/dada/DADA/perllib/URI/Escape.pm line 184.
[Mon Sep 21 09:08:25 2020] mail.cgi: Use of uninitialized value in subroutine entry at /home4/txssaror/public_html/cgi-bin/dada/DADA/perllib/URI/Escape.pm line 184.
[Mon Sep 21 09:08:25 2020] mail.cgi: Problems sending via SMTP:Connecting to SMTP host:mail.txssar.org on port:465
[Mon Sep 21 09:08:25 2020] mail.cgi: SSL: enabled
[Mon Sep 21 09:08:25 2020] mail.cgi: STARTTLS: disabled
[Mon Sep 21 09:08:25 2020] mail.cgi: NOT Verifying SSL Certificate during connection
[Mon Sep 21 09:08:25 2020] mail.cgi: 
[Mon Sep 21 09:08:25 2020] mail.cgi:  at DADA/Mail/Send.pm line 571.

Are the errors what is preventing the sending of mail or should the SMTP sending settings be further modified?

RayGX

**Comment by RayGX** [comment]
Forgot to add that I am working with version 11.4.2

**Comment by justingit** [comment]
Use the Testing button in the mail settings to help with finding the right settings to use. For Bluehost, you should literally be able to simply use, "localhost" as the SMTP server, and keep everything literally default and be able to use sendmail. So, port set at, "AUTO", no authentication, and don't anything with SSL. This would use the same exact mail server as if you used the sendmail command though, so I wouldn't expect any difference in sending/delivery. Go with SES for a big improvement.

**Comment by RayGX** [comment]
As a follow-up, after finally getting to speak with a 3rd level Escalated Support engineer at Bluehost, they stated that they no longer support the use of SMTP sending by "outside" parties, which they consider DADA to be.  This is due to security issues necessitated by the new global email laws.
