### ISSUE TITLE
501 Error on 11.11.3

### ISSUE THREAD

**Issue by dennypaz** [justingit/dada-mail#981]
DadaMail 11.11.3
php 5.3.29

When sending an email the following was received.

Problem fetching URL:
$VAR1 = {
          'url' => 'https://dennyp.com/dennyptravel/newsletters/mailstyler/wild_wednesday.htm',
          'message' => 'Protocol scheme \'https\' is not supported (LWP::Protocol::https not installed)',
          'status_line' => '501 Protocol scheme \'https\' is not supported (LWP::Protocol::https not installed)',
          'code' => 501
        };

I'm not sure why it says "https is not supported". My web site is functioning with https. I can copy the url above and put it into a browser and it works.

Ideas?

Thanks.

**Comment by justingit** [comment]
The support missing is not about your site, but just a missing Perl CPAN module, which would need to be installed called,  `LWP::Protocol::https`

**Comment by dennypaz** [comment]
I migrated to a new server last night. I'll go take a look at the settings and components there. Thanks.
